/* 
 *
 * This file is auto-generated, do not edit. 
 *
 * lexphp.h - GtkScintilla PHP Lexer
 *
 */

#ifndef GTK_SCINTILLA_LEXER_PHP_H
#define GTK_SCINTILLA_LEXER_PHP_H

G_BEGIN_DECLS


/* Lexer states */
#define GTK_SCINTILLA_LEXER_PHP_STYLE_COMPLEX_VARIABLE 104
#define GTK_SCINTILLA_LEXER_PHP_STYLE_DEFAULT 118
#define GTK_SCINTILLA_LEXER_PHP_STYLE_HSTRING 119
#define GTK_SCINTILLA_LEXER_PHP_STYLE_SIMPLESTRING 120
#define GTK_SCINTILLA_LEXER_PHP_STYLE_WORD 121
#define GTK_SCINTILLA_LEXER_PHP_STYLE_NUMBER 122
#define GTK_SCINTILLA_LEXER_PHP_STYLE_VARIABLE 123
#define GTK_SCINTILLA_LEXER_PHP_STYLE_COMMENT 124
#define GTK_SCINTILLA_LEXER_PHP_STYLE_COMMENTLINE 125
#define GTK_SCINTILLA_LEXER_PHP_STYLE_HSTRING_VARIABLE 126
#define GTK_SCINTILLA_LEXER_PHP_STYLE_OPERATOR 127

		
G_END_DECLS

#endif /* ifndef GTK_SCINTILLA_PHP_H */
