/* 
 *
 * This file is auto-generated, do not edit. 
 *
 * lexxml.h - GtkScintilla XML Lexer
 *
 */

#ifndef GTK_SCINTILLA_LEXER_XML_H
#define GTK_SCINTILLA_LEXER_XML_H

G_BEGIN_DECLS

/* Lexer states */
#define GTK_SCINTILLA_LEXER_XML_STYLE_DEFAULT 0
#define GTK_SCINTILLA_LEXER_XML_STYLE_TAG 1
#define GTK_SCINTILLA_LEXER_XML_STYLE_TAGUNKNOWN 2
#define GTK_SCINTILLA_LEXER_XML_STYLE_ATTRIBUTE 3
#define GTK_SCINTILLA_LEXER_XML_STYLE_ATTRIBUTEUNKNOWN 4
#define GTK_SCINTILLA_LEXER_XML_STYLE_NUMBER 5
#define GTK_SCINTILLA_LEXER_XML_STYLE_DOUBLESTRING 6
#define GTK_SCINTILLA_LEXER_XML_STYLE_SINGLESTRING 7
#define GTK_SCINTILLA_LEXER_XML_STYLE_OTHER 8
#define GTK_SCINTILLA_LEXER_XML_STYLE_COMMENT 9
#define GTK_SCINTILLA_LEXER_XML_STYLE_ENTITY 10
#define GTK_SCINTILLA_LEXER_XML_STYLE_TAGEND 11
#define GTK_SCINTILLA_LEXER_XML_STYLE_XMLSTART 12
#define GTK_SCINTILLA_LEXER_XML_STYLE_XMLEND 13
#define GTK_SCINTILLA_LEXER_XML_STYLE_CDATA 17
#define GTK_SCINTILLA_LEXER_XML_STYLE_QUESTION 18
#define GTK_SCINTILLA_LEXER_XML_STYLE_VALUE 19

		
G_END_DECLS

#endif /* ifndef GTK_SCINTILLA_XML_H */
