/* 
 *
 * This file is auto-generated, do not edit. 
 *
 * lexau3.h - GScintilla Au3 Lexer
 *
 */

#ifndef GSCI_LEXER_AU3_H
#define GSCI_LEXER_AU3_H

G_BEGIN_DECLS

/* Lexer states */
#define GTK_SCINTILLA_LEXER_AU3_STYLE_DEFAULT 0
#define GTK_SCINTILLA_LEXER_AU3_STYLE_COMMENT 1
#define GTK_SCINTILLA_LEXER_AU3_STYLE_COMMENTBLOCK 2
#define GTK_SCINTILLA_LEXER_AU3_STYLE_NUMBER 3
#define GTK_SCINTILLA_LEXER_AU3_STYLE_FUNCTION 4
#define GTK_SCINTILLA_LEXER_AU3_STYLE_KEYWORD 5
#define GTK_SCINTILLA_LEXER_AU3_STYLE_MACRO 6
#define GTK_SCINTILLA_LEXER_AU3_STYLE_STRING 7
#define GTK_SCINTILLA_LEXER_AU3_STYLE_OPERATOR 8
#define GTK_SCINTILLA_LEXER_AU3_STYLE_VARIABLE 9
#define GTK_SCINTILLA_LEXER_AU3_STYLE_SENT 10
#define GTK_SCINTILLA_LEXER_AU3_STYLE_PREPROCESSOR 11
#define GTK_SCINTILLA_LEXER_AU3_STYLE_SPECIAL 12
#define GTK_SCINTILLA_LEXER_AU3_STYLE_EXPAND 13
#define GTK_SCINTILLA_LEXER_AU3_STYLE_COMOBJ 14
#define GTK_SCINTILLA_LEXER_AU3_STYLE_UDF 15

		
G_END_DECLS

#endif /* ifndef GSCI_AU3_H */
