/* 
 *
 * This file is auto-generated, do not edit. 
 *
 * lexave.h - GScintilla Avenue Lexer
 *
 */

#ifndef GSCI_LEXER_AVE_H
#define GSCI_LEXER_AVE_H

G_BEGIN_DECLS

/* Lexer states */
#define GTK_SCINTILLA_LEXER_AVE_STYLE_DEFAULT 0
#define GTK_SCINTILLA_LEXER_AVE_STYLE_COMMENT 1
#define GTK_SCINTILLA_LEXER_AVE_STYLE_NUMBER 2
#define GTK_SCINTILLA_LEXER_AVE_STYLE_WORD 3
#define GTK_SCINTILLA_LEXER_AVE_STYLE_STRING 6
#define GTK_SCINTILLA_LEXER_AVE_STYLE_ENUM 7
#define GTK_SCINTILLA_LEXER_AVE_STYLE_STRINGEOL 8
#define GTK_SCINTILLA_LEXER_AVE_STYLE_IDENTIFIER 9
#define GTK_SCINTILLA_LEXER_AVE_STYLE_OPERATOR 10
#define GTK_SCINTILLA_LEXER_AVE_STYLE_WORD1 11
#define GTK_SCINTILLA_LEXER_AVE_STYLE_WORD2 12
#define GTK_SCINTILLA_LEXER_AVE_STYLE_WORD3 13
#define GTK_SCINTILLA_LEXER_AVE_STYLE_WORD4 14
#define GTK_SCINTILLA_LEXER_AVE_STYLE_WORD5 15
#define GTK_SCINTILLA_LEXER_AVE_STYLE_WORD6 16

		
G_END_DECLS

#endif /* ifndef GSCI_AVE_H */
