/* 
 *
 * This file is auto-generated, do not edit. 
 *
 * lexasm.h - GScintilla Asm Lexer
 *
 */

#ifndef GSCI_LEXER_ASM_H
#define GSCI_LEXER_ASM_H

G_BEGIN_DECLS

/* Lexer states */
#define GTK_SCINTILLA_LEXER_ASM_STYLE_DEFAULT 0
#define GTK_SCINTILLA_LEXER_ASM_STYLE_COMMENT 1
#define GTK_SCINTILLA_LEXER_ASM_STYLE_NUMBER 2
#define GTK_SCINTILLA_LEXER_ASM_STYLE_STRING 3
#define GTK_SCINTILLA_LEXER_ASM_STYLE_OPERATOR 4
#define GTK_SCINTILLA_LEXER_ASM_STYLE_IDENTIFIER 5
#define GTK_SCINTILLA_LEXER_ASM_STYLE_CPUINSTRUCTION 6
#define GTK_SCINTILLA_LEXER_ASM_STYLE_MATHINSTRUCTION 7
#define GTK_SCINTILLA_LEXER_ASM_STYLE_REGISTER 8
#define GTK_SCINTILLA_LEXER_ASM_STYLE_DIRECTIVE 9
#define GTK_SCINTILLA_LEXER_ASM_STYLE_DIRECTIVEOPERAND 10
#define GTK_SCINTILLA_LEXER_ASM_STYLE_COMMENTBLOCK 11
#define GTK_SCINTILLA_LEXER_ASM_STYLE_CHARACTER 12
#define GTK_SCINTILLA_LEXER_ASM_STYLE_STRINGEOL 13
#define GTK_SCINTILLA_LEXER_ASM_STYLE_EXTINSTRUCTION 14

		
G_END_DECLS

#endif /* ifndef GSCI_ASM_H */
