/* 
 *
 * This file is auto-generated, do not edit. 
 *
 * lexasn1.h - GScintilla Asn1 Lexer
 *
 */

#ifndef GSCI_LEXER_ASN1_H
#define GSCI_LEXER_ASN1_H

G_BEGIN_DECLS

/* Lexer states */
#define GTK_SCINTILLA_LEXER_ASN1_STYLE_DEFAULT 0
#define GTK_SCINTILLA_LEXER_ASN1_STYLE_COMMENT 1
#define GTK_SCINTILLA_LEXER_ASN1_STYLE_IDENTIFIER 2
#define GTK_SCINTILLA_LEXER_ASN1_STYLE_STRING 3
#define GTK_SCINTILLA_LEXER_ASN1_STYLE_OID 4
#define GTK_SCINTILLA_LEXER_ASN1_STYLE_SCALAR 5
#define GTK_SCINTILLA_LEXER_ASN1_STYLE_KEYWORD 6
#define GTK_SCINTILLA_LEXER_ASN1_STYLE_ATTRIBUTE 7
#define GTK_SCINTILLA_LEXER_ASN1_STYLE_DESCRIPTOR 8
#define GTK_SCINTILLA_LEXER_ASN1_STYLE_TYPE 9
#define GTK_SCINTILLA_LEXER_ASN1_STYLE_OPERATOR 10

		
G_END_DECLS

#endif /* ifndef GSCI_ASN1_H */
