/* 
 *
 * This file is auto-generated, do not edit. 
 *
 * lexasymptote.h - GScintilla Asymptote Lexer
 *
 */

#ifndef GSCI_LEXER_ASYMPTOTE_H
#define GSCI_LEXER_ASYMPTOTE_H

G_BEGIN_DECLS

/* Lexer states */
#define GTK_SCINTILLA_LEXER_ASYMPTOTE_STYLE_DEFAULT 0
#define GTK_SCINTILLA_LEXER_ASYMPTOTE_STYLE_COMMENT 1
#define GTK_SCINTILLA_LEXER_ASYMPTOTE_STYLE_COMMENTLINE 2
#define GTK_SCINTILLA_LEXER_ASYMPTOTE_STYLE_NUMBER 3
#define GTK_SCINTILLA_LEXER_ASYMPTOTE_STYLE_WORD 4
#define GTK_SCINTILLA_LEXER_ASYMPTOTE_STYLE_STRING 5
#define GTK_SCINTILLA_LEXER_ASYMPTOTE_STYLE_CHARACTER 6
#define GTK_SCINTILLA_LEXER_ASYMPTOTE_STYLE_OPERATOR 7
#define GTK_SCINTILLA_LEXER_ASYMPTOTE_STYLE_IDENTIFIER 8
#define GTK_SCINTILLA_LEXER_ASYMPTOTE_STYLE_STRINGEOL 9
#define GTK_SCINTILLA_LEXER_ASYMPTOTE_STYLE_COMMENTLINEDOC 10
#define GTK_SCINTILLA_LEXER_ASYMPTOTE_STYLE_WORD2 11

		
G_END_DECLS

#endif /* ifndef GSCI_ASYMPTOTE_H */
