/* 
 *
 * This file is auto-generated, do not edit. 
 *
 * lexada.h - GScintilla Ada Lexer
 *
 */

#ifndef GSCI_LEXER_ADA_H
#define GSCI_LEXER_ADA_H

G_BEGIN_DECLS

/* Lexer states */
#define GTK_SCINTILLA_LEXER_ADA_STYLE_DEFAULT 0
#define GTK_SCINTILLA_LEXER_ADA_STYLE_WORD 1
#define GTK_SCINTILLA_LEXER_ADA_STYLE_IDENTIFIER 2
#define GTK_SCINTILLA_LEXER_ADA_STYLE_NUMBER 3
#define GTK_SCINTILLA_LEXER_ADA_STYLE_DELIMITER 4
#define GTK_SCINTILLA_LEXER_ADA_STYLE_CHARACTER 5
#define GTK_SCINTILLA_LEXER_ADA_STYLE_CHARACTEREOL 6
#define GTK_SCINTILLA_LEXER_ADA_STYLE_STRING 7
#define GTK_SCINTILLA_LEXER_ADA_STYLE_STRINGEOL 8
#define GTK_SCINTILLA_LEXER_ADA_STYLE_LABEL 9
#define GTK_SCINTILLA_LEXER_ADA_STYLE_COMMENTLINE 10
#define GTK_SCINTILLA_LEXER_ADA_STYLE_ILLEGAL 11

		
G_END_DECLS

#endif /* ifndef GSCI_ADA_H */
