/* 
 *
 * This file is auto-generated, do not edit. 
 *
 * lexabaqus.h - GScintilla ABAQUS Lexer
 *
 */

#ifndef GSCI_LEXER_ABAQUS_H
#define GSCI_LEXER_ABAQUS_H

G_BEGIN_DECLS

/* Lexer states */
#define GTK_SCINTILLA_LEXER_ABAQUS_STYLE_DEFAULT 0
#define GTK_SCINTILLA_LEXER_ABAQUS_STYLE_COMMENT 1
#define GTK_SCINTILLA_LEXER_ABAQUS_STYLE_COMMENTBLOCK 2
#define GTK_SCINTILLA_LEXER_ABAQUS_STYLE_NUMBER 3
#define GTK_SCINTILLA_LEXER_ABAQUS_STYLE_STRING 4
#define GTK_SCINTILLA_LEXER_ABAQUS_STYLE_OPERATOR 5
#define GTK_SCINTILLA_LEXER_ABAQUS_STYLE_WORD 6
#define GTK_SCINTILLA_LEXER_ABAQUS_STYLE_PROCESSOR 7
#define GTK_SCINTILLA_LEXER_ABAQUS_STYLE_COMMAND 8
#define GTK_SCINTILLA_LEXER_ABAQUS_STYLE_SLASHCOMMAND 9
#define GTK_SCINTILLA_LEXER_ABAQUS_STYLE_STARCOMMAND 10
#define GTK_SCINTILLA_LEXER_ABAQUS_STYLE_ARGUMENT 11
#define GTK_SCINTILLA_LEXER_ABAQUS_STYLE_FUNCTION 12

		
G_END_DECLS

#endif /* ifndef GSCI_ABAQUS_H */
