/* 
 *
 * This file is auto-generated, do not edit. 
 *
 * lexbatch.h - GScintilla Batch Lexer
 *
 */

#ifndef GSCI_LEXER_BATCH_H
#define GSCI_LEXER_BATCH_H

G_BEGIN_DECLS

/* Lexer states */
#define GTK_SCINTILLA_LEXER_BATCH_STYLE_DEFAULT 0
#define GTK_SCINTILLA_LEXER_BATCH_STYLE_COMMENT 1
#define GTK_SCINTILLA_LEXER_BATCH_STYLE_WORD 2
#define GTK_SCINTILLA_LEXER_BATCH_STYLE_LABEL 3
#define GTK_SCINTILLA_LEXER_BATCH_STYLE_HIDE 4
#define GTK_SCINTILLA_LEXER_BATCH_STYLE_COMMAND 5
#define GTK_SCINTILLA_LEXER_BATCH_STYLE_IDENTIFIER 6
#define GTK_SCINTILLA_LEXER_BATCH_STYLE_OPERATOR 7

		
G_END_DECLS

#endif /* ifndef GSCI_BATCH_H */
