/* 
 *
 * This file is auto-generated, do not edit. 
 *
 * lexbaan.h - GScintilla Baan Lexer
 *
 */

#ifndef GSCI_LEXER_BAAN_H
#define GSCI_LEXER_BAAN_H

G_BEGIN_DECLS

/* Lexer states */
#define GTK_SCINTILLA_LEXER_BAAN_STYLE_DEFAULT 0
#define GTK_SCINTILLA_LEXER_BAAN_STYLE_COMMENT 1
#define GTK_SCINTILLA_LEXER_BAAN_STYLE_COMMENTDOC 2
#define GTK_SCINTILLA_LEXER_BAAN_STYLE_NUMBER 3
#define GTK_SCINTILLA_LEXER_BAAN_STYLE_WORD 4
#define GTK_SCINTILLA_LEXER_BAAN_STYLE_STRING 5
#define GTK_SCINTILLA_LEXER_BAAN_STYLE_PREPROCESSOR 6
#define GTK_SCINTILLA_LEXER_BAAN_STYLE_OPERATOR 7
#define GTK_SCINTILLA_LEXER_BAAN_STYLE_IDENTIFIER 8
#define GTK_SCINTILLA_LEXER_BAAN_STYLE_STRINGEOL 9
#define GTK_SCINTILLA_LEXER_BAAN_STYLE_WORD2 10

		
G_END_DECLS

#endif /* ifndef GSCI_BAAN_H */
