/* 
 *
 * This file is auto-generated, do not edit. 
 *
 * lexbash.h - GScintilla Bash Lexer
 *
 */

#ifndef GSCI_LEXER_BASH_H
#define GSCI_LEXER_BASH_H

G_BEGIN_DECLS

/* Lexer states */
#define GTK_SCINTILLA_LEXER_BASH_STYLE_DEFAULT 0
#define GTK_SCINTILLA_LEXER_BASH_STYLE_ERROR 1
#define GTK_SCINTILLA_LEXER_BASH_STYLE_COMMENTLINE 2
#define GTK_SCINTILLA_LEXER_BASH_STYLE_NUMBER 3
#define GTK_SCINTILLA_LEXER_BASH_STYLE_WORD 4
#define GTK_SCINTILLA_LEXER_BASH_STYLE_STRING 5
#define GTK_SCINTILLA_LEXER_BASH_STYLE_CHARACTER 6
#define GTK_SCINTILLA_LEXER_BASH_STYLE_OPERATOR 7
#define GTK_SCINTILLA_LEXER_BASH_STYLE_IDENTIFIER 8
#define GTK_SCINTILLA_LEXER_BASH_STYLE_SCALAR 9
#define GTK_SCINTILLA_LEXER_BASH_STYLE_PARAM 10
#define GTK_SCINTILLA_LEXER_BASH_STYLE_BACKTICKS 11
#define GTK_SCINTILLA_LEXER_BASH_STYLE_HERE_DELIM 12
#define GTK_SCINTILLA_LEXER_BASH_STYLE_HERE_Q 13

		
G_END_DECLS

#endif /* ifndef GSCI_BASH_H */
