/* 
 *
 * This file is auto-generated, do not edit. 
 *
 * lexbullant.h - GScintilla BullAnt Lexer
 *
 */

#ifndef GSCI_LEXER_BULLANT_H
#define GSCI_LEXER_BULLANT_H

G_BEGIN_DECLS

/* Lexer states */
#define GTK_SCINTILLA_LEXER_BULLANT_STYLE_DEFAULT 0
#define GTK_SCINTILLA_LEXER_BULLANT_STYLE_COMMENT 1
#define GTK_SCINTILLA_LEXER_BULLANT_STYLE_COMMENTLINE 2
#define GTK_SCINTILLA_LEXER_BULLANT_STYLE_COMMENTDOC 3
#define GTK_SCINTILLA_LEXER_BULLANT_STYLE_NUMBER 4
#define GTK_SCINTILLA_LEXER_BULLANT_STYLE_WORD 5
#define GTK_SCINTILLA_LEXER_BULLANT_STYLE_STRING 6
#define GTK_SCINTILLA_LEXER_BULLANT_STYLE_CHARACTER 7
#define GTK_SCINTILLA_LEXER_BULLANT_STYLE_UUID 8
#define GTK_SCINTILLA_LEXER_BULLANT_STYLE_PREPROCESSOR 9
#define GTK_SCINTILLA_LEXER_BULLANT_STYLE_OPERATOR 10
#define GTK_SCINTILLA_LEXER_BULLANT_STYLE_IDENTIFIER 11
#define GTK_SCINTILLA_LEXER_BULLANT_STYLE_STRINGEOL 12
#define GTK_SCINTILLA_LEXER_BULLANT_STYLE_VERBATIM 13
#define GTK_SCINTILLA_LEXER_BULLANT_STYLE_REGEX 14
#define GTK_SCINTILLA_LEXER_BULLANT_STYLE_COMMENTLINEDOC 15
#define GTK_SCINTILLA_LEXER_BULLANT_STYLE_WORD2 16
#define GTK_SCINTILLA_LEXER_BULLANT_STYLE_COMMENTDOCKEYWORD 17
#define GTK_SCINTILLA_LEXER_BULLANT_STYLE_COMMENTDOCKEYWORDERROR 18
#define GTK_SCINTILLA_LEXER_BULLANT_STYLE_GLOBALCLASS 19

		
G_END_DECLS

#endif /* ifndef GSCI_BULLANT_H */
