/* 
 *
 * This file is auto-generated, do not edit. 
 *
 * lexcss.h - GScintilla CSS Lexer
 *
 */

#ifndef GSCI_LEXER_CSS_H
#define GSCI_LEXER_CSS_H

G_BEGIN_DECLS

/* Lexer states */
#define GTK_SCINTILLA_LEXER_CSS_STYLE_DEFAULT 0
#define GTK_SCINTILLA_LEXER_CSS_STYLE_TAG 1
#define GTK_SCINTILLA_LEXER_CSS_STYLE_CLASS 2
#define GTK_SCINTILLA_LEXER_CSS_STYLE_PSEUDOCLASS 3
#define GTK_SCINTILLA_LEXER_CSS_STYLE_UNKNOWN_PSEUDOCLASS 4
#define GTK_SCINTILLA_LEXER_CSS_STYLE_OPERATOR 5
#define GTK_SCINTILLA_LEXER_CSS_STYLE_IDENTIFIER 6
#define GTK_SCINTILLA_LEXER_CSS_STYLE_UNKNOWN_IDENTIFIER 7
#define GTK_SCINTILLA_LEXER_CSS_STYLE_VALUE 8
#define GTK_SCINTILLA_LEXER_CSS_STYLE_COMMENT 9
#define GTK_SCINTILLA_LEXER_CSS_STYLE_ID 10
#define GTK_SCINTILLA_LEXER_CSS_STYLE_IMPORTANT 11
#define GTK_SCINTILLA_LEXER_CSS_STYLE_DIRECTIVE 12
#define GTK_SCINTILLA_LEXER_CSS_STYLE_DOUBLESTRING 13
#define GTK_SCINTILLA_LEXER_CSS_STYLE_SINGLESTRING 14
#define GTK_SCINTILLA_LEXER_CSS_STYLE_IDENTIFIER2 15
#define GTK_SCINTILLA_LEXER_CSS_STYLE_ATTRIBUTE 16
#define GTK_SCINTILLA_LEXER_CSS_STYLE_IDENTIFIER3 17
#define GTK_SCINTILLA_LEXER_CSS_STYLE_PSEUDOELEMENT 18
#define GTK_SCINTILLA_LEXER_CSS_STYLE_EXTENDED_IDENTIFIER 19
#define GTK_SCINTILLA_LEXER_CSS_STYLE_EXTENDED_PSEUDOCLASS 20
#define GTK_SCINTILLA_LEXER_CSS_STYLE_EXTENDED_PSEUDOELEMENT 21
#define GTK_SCINTILLA_LEXER_CSS_STYLE_MEDIA 22

		
G_END_DECLS

#endif /* ifndef GSCI_CSS_H */
