/* 
 *
 * This file is auto-generated, do not edit. 
 *
 * lexcmake.h - GScintilla CMAKE Lexer
 *
 */

#ifndef GSCI_LEXER_CMAKE_H
#define GSCI_LEXER_CMAKE_H

G_BEGIN_DECLS

/* Lexer states */
#define GTK_SCINTILLA_LEXER_CMAKE_STYLE_DEFAULT 0
#define GTK_SCINTILLA_LEXER_CMAKE_STYLE_COMMENT 1
#define GTK_SCINTILLA_LEXER_CMAKE_STYLE_STRINGDQ 2
#define GTK_SCINTILLA_LEXER_CMAKE_STYLE_STRINGLQ 3
#define GTK_SCINTILLA_LEXER_CMAKE_STYLE_STRINGRQ 4
#define GTK_SCINTILLA_LEXER_CMAKE_STYLE_COMMANDS 5
#define GTK_SCINTILLA_LEXER_CMAKE_STYLE_PARAMETERS 6
#define GTK_SCINTILLA_LEXER_CMAKE_STYLE_VARIABLE 7
#define GTK_SCINTILLA_LEXER_CMAKE_STYLE_USERDEFINED 8
#define GTK_SCINTILLA_LEXER_CMAKE_STYLE_WHILEDEF 9
#define GTK_SCINTILLA_LEXER_CMAKE_STYLE_FOREACHDEF 10
#define GTK_SCINTILLA_LEXER_CMAKE_STYLE_IFDEFINEDEF 11
#define GTK_SCINTILLA_LEXER_CMAKE_STYLE_MACRODEF 12
#define GTK_SCINTILLA_LEXER_CMAKE_STYLE_STRINGVAR 13
#define GTK_SCINTILLA_LEXER_CMAKE_STYLE_NUMBER 14

		
G_END_DECLS

#endif /* ifndef GSCI_CMAKE_H */
