/* 
 *
 * This file is auto-generated, do not edit. 
 *
 * lexcpp.h - GScintilla Cpp Lexer
 *
 */

#ifndef GSCI_LEXER_CPP_H
#define GSCI_LEXER_CPP_H

G_BEGIN_DECLS

/* Lexer states */
#define GTK_SCINTILLA_LEXER_CPP_STYLE_DEFAULT 0
#define GTK_SCINTILLA_LEXER_CPP_STYLE_COMMENT 1
#define GTK_SCINTILLA_LEXER_CPP_STYLE_COMMENTLINE 2
#define GTK_SCINTILLA_LEXER_CPP_STYLE_COMMENTDOC 3
#define GTK_SCINTILLA_LEXER_CPP_STYLE_NUMBER 4
#define GTK_SCINTILLA_LEXER_CPP_STYLE_WORD 5
#define GTK_SCINTILLA_LEXER_CPP_STYLE_STRING 6
#define GTK_SCINTILLA_LEXER_CPP_STYLE_CHARACTER 7
#define GTK_SCINTILLA_LEXER_CPP_STYLE_UUID 8
#define GTK_SCINTILLA_LEXER_CPP_STYLE_PREPROCESSOR 9
#define GTK_SCINTILLA_LEXER_CPP_STYLE_OPERATOR 10
#define GTK_SCINTILLA_LEXER_CPP_STYLE_IDENTIFIER 11
#define GTK_SCINTILLA_LEXER_CPP_STYLE_STRINGEOL 12
#define GTK_SCINTILLA_LEXER_CPP_STYLE_VERBATIM 13
#define GTK_SCINTILLA_LEXER_CPP_STYLE_REGEX 14
#define GTK_SCINTILLA_LEXER_CPP_STYLE_COMMENTLINEDOC 15
#define GTK_SCINTILLA_LEXER_CPP_STYLE_WORD2 16
#define GTK_SCINTILLA_LEXER_CPP_STYLE_COMMENTDOCKEYWORD 17
#define GTK_SCINTILLA_LEXER_CPP_STYLE_COMMENTDOCKEYWORDERROR 18
#define GTK_SCINTILLA_LEXER_CPP_STYLE_GLOBALCLASS 19

		
G_END_DECLS

#endif /* ifndef GSCI_CPP_H */
