/* 
 *
 * This file is auto-generated, do not edit. 
 *
 * lexcsound.h - GScintilla Csound Lexer
 *
 */

#ifndef GSCI_LEXER_CSOUND_H
#define GSCI_LEXER_CSOUND_H

G_BEGIN_DECLS

/* Lexer states */
#define GTK_SCINTILLA_LEXER_CSOUND_STYLE_DEFAULT 0
#define GTK_SCINTILLA_LEXER_CSOUND_STYLE_COMMENT 1
#define GTK_SCINTILLA_LEXER_CSOUND_STYLE_NUMBER 2
#define GTK_SCINTILLA_LEXER_CSOUND_STYLE_OPERATOR 3
#define GTK_SCINTILLA_LEXER_CSOUND_STYLE_INSTR 4
#define GTK_SCINTILLA_LEXER_CSOUND_STYLE_IDENTIFIER 5
#define GTK_SCINTILLA_LEXER_CSOUND_STYLE_OPCODE 6
#define GTK_SCINTILLA_LEXER_CSOUND_STYLE_HEADERSTMT 7
#define GTK_SCINTILLA_LEXER_CSOUND_STYLE_USERKEYWORD 8
#define GTK_SCINTILLA_LEXER_CSOUND_STYLE_COMMENTBLOCK 9
#define GTK_SCINTILLA_LEXER_CSOUND_STYLE_PARAM 10
#define GTK_SCINTILLA_LEXER_CSOUND_STYLE_ARATE_VAR 11
#define GTK_SCINTILLA_LEXER_CSOUND_STYLE_KRATE_VAR 12
#define GTK_SCINTILLA_LEXER_CSOUND_STYLE_IRATE_VAR 13
#define GTK_SCINTILLA_LEXER_CSOUND_STYLE_GLOBAL_VAR 14
#define GTK_SCINTILLA_LEXER_CSOUND_STYLE_STRINGEOL 15

		
G_END_DECLS

#endif /* ifndef GSCI_CSOUND_H */
