/* 
 *
 * This file is auto-generated, do not edit. 
 *
 * lexconf.h - GScintilla Conf Lexer
 *
 */

#ifndef GSCI_LEXER_CONF_H
#define GSCI_LEXER_CONF_H

G_BEGIN_DECLS

/* Lexer states */
#define GTK_SCINTILLA_LEXER_CONF_STYLE_DEFAULT 0
#define GTK_SCINTILLA_LEXER_CONF_STYLE_COMMENT 1
#define GTK_SCINTILLA_LEXER_CONF_STYLE_NUMBER 2
#define GTK_SCINTILLA_LEXER_CONF_STYLE_IDENTIFIER 3
#define GTK_SCINTILLA_LEXER_CONF_STYLE_EXTENSION 4
#define GTK_SCINTILLA_LEXER_CONF_STYLE_PARAMETER 5
#define GTK_SCINTILLA_LEXER_CONF_STYLE_STRING 6
#define GTK_SCINTILLA_LEXER_CONF_STYLE_OPERATOR 7
#define GTK_SCINTILLA_LEXER_CONF_STYLE_IP 8
#define GTK_SCINTILLA_LEXER_CONF_STYLE_DIRECTIVE 9

		
G_END_DECLS

#endif /* ifndef GSCI_CONF_H */
