/* 
 *
 * This file is auto-generated, do not edit. 
 *
 * lexclw.h - GScintilla Clarion Lexer
 *
 */

#ifndef GSCI_LEXER_CLW_H
#define GSCI_LEXER_CLW_H

G_BEGIN_DECLS

/* Lexer states */
#define GTK_SCINTILLA_LEXER_CLW_STYLE_DEFAULT 0
#define GTK_SCINTILLA_LEXER_CLW_STYLE_LABEL 1
#define GTK_SCINTILLA_LEXER_CLW_STYLE_COMMENT 2
#define GTK_SCINTILLA_LEXER_CLW_STYLE_STRING 3
#define GTK_SCINTILLA_LEXER_CLW_STYLE_USER_IDENTIFIER 4
#define GTK_SCINTILLA_LEXER_CLW_STYLE_INTEGER_CONSTANT 5
#define GTK_SCINTILLA_LEXER_CLW_STYLE_REAL_CONSTANT 6
#define GTK_SCINTILLA_LEXER_CLW_STYLE_PICTURE_STRING 7
#define GTK_SCINTILLA_LEXER_CLW_STYLE_KEYWORD 8
#define GTK_SCINTILLA_LEXER_CLW_STYLE_COMPILER_DIRECTIVE 9
#define GTK_SCINTILLA_LEXER_CLW_STYLE_RUNTIME_EXPRESSIONS 10
#define GTK_SCINTILLA_LEXER_CLW_STYLE_BUILTIN_PROCEDURES_FUNCTION 11
#define GTK_SCINTILLA_LEXER_CLW_STYLE_STRUCTURE_DATA_TYPE 12
#define GTK_SCINTILLA_LEXER_CLW_STYLE_ATTRIBUTE 13
#define GTK_SCINTILLA_LEXER_CLW_STYLE_STANDARD_EQUATE 14
#define GTK_SCINTILLA_LEXER_CLW_STYLE_ERROR 15
#define GTK_SCINTILLA_LEXER_CLW_STYLE_DEPRECATED 16

		
G_END_DECLS

#endif /* ifndef GSCI_CLW_H */
