/* 
 *
 * This file is auto-generated, do not edit. 
 *
 * lexd.h - GScintilla D Lexer
 *
 */

#ifndef GSCI_LEXER_D_H
#define GSCI_LEXER_D_H

G_BEGIN_DECLS

/* Lexer states */
#define GTK_SCINTILLA_LEXER_D_STYLE_DEFAULT 0
#define GTK_SCINTILLA_LEXER_D_STYLE_COMMENT 1
#define GTK_SCINTILLA_LEXER_D_STYLE_COMMENTLINE 2
#define GTK_SCINTILLA_LEXER_D_STYLE_COMMENTDOC 3
#define GTK_SCINTILLA_LEXER_D_STYLE_COMMENTNESTED 4
#define GTK_SCINTILLA_LEXER_D_STYLE_NUMBER 5
#define GTK_SCINTILLA_LEXER_D_STYLE_WORD 6
#define GTK_SCINTILLA_LEXER_D_STYLE_WORD2 7
#define GTK_SCINTILLA_LEXER_D_STYLE_WORD3 8
#define GTK_SCINTILLA_LEXER_D_STYLE_TYPEDEF 9
#define GTK_SCINTILLA_LEXER_D_STYLE_STRING 10
#define GTK_SCINTILLA_LEXER_D_STYLE_STRINGEOL 11
#define GTK_SCINTILLA_LEXER_D_STYLE_CHARACTER 12
#define GTK_SCINTILLA_LEXER_D_STYLE_OPERATOR 13
#define GTK_SCINTILLA_LEXER_D_STYLE_IDENTIFIER 14
#define GTK_SCINTILLA_LEXER_D_STYLE_COMMENTLINEDOC 15
#define GTK_SCINTILLA_LEXER_D_STYLE_COMMENTDOCKEYWORD 16
#define GTK_SCINTILLA_LEXER_D_STYLE_COMMENTDOCKEYWORDERROR 17
#define GTK_SCINTILLA_LEXER_D_STYLE_STRINGB 18
#define GTK_SCINTILLA_LEXER_D_STYLE_STRINGR 19
#define GTK_SCINTILLA_LEXER_D_STYLE_WORD5 20
#define GTK_SCINTILLA_LEXER_D_STYLE_WORD6 21
#define GTK_SCINTILLA_LEXER_D_STYLE_WORD7 22

		
G_END_DECLS

#endif /* ifndef GSCI_D_H */
