/* 
 *
 * This file is auto-generated, do not edit. 
 *
 * lexdiff.h - GScintilla Diff Lexer
 *
 */

#ifndef GSCI_LEXER_DIFF_H
#define GSCI_LEXER_DIFF_H

G_BEGIN_DECLS

/* Lexer states */
#define GTK_SCINTILLA_LEXER_DIFF_STYLE_DEFAULT 0
#define GTK_SCINTILLA_LEXER_DIFF_STYLE_COMMENT 1
#define GTK_SCINTILLA_LEXER_DIFF_STYLE_COMMAND 2
#define GTK_SCINTILLA_LEXER_DIFF_STYLE_HEADER 3
#define GTK_SCINTILLA_LEXER_DIFF_STYLE_POSITION 4
#define GTK_SCINTILLA_LEXER_DIFF_STYLE_DELETED 5
#define GTK_SCINTILLA_LEXER_DIFF_STYLE_ADDED 6
#define GTK_SCINTILLA_LEXER_DIFF_STYLE_CHANGED 7

		
G_END_DECLS

#endif /* ifndef GSCI_DIFF_H */
