/* 
 *
 * This file is auto-generated, do not edit. 
 *
 * lexerrorlist.h - GScintilla ErrorList Lexer
 *
 */

#ifndef GSCI_LEXER_ERRORLIST_H
#define GSCI_LEXER_ERRORLIST_H

G_BEGIN_DECLS

/* Lexer states */
#define GTK_SCINTILLA_LEXER_ERRORLIST_STYLE_DEFAULT 0
#define GTK_SCINTILLA_LEXER_ERRORLIST_STYLE_PYTHON 1
#define GTK_SCINTILLA_LEXER_ERRORLIST_STYLE_GCC 2
#define GTK_SCINTILLA_LEXER_ERRORLIST_STYLE_MS 3
#define GTK_SCINTILLA_LEXER_ERRORLIST_STYLE_CMD 4
#define GTK_SCINTILLA_LEXER_ERRORLIST_STYLE_BORLAND 5
#define GTK_SCINTILLA_LEXER_ERRORLIST_STYLE_PERL 6
#define GTK_SCINTILLA_LEXER_ERRORLIST_STYLE_NET 7
#define GTK_SCINTILLA_LEXER_ERRORLIST_STYLE_LUA 8
#define GTK_SCINTILLA_LEXER_ERRORLIST_STYLE_CTAG 9
#define GTK_SCINTILLA_LEXER_ERRORLIST_STYLE_DIFF_CHANGED 10
#define GTK_SCINTILLA_LEXER_ERRORLIST_STYLE_DIFF_ADDITION 11
#define GTK_SCINTILLA_LEXER_ERRORLIST_STYLE_DIFF_DELETION 12
#define GTK_SCINTILLA_LEXER_ERRORLIST_STYLE_DIFF_MESSAGE 13
#define GTK_SCINTILLA_LEXER_ERRORLIST_STYLE_PHP 14
#define GTK_SCINTILLA_LEXER_ERRORLIST_STYLE_ELF 15
#define GTK_SCINTILLA_LEXER_ERRORLIST_STYLE_IFC 16
#define GTK_SCINTILLA_LEXER_ERRORLIST_STYLE_IFORT 17
#define GTK_SCINTILLA_LEXER_ERRORLIST_STYLE_ABSF 18
#define GTK_SCINTILLA_LEXER_ERRORLIST_STYLE_TIDY 19
#define GTK_SCINTILLA_LEXER_ERRORLIST_STYLE_JAVA_STACK 20
#define GTK_SCINTILLA_LEXER_ERRORLIST_STYLE_VALUE 21

		
G_END_DECLS

#endif /* ifndef GSCI_ERRORLIST_H */
