/* 
 *
 * This file is auto-generated, do not edit. 
 *
 * lexeiffel.h - GScintilla Eiffel Lexer
 *
 */

#ifndef GSCI_LEXER_EIFFEL_H
#define GSCI_LEXER_EIFFEL_H

G_BEGIN_DECLS

/* Lexer states */
#define GTK_SCINTILLA_LEXER_EIFFEL_STYLE_DEFAULT 0
#define GTK_SCINTILLA_LEXER_EIFFEL_STYLE_COMMENTLINE 1
#define GTK_SCINTILLA_LEXER_EIFFEL_STYLE_NUMBER 2
#define GTK_SCINTILLA_LEXER_EIFFEL_STYLE_WORD 3
#define GTK_SCINTILLA_LEXER_EIFFEL_STYLE_STRING 4
#define GTK_SCINTILLA_LEXER_EIFFEL_STYLE_CHARACTER 5
#define GTK_SCINTILLA_LEXER_EIFFEL_STYLE_OPERATOR 6
#define GTK_SCINTILLA_LEXER_EIFFEL_STYLE_IDENTIFIER 7
#define GTK_SCINTILLA_LEXER_EIFFEL_STYLE_STRINGEOL 8

		
G_END_DECLS

#endif /* ifndef GSCI_EIFFEL_H */
