/* 
 *
 * This file is auto-generated, do not edit. 
 *
 * lexescript.h - GScintilla ESCRIPT Lexer
 *
 */

#ifndef GSCI_LEXER_ESCRIPT_H
#define GSCI_LEXER_ESCRIPT_H

G_BEGIN_DECLS

/* Lexer states */
#define GTK_SCINTILLA_LEXER_ESCRIPT_STYLE_DEFAULT 0
#define GTK_SCINTILLA_LEXER_ESCRIPT_STYLE_COMMENT 1
#define GTK_SCINTILLA_LEXER_ESCRIPT_STYLE_COMMENTLINE 2
#define GTK_SCINTILLA_LEXER_ESCRIPT_STYLE_COMMENTDOC 3
#define GTK_SCINTILLA_LEXER_ESCRIPT_STYLE_NUMBER 4
#define GTK_SCINTILLA_LEXER_ESCRIPT_STYLE_WORD 5
#define GTK_SCINTILLA_LEXER_ESCRIPT_STYLE_STRING 6
#define GTK_SCINTILLA_LEXER_ESCRIPT_STYLE_OPERATOR 7
#define GTK_SCINTILLA_LEXER_ESCRIPT_STYLE_IDENTIFIER 8
#define GTK_SCINTILLA_LEXER_ESCRIPT_STYLE_BRACE 9
#define GTK_SCINTILLA_LEXER_ESCRIPT_STYLE_WORD2 10
#define GTK_SCINTILLA_LEXER_ESCRIPT_STYLE_WORD3 11

		
G_END_DECLS

#endif /* ifndef GSCI_ESCRIPT_H */
