/* 
 *
 * This file is auto-generated, do not edit. 
 *
 * lexeiffelkw.h - GScintilla EiffelKW Lexer
 *
 */

#ifndef GSCI_LEXER_EIFFELKW_H
#define GSCI_LEXER_EIFFELKW_H

G_BEGIN_DECLS

/* Lexer states */
#define GTK_SCINTILLA_LEXER_EIFFELKW_STYLE_DEFAULT 0
#define GTK_SCINTILLA_LEXER_EIFFELKW_STYLE_COMMENTLINE 1
#define GTK_SCINTILLA_LEXER_EIFFELKW_STYLE_NUMBER 2
#define GTK_SCINTILLA_LEXER_EIFFELKW_STYLE_WORD 3
#define GTK_SCINTILLA_LEXER_EIFFELKW_STYLE_STRING 4
#define GTK_SCINTILLA_LEXER_EIFFELKW_STYLE_CHARACTER 5
#define GTK_SCINTILLA_LEXER_EIFFELKW_STYLE_OPERATOR 6
#define GTK_SCINTILLA_LEXER_EIFFELKW_STYLE_IDENTIFIER 7
#define GTK_SCINTILLA_LEXER_EIFFELKW_STYLE_STRINGEOL 8

		
G_END_DECLS

#endif /* ifndef GSCI_EIFFELKW_H */
