/* 
 *
 * This file is auto-generated, do not edit. 
 *
 * lexerlang.h - GScintilla Erlang Lexer
 *
 */

#ifndef GSCI_LEXER_ERLANG_H
#define GSCI_LEXER_ERLANG_H

G_BEGIN_DECLS

/* Lexer states */
#define GTK_SCINTILLA_LEXER_ERLANG_STYLE_DEFAULT 0
#define GTK_SCINTILLA_LEXER_ERLANG_STYLE_COMMENT 1
#define GTK_SCINTILLA_LEXER_ERLANG_STYLE_VARIABLE 2
#define GTK_SCINTILLA_LEXER_ERLANG_STYLE_NUMBER 3
#define GTK_SCINTILLA_LEXER_ERLANG_STYLE_KEYWORD 4
#define GTK_SCINTILLA_LEXER_ERLANG_STYLE_STRING 5
#define GTK_SCINTILLA_LEXER_ERLANG_STYLE_OPERATOR 6
#define GTK_SCINTILLA_LEXER_ERLANG_STYLE_ATOM 7
#define GTK_SCINTILLA_LEXER_ERLANG_STYLE_FUNCTION_NAME 8
#define GTK_SCINTILLA_LEXER_ERLANG_STYLE_CHARACTER 9
#define GTK_SCINTILLA_LEXER_ERLANG_STYLE_MACRO 10
#define GTK_SCINTILLA_LEXER_ERLANG_STYLE_RECORD 11
#define GTK_SCINTILLA_LEXER_ERLANG_STYLE_PREPROC 12
#define GTK_SCINTILLA_LEXER_ERLANG_STYLE_NODE_NAME 13
#define GTK_SCINTILLA_LEXER_ERLANG_STYLE_COMMENT_FUNCTION 14
#define GTK_SCINTILLA_LEXER_ERLANG_STYLE_COMMENT_MODULE 15
#define GTK_SCINTILLA_LEXER_ERLANG_STYLE_COMMENT_DOC 16
#define GTK_SCINTILLA_LEXER_ERLANG_STYLE_COMMENT_DOC_MACRO 17
#define GTK_SCINTILLA_LEXER_ERLANG_STYLE_ATOM_QUOTED 18
#define GTK_SCINTILLA_LEXER_ERLANG_STYLE_MACRO_QUOTED 19
#define GTK_SCINTILLA_LEXER_ERLANG_STYLE_RECORD_QUOTED 20
#define GTK_SCINTILLA_LEXER_ERLANG_STYLE_NODE_NAME_QUOTED 21
#define GTK_SCINTILLA_LEXER_ERLANG_STYLE_BIFS 22
#define GTK_SCINTILLA_LEXER_ERLANG_STYLE_MODULES 23
#define GTK_SCINTILLA_LEXER_ERLANG_STYLE_MODULES_ATT 24
#define GTK_SCINTILLA_LEXER_ERLANG_STYLE_UNKNOWN 31

		
G_END_DECLS

#endif /* ifndef GSCI_ERLANG_H */
