/* 
 *
 * This file is auto-generated, do not edit. 
 *
 * lexforth.h - GScintilla Forth Lexer
 *
 */

#ifndef GSCI_LEXER_FORTH_H
#define GSCI_LEXER_FORTH_H

G_BEGIN_DECLS

/* Lexer states */
#define GTK_SCINTILLA_LEXER_FORTH_STYLE_DEFAULT 0
#define GTK_SCINTILLA_LEXER_FORTH_STYLE_COMMENT 1
#define GTK_SCINTILLA_LEXER_FORTH_STYLE_COMMENT_ML 2
#define GTK_SCINTILLA_LEXER_FORTH_STYLE_IDENTIFIER 3
#define GTK_SCINTILLA_LEXER_FORTH_STYLE_CONTROL 4
#define GTK_SCINTILLA_LEXER_FORTH_STYLE_KEYWORD 5
#define GTK_SCINTILLA_LEXER_FORTH_STYLE_DEFWORD 6
#define GTK_SCINTILLA_LEXER_FORTH_STYLE_PREWORD1 7
#define GTK_SCINTILLA_LEXER_FORTH_STYLE_PREWORD2 8
#define GTK_SCINTILLA_LEXER_FORTH_STYLE_NUMBER 9
#define GTK_SCINTILLA_LEXER_FORTH_STYLE_STRING 10
#define GTK_SCINTILLA_LEXER_FORTH_STYLE_LOCALE 11

		
G_END_DECLS

#endif /* ifndef GSCI_FORTH_H */
