/* 
 *
 * This file is auto-generated, do not edit. 
 *
 * lexf77.h - GScintilla F77 Lexer
 *
 */

#ifndef GSCI_LEXER_F77_H
#define GSCI_LEXER_F77_H

G_BEGIN_DECLS

/* Lexer states */
#define GTK_SCINTILLA_LEXER_F77_STYLE_DEFAULT 0
#define GTK_SCINTILLA_LEXER_F77_STYLE_COMMENT 1
#define GTK_SCINTILLA_LEXER_F77_STYLE_NUMBER 2
#define GTK_SCINTILLA_LEXER_F77_STYLE_STRING1 3
#define GTK_SCINTILLA_LEXER_F77_STYLE_STRING2 4
#define GTK_SCINTILLA_LEXER_F77_STYLE_STRINGEOL 5
#define GTK_SCINTILLA_LEXER_F77_STYLE_OPERATOR 6
#define GTK_SCINTILLA_LEXER_F77_STYLE_IDENTIFIER 7
#define GTK_SCINTILLA_LEXER_F77_STYLE_WORD 8
#define GTK_SCINTILLA_LEXER_F77_STYLE_WORD2 9
#define GTK_SCINTILLA_LEXER_F77_STYLE_WORD3 10
#define GTK_SCINTILLA_LEXER_F77_STYLE_PREPROCESSOR 11
#define GTK_SCINTILLA_LEXER_F77_STYLE_OPERATOR2 12
#define GTK_SCINTILLA_LEXER_F77_STYLE_LABEL 13
#define GTK_SCINTILLA_LEXER_F77_STYLE_CONTINUATION 14

		
G_END_DECLS

#endif /* ifndef GSCI_F77_H */
