/* 
 *
 * This file is auto-generated, do not edit. 
 *
 * lexgap.h - GScintilla Gap Lexer
 *
 */

#ifndef GSCI_LEXER_GAP_H
#define GSCI_LEXER_GAP_H

G_BEGIN_DECLS

/* Lexer states */
#define GTK_SCINTILLA_LEXER_GAP_STYLE_DEFAULT 0
#define GTK_SCINTILLA_LEXER_GAP_STYLE_IDENTIFIER 1
#define GTK_SCINTILLA_LEXER_GAP_STYLE_KEYWORD 2
#define GTK_SCINTILLA_LEXER_GAP_STYLE_KEYWORD2 3
#define GTK_SCINTILLA_LEXER_GAP_STYLE_KEYWORD3 4
#define GTK_SCINTILLA_LEXER_GAP_STYLE_KEYWORD4 5
#define GTK_SCINTILLA_LEXER_GAP_STYLE_STRING 6
#define GTK_SCINTILLA_LEXER_GAP_STYLE_CHAR 7
#define GTK_SCINTILLA_LEXER_GAP_STYLE_OPERATOR 8
#define GTK_SCINTILLA_LEXER_GAP_STYLE_COMMENT 9
#define GTK_SCINTILLA_LEXER_GAP_STYLE_NUMBER 10
#define GTK_SCINTILLA_LEXER_GAP_STYLE_STRINGEOL 11

		
G_END_DECLS

#endif /* ifndef GSCI_GAP_H */
