/* 
 *
 * This file is auto-generated, do not edit. 
 *
 * lexgui4cli.h - GScintilla GUI4CLI Lexer
 *
 */

#ifndef GSCI_LEXER_GUI4CLI_H
#define GSCI_LEXER_GUI4CLI_H

G_BEGIN_DECLS

/* Lexer states */
#define GTK_SCINTILLA_LEXER_GUI4CLI_STYLE_DEFAULT 0
#define GTK_SCINTILLA_LEXER_GUI4CLI_STYLE_COMMENTLINE 1
#define GTK_SCINTILLA_LEXER_GUI4CLI_STYLE_COMMENTBLOCK 2
#define GTK_SCINTILLA_LEXER_GUI4CLI_STYLE_GLOBAL 3
#define GTK_SCINTILLA_LEXER_GUI4CLI_STYLE_EVENT 4
#define GTK_SCINTILLA_LEXER_GUI4CLI_STYLE_ATTRIBUTE 5
#define GTK_SCINTILLA_LEXER_GUI4CLI_STYLE_CONTROL 6
#define GTK_SCINTILLA_LEXER_GUI4CLI_STYLE_COMMAND 7
#define GTK_SCINTILLA_LEXER_GUI4CLI_STYLE_STRING 8
#define GTK_SCINTILLA_LEXER_GUI4CLI_STYLE_OPERATOR 9

		
G_END_DECLS

#endif /* ifndef GSCI_GUI4CLI_H */
