/* 
 *
 * This file is auto-generated, do not edit. 
 *
 * lexhaskell.h - GScintilla Haskell Lexer
 *
 */

#ifndef GSCI_LEXER_HASKELL_H
#define GSCI_LEXER_HASKELL_H

G_BEGIN_DECLS

/* Lexer states */
#define GTK_SCINTILLA_LEXER_HASKELL_STYLE_DEFAULT 0
#define GTK_SCINTILLA_LEXER_HASKELL_STYLE_IDENTIFIER 1
#define GTK_SCINTILLA_LEXER_HASKELL_STYLE_KEYWORD 2
#define GTK_SCINTILLA_LEXER_HASKELL_STYLE_NUMBER 3
#define GTK_SCINTILLA_LEXER_HASKELL_STYLE_STRING 4
#define GTK_SCINTILLA_LEXER_HASKELL_STYLE_CHARACTER 5
#define GTK_SCINTILLA_LEXER_HASKELL_STYLE_CLASS 6
#define GTK_SCINTILLA_LEXER_HASKELL_STYLE_MODULE 7
#define GTK_SCINTILLA_LEXER_HASKELL_STYLE_CAPITAL 8
#define GTK_SCINTILLA_LEXER_HASKELL_STYLE_DATA 9
#define GTK_SCINTILLA_LEXER_HASKELL_STYLE_IMPORT 10
#define GTK_SCINTILLA_LEXER_HASKELL_STYLE_OPERATOR 11
#define GTK_SCINTILLA_LEXER_HASKELL_STYLE_INSTANCE 12
#define GTK_SCINTILLA_LEXER_HASKELL_STYLE_COMMENTLINE 13
#define GTK_SCINTILLA_LEXER_HASKELL_STYLE_COMMENTBLOCK 14
#define GTK_SCINTILLA_LEXER_HASKELL_STYLE_COMMENTBLOCK2 15
#define GTK_SCINTILLA_LEXER_HASKELL_STYLE_COMMENTBLOCK3 16

		
G_END_DECLS

#endif /* ifndef GSCI_HASKELL_H */
