/* 
 *
 * This file is auto-generated, do not edit. 
 *
 * lexinnosetup.h - GScintilla Inno Lexer
 *
 */

#ifndef GSCI_LEXER_INNOSETUP_H
#define GSCI_LEXER_INNOSETUP_H

G_BEGIN_DECLS

/* Lexer states */
#define GTK_SCINTILLA_LEXER_INNOSETUP_STYLE_DEFAULT 0
#define GTK_SCINTILLA_LEXER_INNOSETUP_STYLE_COMMENT 1
#define GTK_SCINTILLA_LEXER_INNOSETUP_STYLE_KEYWORD 2
#define GTK_SCINTILLA_LEXER_INNOSETUP_STYLE_PARAMETER 3
#define GTK_SCINTILLA_LEXER_INNOSETUP_STYLE_SECTION 4
#define GTK_SCINTILLA_LEXER_INNOSETUP_STYLE_PREPROC 5
#define GTK_SCINTILLA_LEXER_INNOSETUP_STYLE_INLINE_EXPANSION 6
#define GTK_SCINTILLA_LEXER_INNOSETUP_STYLE_COMMENT_PASCAL 7
#define GTK_SCINTILLA_LEXER_INNOSETUP_STYLE_KEYWORD_PASCAL 8
#define GTK_SCINTILLA_LEXER_INNOSETUP_STYLE_KEYWORD_USER 9
#define GTK_SCINTILLA_LEXER_INNOSETUP_STYLE_STRING_DOUBLE 10
#define GTK_SCINTILLA_LEXER_INNOSETUP_STYLE_STRING_SINGLE 11
#define GTK_SCINTILLA_LEXER_INNOSETUP_STYLE_IDENTIFIER 12

		
G_END_DECLS

#endif /* ifndef GSCI_INNOSETUP_H */
