/* 
 *
 * This file is auto-generated, do not edit. 
 *
 * lexkix.h - GScintilla Kix Lexer
 *
 */

#ifndef GSCI_LEXER_KIX_H
#define GSCI_LEXER_KIX_H

G_BEGIN_DECLS

/* Lexer states */
#define GTK_SCINTILLA_LEXER_KIX_STYLE_DEFAULT 0
#define GTK_SCINTILLA_LEXER_KIX_STYLE_COMMENT 1
#define GTK_SCINTILLA_LEXER_KIX_STYLE_STRING1 2
#define GTK_SCINTILLA_LEXER_KIX_STYLE_STRING2 3
#define GTK_SCINTILLA_LEXER_KIX_STYLE_NUMBER 4
#define GTK_SCINTILLA_LEXER_KIX_STYLE_VAR 5
#define GTK_SCINTILLA_LEXER_KIX_STYLE_MACRO 6
#define GTK_SCINTILLA_LEXER_KIX_STYLE_KEYWORD 7
#define GTK_SCINTILLA_LEXER_KIX_STYLE_FUNCTIONS 8
#define GTK_SCINTILLA_LEXER_KIX_STYLE_OPERATOR 9
#define GTK_SCINTILLA_LEXER_KIX_STYLE_IDENTIFIER 31

		
G_END_DECLS

#endif /* ifndef GSCI_KIX_H */
