/* 
 *
 * This file is auto-generated, do not edit. 
 *
 * lexlua.h - GScintilla Lua Lexer
 *
 */

#ifndef GSCI_LEXER_LUA_H
#define GSCI_LEXER_LUA_H

G_BEGIN_DECLS

/* Lexer states */
#define GTK_SCINTILLA_LEXER_LUA_STYLE_DEFAULT 0
#define GTK_SCINTILLA_LEXER_LUA_STYLE_COMMENT 1
#define GTK_SCINTILLA_LEXER_LUA_STYLE_COMMENTLINE 2
#define GTK_SCINTILLA_LEXER_LUA_STYLE_COMMENTDOC 3
#define GTK_SCINTILLA_LEXER_LUA_STYLE_NUMBER 4
#define GTK_SCINTILLA_LEXER_LUA_STYLE_WORD 5
#define GTK_SCINTILLA_LEXER_LUA_STYLE_STRING 6
#define GTK_SCINTILLA_LEXER_LUA_STYLE_CHARACTER 7
#define GTK_SCINTILLA_LEXER_LUA_STYLE_LITERALSTRING 8
#define GTK_SCINTILLA_LEXER_LUA_STYLE_PREPROCESSOR 9
#define GTK_SCINTILLA_LEXER_LUA_STYLE_OPERATOR 10
#define GTK_SCINTILLA_LEXER_LUA_STYLE_IDENTIFIER 11
#define GTK_SCINTILLA_LEXER_LUA_STYLE_STRINGEOL 12
#define GTK_SCINTILLA_LEXER_LUA_STYLE_WORD2 13
#define GTK_SCINTILLA_LEXER_LUA_STYLE_WORD3 14
#define GTK_SCINTILLA_LEXER_LUA_STYLE_WORD4 15
#define GTK_SCINTILLA_LEXER_LUA_STYLE_WORD5 16
#define GTK_SCINTILLA_LEXER_LUA_STYLE_WORD6 17
#define GTK_SCINTILLA_LEXER_LUA_STYLE_WORD7 18
#define GTK_SCINTILLA_LEXER_LUA_STYLE_WORD8 19

		
G_END_DECLS

#endif /* ifndef GSCI_LUA_H */
