/* 
 *
 * This file is auto-generated, do not edit. 
 *
 * lexlout.h - GScintilla LOUT Lexer
 *
 */

#ifndef GSCI_LEXER_LOUT_H
#define GSCI_LEXER_LOUT_H

G_BEGIN_DECLS

/* Lexer states */
#define GTK_SCINTILLA_LEXER_LOUT_STYLE_DEFAULT 0
#define GTK_SCINTILLA_LEXER_LOUT_STYLE_COMMENT 1
#define GTK_SCINTILLA_LEXER_LOUT_STYLE_NUMBER 2
#define GTK_SCINTILLA_LEXER_LOUT_STYLE_WORD 3
#define GTK_SCINTILLA_LEXER_LOUT_STYLE_WORD2 4
#define GTK_SCINTILLA_LEXER_LOUT_STYLE_WORD3 5
#define GTK_SCINTILLA_LEXER_LOUT_STYLE_WORD4 6
#define GTK_SCINTILLA_LEXER_LOUT_STYLE_STRING 7
#define GTK_SCINTILLA_LEXER_LOUT_STYLE_OPERATOR 8
#define GTK_SCINTILLA_LEXER_LOUT_STYLE_IDENTIFIER 9
#define GTK_SCINTILLA_LEXER_LOUT_STYLE_STRINGEOL 10

		
G_END_DECLS

#endif /* ifndef GSCI_LOUT_H */
