/* 
 *
 * This file is auto-generated, do not edit. 
 *
 * lexlisp.h - GScintilla Lisp Lexer
 *
 */

#ifndef GSCI_LEXER_LISP_H
#define GSCI_LEXER_LISP_H

G_BEGIN_DECLS

/* Lexer states */
#define GTK_SCINTILLA_LEXER_LISP_STYLE_DEFAULT 0
#define GTK_SCINTILLA_LEXER_LISP_STYLE_COMMENT 1
#define GTK_SCINTILLA_LEXER_LISP_STYLE_NUMBER 2
#define GTK_SCINTILLA_LEXER_LISP_STYLE_KEYWORD 3
#define GTK_SCINTILLA_LEXER_LISP_STYLE_KEYWORD_KW 4
#define GTK_SCINTILLA_LEXER_LISP_STYLE_SYMBOL 5
#define GTK_SCINTILLA_LEXER_LISP_STYLE_STRING 6
#define GTK_SCINTILLA_LEXER_LISP_STYLE_STRINGEOL 8
#define GTK_SCINTILLA_LEXER_LISP_STYLE_IDENTIFIER 9
#define GTK_SCINTILLA_LEXER_LISP_STYLE_OPERATOR 10
#define GTK_SCINTILLA_LEXER_LISP_STYLE_SPECIAL 11
#define GTK_SCINTILLA_LEXER_LISP_STYLE_MULTI_COMMENT 12

		
G_END_DECLS

#endif /* ifndef GSCI_LISP_H */
