/* 
 *
 * This file is auto-generated, do not edit. 
 *
 * lexmmixal.h - GScintilla MMIXAL Lexer
 *
 */

#ifndef GSCI_LEXER_MMIXAL_H
#define GSCI_LEXER_MMIXAL_H

G_BEGIN_DECLS

/* Lexer states */
#define GTK_SCINTILLA_LEXER_MMIXAL_STYLE_LEADWS 0
#define GTK_SCINTILLA_LEXER_MMIXAL_STYLE_COMMENT 1
#define GTK_SCINTILLA_LEXER_MMIXAL_STYLE_LABEL 2
#define GTK_SCINTILLA_LEXER_MMIXAL_STYLE_OPCODE 3
#define GTK_SCINTILLA_LEXER_MMIXAL_STYLE_OPCODE_PRE 4
#define GTK_SCINTILLA_LEXER_MMIXAL_STYLE_OPCODE_VALID 5
#define GTK_SCINTILLA_LEXER_MMIXAL_STYLE_OPCODE_UNKNOWN 6
#define GTK_SCINTILLA_LEXER_MMIXAL_STYLE_OPCODE_POST 7
#define GTK_SCINTILLA_LEXER_MMIXAL_STYLE_OPERANDS 8
#define GTK_SCINTILLA_LEXER_MMIXAL_STYLE_NUMBER 9
#define GTK_SCINTILLA_LEXER_MMIXAL_STYLE_REF 10
#define GTK_SCINTILLA_LEXER_MMIXAL_STYLE_CHAR 11
#define GTK_SCINTILLA_LEXER_MMIXAL_STYLE_STRING 12
#define GTK_SCINTILLA_LEXER_MMIXAL_STYLE_REGISTER 13
#define GTK_SCINTILLA_LEXER_MMIXAL_STYLE_HEX 14
#define GTK_SCINTILLA_LEXER_MMIXAL_STYLE_OPERATOR 15
#define GTK_SCINTILLA_LEXER_MMIXAL_STYLE_SYMBOL 16
#define GTK_SCINTILLA_LEXER_MMIXAL_STYLE_INCLUDE 17

		
G_END_DECLS

#endif /* ifndef GSCI_MMIXAL_H */
