/* 
 *
 * This file is auto-generated, do not edit. 
 *
 * lexmakefile.h - GScintilla MakeFile Lexer
 *
 */

#ifndef GSCI_LEXER_MAKEFILE_H
#define GSCI_LEXER_MAKEFILE_H

G_BEGIN_DECLS

/* Lexer states */
#define GTK_SCINTILLA_LEXER_MAKEFILE_STYLE_DEFAULT 0
#define GTK_SCINTILLA_LEXER_MAKEFILE_STYLE_COMMENT 1
#define GTK_SCINTILLA_LEXER_MAKEFILE_STYLE_PREPROCESSOR 2
#define GTK_SCINTILLA_LEXER_MAKEFILE_STYLE_IDENTIFIER 3
#define GTK_SCINTILLA_LEXER_MAKEFILE_STYLE_OPERATOR 4
#define GTK_SCINTILLA_LEXER_MAKEFILE_STYLE_TARGET 5
#define GTK_SCINTILLA_LEXER_MAKEFILE_STYLE_IDEOL 9

		
G_END_DECLS

#endif /* ifndef GSCI_MAKEFILE_H */
