/* 
 *
 * This file is auto-generated, do not edit. 
 *
 * lexmetapost.h - GScintilla Metapost Lexer
 *
 */

#ifndef GSCI_LEXER_METAPOST_H
#define GSCI_LEXER_METAPOST_H

G_BEGIN_DECLS

/* Lexer states */
#define GTK_SCINTILLA_LEXER_METAPOST_STYLE_DEFAULT 0
#define GTK_SCINTILLA_LEXER_METAPOST_STYLE_SPECIAL 1
#define GTK_SCINTILLA_LEXER_METAPOST_STYLE_GROUP 2
#define GTK_SCINTILLA_LEXER_METAPOST_STYLE_SYMBOL 3
#define GTK_SCINTILLA_LEXER_METAPOST_STYLE_COMMAND 4
#define GTK_SCINTILLA_LEXER_METAPOST_STYLE_TEXT 5
#define GTK_SCINTILLA_LEXER_METAPOST_STYLE_EXTRA 6

		
G_END_DECLS

#endif /* ifndef GSCI_METAPOST_H */
