/* 
 *
 * This file is auto-generated, do not edit. 
 *
 * lexmatlab.h - GScintilla MatLab Lexer
 *
 */

#ifndef GSCI_LEXER_MATLAB_H
#define GSCI_LEXER_MATLAB_H

G_BEGIN_DECLS

/* Lexer states */
#define GTK_SCINTILLA_LEXER_MATLAB_STYLE_DEFAULT 0
#define GTK_SCINTILLA_LEXER_MATLAB_STYLE_COMMENT 1
#define GTK_SCINTILLA_LEXER_MATLAB_STYLE_COMMAND 2
#define GTK_SCINTILLA_LEXER_MATLAB_STYLE_NUMBER 3
#define GTK_SCINTILLA_LEXER_MATLAB_STYLE_KEYWORD 4
#define GTK_SCINTILLA_LEXER_MATLAB_STYLE_STRING 5
#define GTK_SCINTILLA_LEXER_MATLAB_STYLE_OPERATOR 6
#define GTK_SCINTILLA_LEXER_MATLAB_STYLE_IDENTIFIER 7
#define GTK_SCINTILLA_LEXER_MATLAB_STYLE_DOUBLEQUOTESTRING 8

		
G_END_DECLS

#endif /* ifndef GSCI_MATLAB_H */
