/* 
 *
 * This file is auto-generated, do not edit. 
 *
 * lexmysql.h - GScintilla MySQL Lexer
 *
 */

#ifndef GSCI_LEXER_MYSQL_H
#define GSCI_LEXER_MYSQL_H

G_BEGIN_DECLS

/* Lexer states */
#define GTK_SCINTILLA_LEXER_MYSQL_STYLE_DEFAULT 0
#define GTK_SCINTILLA_LEXER_MYSQL_STYLE_COMMENT 1
#define GTK_SCINTILLA_LEXER_MYSQL_STYLE_COMMENTLINE 2
#define GTK_SCINTILLA_LEXER_MYSQL_STYLE_VARIABLE 3
#define GTK_SCINTILLA_LEXER_MYSQL_STYLE_SYSTEMVARIABLE 4
#define GTK_SCINTILLA_LEXER_MYSQL_STYLE_KNOWNSYSTEMVARIABLE 5
#define GTK_SCINTILLA_LEXER_MYSQL_STYLE_NUMBER 6
#define GTK_SCINTILLA_LEXER_MYSQL_STYLE_MAJORKEYWORD 7
#define GTK_SCINTILLA_LEXER_MYSQL_STYLE_KEYWORD 8
#define GTK_SCINTILLA_LEXER_MYSQL_STYLE_DATABASEOBJECT 9
#define GTK_SCINTILLA_LEXER_MYSQL_STYLE_PROCEDUREKEYWORD 10
#define GTK_SCINTILLA_LEXER_MYSQL_STYLE_STRING 11
#define GTK_SCINTILLA_LEXER_MYSQL_STYLE_SQSTRING 12
#define GTK_SCINTILLA_LEXER_MYSQL_STYLE_DQSTRING 13
#define GTK_SCINTILLA_LEXER_MYSQL_STYLE_OPERATOR 14
#define GTK_SCINTILLA_LEXER_MYSQL_STYLE_FUNCTION 15
#define GTK_SCINTILLA_LEXER_MYSQL_STYLE_IDENTIFIER 16
#define GTK_SCINTILLA_LEXER_MYSQL_STYLE_QUOTEDIDENTIFIER 17
#define GTK_SCINTILLA_LEXER_MYSQL_STYLE_USER1 18
#define GTK_SCINTILLA_LEXER_MYSQL_STYLE_USER2 19
#define GTK_SCINTILLA_LEXER_MYSQL_STYLE_USER3 20
#define GTK_SCINTILLA_LEXER_MYSQL_STYLE_HIDDENCOMMAND 21

		
G_END_DECLS

#endif /* ifndef GSCI_MYSQL_H */
