/* 
 *
 * This file is auto-generated, do not edit. 
 *
 * lexmssql.h - GScintilla MSSQL Lexer
 *
 */

#ifndef GSCI_LEXER_MSSQL_H
#define GSCI_LEXER_MSSQL_H

G_BEGIN_DECLS

/* Lexer states */
#define GTK_SCINTILLA_LEXER_MSSQL_STYLE_DEFAULT 0
#define GTK_SCINTILLA_LEXER_MSSQL_STYLE_COMMENT 1
#define GTK_SCINTILLA_LEXER_MSSQL_STYLE_LINE_COMMENT 2
#define GTK_SCINTILLA_LEXER_MSSQL_STYLE_NUMBER 3
#define GTK_SCINTILLA_LEXER_MSSQL_STYLE_STRING 4
#define GTK_SCINTILLA_LEXER_MSSQL_STYLE_OPERATOR 5
#define GTK_SCINTILLA_LEXER_MSSQL_STYLE_IDENTIFIER 6
#define GTK_SCINTILLA_LEXER_MSSQL_STYLE_VARIABLE 7
#define GTK_SCINTILLA_LEXER_MSSQL_STYLE_COLUMN_NAME 8
#define GTK_SCINTILLA_LEXER_MSSQL_STYLE_STATEMENT 9
#define GTK_SCINTILLA_LEXER_MSSQL_STYLE_DATATYPE 10
#define GTK_SCINTILLA_LEXER_MSSQL_STYLE_SYSTABLE 11
#define GTK_SCINTILLA_LEXER_MSSQL_STYLE_GLOBAL_VARIABLE 12
#define GTK_SCINTILLA_LEXER_MSSQL_STYLE_FUNCTION 13
#define GTK_SCINTILLA_LEXER_MSSQL_STYLE_STORED_PROCEDURE 14
#define GTK_SCINTILLA_LEXER_MSSQL_STYLE_DEFAULT_PREF_DATATYPE 15
#define GTK_SCINTILLA_LEXER_MSSQL_STYLE_COLUMN_NAME_2 16

		
G_END_DECLS

#endif /* ifndef GSCI_MSSQL_H */
