/* 
 *
 * This file is auto-generated, do not edit. 
 *
 * lexmarkdown.h - GScintilla Markdown Lexer
 *
 */

#ifndef GSCI_LEXER_MARKDOWN_H
#define GSCI_LEXER_MARKDOWN_H

G_BEGIN_DECLS

/* Lexer states */
#define GTK_SCINTILLA_LEXER_MARKDOWN_STYLE_DEFAULT 0
#define GTK_SCINTILLA_LEXER_MARKDOWN_STYLE_LINE_BEGIN 1
#define GTK_SCINTILLA_LEXER_MARKDOWN_STYLE_STRONG1 2
#define GTK_SCINTILLA_LEXER_MARKDOWN_STYLE_STRONG2 3
#define GTK_SCINTILLA_LEXER_MARKDOWN_STYLE_EM1 4
#define GTK_SCINTILLA_LEXER_MARKDOWN_STYLE_EM2 5
#define GTK_SCINTILLA_LEXER_MARKDOWN_STYLE_HEADER1 6
#define GTK_SCINTILLA_LEXER_MARKDOWN_STYLE_HEADER2 7
#define GTK_SCINTILLA_LEXER_MARKDOWN_STYLE_HEADER3 8
#define GTK_SCINTILLA_LEXER_MARKDOWN_STYLE_HEADER4 9
#define GTK_SCINTILLA_LEXER_MARKDOWN_STYLE_HEADER5 10
#define GTK_SCINTILLA_LEXER_MARKDOWN_STYLE_HEADER6 11
#define GTK_SCINTILLA_LEXER_MARKDOWN_STYLE_PRECHAR 12
#define GTK_SCINTILLA_LEXER_MARKDOWN_STYLE_ULIST_ITEM 13
#define GTK_SCINTILLA_LEXER_MARKDOWN_STYLE_OLIST_ITEM 14
#define GTK_SCINTILLA_LEXER_MARKDOWN_STYLE_BLOCKQUOTE 15
#define GTK_SCINTILLA_LEXER_MARKDOWN_STYLE_STRIKEOUT 16
#define GTK_SCINTILLA_LEXER_MARKDOWN_STYLE_HRULE 17
#define GTK_SCINTILLA_LEXER_MARKDOWN_STYLE_LINK 18
#define GTK_SCINTILLA_LEXER_MARKDOWN_STYLE_CODE 19
#define GTK_SCINTILLA_LEXER_MARKDOWN_STYLE_CODE2 20
#define GTK_SCINTILLA_LEXER_MARKDOWN_STYLE_CODEBK 21

		
G_END_DECLS

#endif /* ifndef GSCI_MARKDOWN_H */
