/* 
 *
 * This file is auto-generated, do not edit. 
 *
 * lexmagiksf.h - GScintilla MagikSF Lexer
 *
 */

#ifndef GSCI_LEXER_MAGIKSF_H
#define GSCI_LEXER_MAGIKSF_H

G_BEGIN_DECLS

/* Lexer states */
#define GTK_SCINTILLA_LEXER_MAGIKSF_STYLE_DEFAULT 0
#define GTK_SCINTILLA_LEXER_MAGIKSF_STYLE_COMMENT 1
#define GTK_SCINTILLA_LEXER_MAGIKSF_STYLE_HYPER_COMMENT 16
#define GTK_SCINTILLA_LEXER_MAGIKSF_STYLE_STRING 2
#define GTK_SCINTILLA_LEXER_MAGIKSF_STYLE_CHARACTER 3
#define GTK_SCINTILLA_LEXER_MAGIKSF_STYLE_NUMBER 4
#define GTK_SCINTILLA_LEXER_MAGIKSF_STYLE_IDENTIFIER 5
#define GTK_SCINTILLA_LEXER_MAGIKSF_STYLE_OPERATOR 6
#define GTK_SCINTILLA_LEXER_MAGIKSF_STYLE_FLOW 7
#define GTK_SCINTILLA_LEXER_MAGIKSF_STYLE_CONTAINER 8
#define GTK_SCINTILLA_LEXER_MAGIKSF_STYLE_BRACKET_BLOCK 9
#define GTK_SCINTILLA_LEXER_MAGIKSF_STYLE_BRACE_BLOCK 10
#define GTK_SCINTILLA_LEXER_MAGIKSF_STYLE_SQBRACKET_BLOCK 11
#define GTK_SCINTILLA_LEXER_MAGIKSF_STYLE_UNKNOWN_KEYWORD 12
#define GTK_SCINTILLA_LEXER_MAGIKSF_STYLE_KEYWORD 13
#define GTK_SCINTILLA_LEXER_MAGIKSF_STYLE_PRAGMA 14
#define GTK_SCINTILLA_LEXER_MAGIKSF_STYLE_SYMBOL 15

		
G_END_DECLS

#endif /* ifndef GSCI_MAGIKSF_H */
