/* 
 *
 * This file is auto-generated, do not edit. 
 *
 * lexnsis.h - GScintilla NSIS Lexer
 *
 */

#ifndef GSCI_LEXER_NSIS_H
#define GSCI_LEXER_NSIS_H

G_BEGIN_DECLS

/* Lexer states */
#define GTK_SCINTILLA_LEXER_NSIS_STYLE_DEFAULT 0
#define GTK_SCINTILLA_LEXER_NSIS_STYLE_COMMENT 1
#define GTK_SCINTILLA_LEXER_NSIS_STYLE_STRINGDQ 2
#define GTK_SCINTILLA_LEXER_NSIS_STYLE_STRINGLQ 3
#define GTK_SCINTILLA_LEXER_NSIS_STYLE_STRINGRQ 4
#define GTK_SCINTILLA_LEXER_NSIS_STYLE_FUNCTION 5
#define GTK_SCINTILLA_LEXER_NSIS_STYLE_VARIABLE 6
#define GTK_SCINTILLA_LEXER_NSIS_STYLE_LABEL 7
#define GTK_SCINTILLA_LEXER_NSIS_STYLE_USERDEFINED 8
#define GTK_SCINTILLA_LEXER_NSIS_STYLE_SECTIONDEF 9
#define GTK_SCINTILLA_LEXER_NSIS_STYLE_SUBSECTIONDEF 10
#define GTK_SCINTILLA_LEXER_NSIS_STYLE_IFDEFINEDEF 11
#define GTK_SCINTILLA_LEXER_NSIS_STYLE_MACRODEF 12
#define GTK_SCINTILLA_LEXER_NSIS_STYLE_STRINGVAR 13
#define GTK_SCINTILLA_LEXER_NSIS_STYLE_NUMBER 14
#define GTK_SCINTILLA_LEXER_NSIS_STYLE_SECTIONGROUP 15
#define GTK_SCINTILLA_LEXER_NSIS_STYLE_PAGEEX 16
#define GTK_SCINTILLA_LEXER_NSIS_STYLE_FUNCTIONDEF 17
#define GTK_SCINTILLA_LEXER_NSIS_STYLE_COMMENTBOX 18

		
G_END_DECLS

#endif /* ifndef GSCI_NSIS_H */
