/* 
 *
 * This file is auto-generated, do not edit. 
 *
 * lexnimrod.h - GScintilla Nimrod Lexer
 *
 */

#ifndef GSCI_LEXER_NIMROD_H
#define GSCI_LEXER_NIMROD_H

G_BEGIN_DECLS

/* Lexer states */
#define GTK_SCINTILLA_LEXER_NIMROD_STYLE_DEFAULT 0
#define GTK_SCINTILLA_LEXER_NIMROD_STYLE_COMMENTLINE 1
#define GTK_SCINTILLA_LEXER_NIMROD_STYLE_NUMBER 2
#define GTK_SCINTILLA_LEXER_NIMROD_STYLE_STRING 3
#define GTK_SCINTILLA_LEXER_NIMROD_STYLE_CHARACTER 4
#define GTK_SCINTILLA_LEXER_NIMROD_STYLE_WORD 5
#define GTK_SCINTILLA_LEXER_NIMROD_STYLE_TRIPLE 6
#define GTK_SCINTILLA_LEXER_NIMROD_STYLE_TRIPLEDOUBLE 7
#define GTK_SCINTILLA_LEXER_NIMROD_STYLE_CLASSNAME 8
#define GTK_SCINTILLA_LEXER_NIMROD_STYLE_DEFNAME 9
#define GTK_SCINTILLA_LEXER_NIMROD_STYLE_OPERATOR 10
#define GTK_SCINTILLA_LEXER_NIMROD_STYLE_IDENTIFIER 11
#define GTK_SCINTILLA_LEXER_NIMROD_STYLE_COMMENTBLOCK 12
#define GTK_SCINTILLA_LEXER_NIMROD_STYLE_STRINGEOL 13
#define GTK_SCINTILLA_LEXER_NIMROD_STYLE_WORD2 14
#define GTK_SCINTILLA_LEXER_NIMROD_STYLE_DECORATOR 15

		
G_END_DECLS

#endif /* ifndef GSCI_NIMROD_H */
