/* 
 *
 * This file is auto-generated, do not edit. 
 *
 * lexnncrontab.h - GScintilla NNCronTab Lexer
 *
 */

#ifndef GSCI_LEXER_NNCRONTAB_H
#define GSCI_LEXER_NNCRONTAB_H

G_BEGIN_DECLS

/* Lexer states */
#define GTK_SCINTILLA_LEXER_NNCRONTAB_STYLE_DEFAULT 0
#define GTK_SCINTILLA_LEXER_NNCRONTAB_STYLE_COMMENT 1
#define GTK_SCINTILLA_LEXER_NNCRONTAB_STYLE_TASK 2
#define GTK_SCINTILLA_LEXER_NNCRONTAB_STYLE_SECTION 3
#define GTK_SCINTILLA_LEXER_NNCRONTAB_STYLE_KEYWORD 4
#define GTK_SCINTILLA_LEXER_NNCRONTAB_STYLE_MODIFIER 5
#define GTK_SCINTILLA_LEXER_NNCRONTAB_STYLE_ASTERISK 6
#define GTK_SCINTILLA_LEXER_NNCRONTAB_STYLE_NUMBER 7
#define GTK_SCINTILLA_LEXER_NNCRONTAB_STYLE_STRING 8
#define GTK_SCINTILLA_LEXER_NNCRONTAB_STYLE_ENVIRONMENT 9
#define GTK_SCINTILLA_LEXER_NNCRONTAB_STYLE_IDENTIFIER 10

		
G_END_DECLS

#endif /* ifndef GSCI_NNCRONTAB_H */
