/* 
 *
 * This file is auto-generated, do not edit. 
 *
 * lexopal.h - GScintilla Opal Lexer
 *
 */

#ifndef GSCI_LEXER_OPAL_H
#define GSCI_LEXER_OPAL_H

G_BEGIN_DECLS

/* Lexer states */
#define GTK_SCINTILLA_LEXER_OPAL_STYLE_SPACE 0
#define GTK_SCINTILLA_LEXER_OPAL_STYLE_COMMENT_BLOCK 1
#define GTK_SCINTILLA_LEXER_OPAL_STYLE_COMMENT_LINE 2
#define GTK_SCINTILLA_LEXER_OPAL_STYLE_INTEGER 3
#define GTK_SCINTILLA_LEXER_OPAL_STYLE_KEYWORD 4
#define GTK_SCINTILLA_LEXER_OPAL_STYLE_SORT 5
#define GTK_SCINTILLA_LEXER_OPAL_STYLE_STRING 6
#define GTK_SCINTILLA_LEXER_OPAL_STYLE_PAR 7
#define GTK_SCINTILLA_LEXER_OPAL_STYLE_BOOL_CONST 8
#define GTK_SCINTILLA_LEXER_OPAL_STYLE_DEFAULT 32

		
G_END_DECLS

#endif /* ifndef GSCI_OPAL_H */
