/* 
 *
 * This file is auto-generated, do not edit. 
 *
 * lexpython.h - GScintilla Python Lexer
 *
 */

#ifndef GSCI_LEXER_PYTHON_H
#define GSCI_LEXER_PYTHON_H

G_BEGIN_DECLS

/* Lexer states */
#define GTK_SCINTILLA_LEXER_PYTHON_STYLE_DEFAULT 0
#define GTK_SCINTILLA_LEXER_PYTHON_STYLE_COMMENTLINE 1
#define GTK_SCINTILLA_LEXER_PYTHON_STYLE_NUMBER 2
#define GTK_SCINTILLA_LEXER_PYTHON_STYLE_STRING 3
#define GTK_SCINTILLA_LEXER_PYTHON_STYLE_CHARACTER 4
#define GTK_SCINTILLA_LEXER_PYTHON_STYLE_WORD 5
#define GTK_SCINTILLA_LEXER_PYTHON_STYLE_TRIPLE 6
#define GTK_SCINTILLA_LEXER_PYTHON_STYLE_TRIPLEDOUBLE 7
#define GTK_SCINTILLA_LEXER_PYTHON_STYLE_CLASSNAME 8
#define GTK_SCINTILLA_LEXER_PYTHON_STYLE_DEFNAME 9
#define GTK_SCINTILLA_LEXER_PYTHON_STYLE_OPERATOR 10
#define GTK_SCINTILLA_LEXER_PYTHON_STYLE_IDENTIFIER 11
#define GTK_SCINTILLA_LEXER_PYTHON_STYLE_COMMENTBLOCK 12
#define GTK_SCINTILLA_LEXER_PYTHON_STYLE_STRINGEOL 13
#define GTK_SCINTILLA_LEXER_PYTHON_STYLE_WORD2 14
#define GTK_SCINTILLA_LEXER_PYTHON_STYLE_DECORATOR 15

		
G_END_DECLS

#endif /* ifndef GSCI_PYTHON_H */
