/* 
 *
 * This file is auto-generated, do not edit. 
 *
 * lexpov.h - GScintilla POV Lexer
 *
 */

#ifndef GSCI_LEXER_POV_H
#define GSCI_LEXER_POV_H

G_BEGIN_DECLS

/* Lexer states */
#define GTK_SCINTILLA_LEXER_POV_STYLE_DEFAULT 0
#define GTK_SCINTILLA_LEXER_POV_STYLE_COMMENT 1
#define GTK_SCINTILLA_LEXER_POV_STYLE_COMMENTLINE 2
#define GTK_SCINTILLA_LEXER_POV_STYLE_NUMBER 3
#define GTK_SCINTILLA_LEXER_POV_STYLE_OPERATOR 4
#define GTK_SCINTILLA_LEXER_POV_STYLE_IDENTIFIER 5
#define GTK_SCINTILLA_LEXER_POV_STYLE_STRING 6
#define GTK_SCINTILLA_LEXER_POV_STYLE_STRINGEOL 7
#define GTK_SCINTILLA_LEXER_POV_STYLE_DIRECTIVE 8
#define GTK_SCINTILLA_LEXER_POV_STYLE_BADDIRECTIVE 9
#define GTK_SCINTILLA_LEXER_POV_STYLE_WORD2 10
#define GTK_SCINTILLA_LEXER_POV_STYLE_WORD3 11
#define GTK_SCINTILLA_LEXER_POV_STYLE_WORD4 12
#define GTK_SCINTILLA_LEXER_POV_STYLE_WORD5 13
#define GTK_SCINTILLA_LEXER_POV_STYLE_WORD6 14
#define GTK_SCINTILLA_LEXER_POV_STYLE_WORD7 15
#define GTK_SCINTILLA_LEXER_POV_STYLE_WORD8 16

		
G_END_DECLS

#endif /* ifndef GSCI_POV_H */
