/* 
 *
 * This file is auto-generated, do not edit. 
 *
 * lexplm.h - GScintilla PLM Lexer
 *
 */

#ifndef GSCI_LEXER_PLM_H
#define GSCI_LEXER_PLM_H

G_BEGIN_DECLS

/* Lexer states */
#define GTK_SCINTILLA_LEXER_PLM_STYLE_DEFAULT 0
#define GTK_SCINTILLA_LEXER_PLM_STYLE_COMMENT 1
#define GTK_SCINTILLA_LEXER_PLM_STYLE_STRING 2
#define GTK_SCINTILLA_LEXER_PLM_STYLE_NUMBER 3
#define GTK_SCINTILLA_LEXER_PLM_STYLE_IDENTIFIER 4
#define GTK_SCINTILLA_LEXER_PLM_STYLE_OPERATOR 5
#define GTK_SCINTILLA_LEXER_PLM_STYLE_CONTROL 6
#define GTK_SCINTILLA_LEXER_PLM_STYLE_KEYWORD 7

		
G_END_DECLS

#endif /* ifndef GSCI_PLM_H */
