/* 
 *
 * This file is auto-generated, do not edit. 
 *
 * lexpowerpro.h - GScintilla PowerPro Lexer
 *
 */

#ifndef GSCI_LEXER_POWERPRO_H
#define GSCI_LEXER_POWERPRO_H

G_BEGIN_DECLS

/* Lexer states */
#define GTK_SCINTILLA_LEXER_POWERPRO_STYLE_DEFAULT 0
#define GTK_SCINTILLA_LEXER_POWERPRO_STYLE_COMMENTBLOCK 1
#define GTK_SCINTILLA_LEXER_POWERPRO_STYLE_COMMENTLINE 2
#define GTK_SCINTILLA_LEXER_POWERPRO_STYLE_NUMBER 3
#define GTK_SCINTILLA_LEXER_POWERPRO_STYLE_WORD 4
#define GTK_SCINTILLA_LEXER_POWERPRO_STYLE_WORD2 5
#define GTK_SCINTILLA_LEXER_POWERPRO_STYLE_WORD3 6
#define GTK_SCINTILLA_LEXER_POWERPRO_STYLE_WORD4 7
#define GTK_SCINTILLA_LEXER_POWERPRO_STYLE_DOUBLEQUOTEDSTRING 8
#define GTK_SCINTILLA_LEXER_POWERPRO_STYLE_SINGLEQUOTEDSTRING 9
#define GTK_SCINTILLA_LEXER_POWERPRO_STYLE_LINECONTINUE 10
#define GTK_SCINTILLA_LEXER_POWERPRO_STYLE_OPERATOR 11
#define GTK_SCINTILLA_LEXER_POWERPRO_STYLE_IDENTIFIER 12
#define GTK_SCINTILLA_LEXER_POWERPRO_STYLE_STRINGEOL 13
#define GTK_SCINTILLA_LEXER_POWERPRO_STYLE_VERBATIM 14
#define GTK_SCINTILLA_LEXER_POWERPRO_STYLE_ALTQUOTE 15
#define GTK_SCINTILLA_LEXER_POWERPRO_STYLE_FUNCTION 16

		
G_END_DECLS

#endif /* ifndef GSCI_POWERPRO_H */
