/* 
 *
 * This file is auto-generated, do not edit. 
 *
 * lexps.h - GScintilla PS Lexer
 *
 */

#ifndef GSCI_LEXER_PS_H
#define GSCI_LEXER_PS_H

G_BEGIN_DECLS

/* Lexer states */
#define GTK_SCINTILLA_LEXER_PS_STYLE_DEFAULT 0
#define GTK_SCINTILLA_LEXER_PS_STYLE_COMMENT 1
#define GTK_SCINTILLA_LEXER_PS_STYLE_DSC_COMMENT 2
#define GTK_SCINTILLA_LEXER_PS_STYLE_DSC_VALUE 3
#define GTK_SCINTILLA_LEXER_PS_STYLE_NUMBER 4
#define GTK_SCINTILLA_LEXER_PS_STYLE_NAME 5
#define GTK_SCINTILLA_LEXER_PS_STYLE_KEYWORD 6
#define GTK_SCINTILLA_LEXER_PS_STYLE_LITERAL 7
#define GTK_SCINTILLA_LEXER_PS_STYLE_IMMEVAL 8
#define GTK_SCINTILLA_LEXER_PS_STYLE_PAREN_ARRAY 9
#define GTK_SCINTILLA_LEXER_PS_STYLE_PAREN_DICT 10
#define GTK_SCINTILLA_LEXER_PS_STYLE_PAREN_PROC 11
#define GTK_SCINTILLA_LEXER_PS_STYLE_TEXT 12
#define GTK_SCINTILLA_LEXER_PS_STYLE_HEXSTRING 13
#define GTK_SCINTILLA_LEXER_PS_STYLE_BASE85STRING 14
#define GTK_SCINTILLA_LEXER_PS_STYLE_BADSTRINGCHAR 15

		
G_END_DECLS

#endif /* ifndef GSCI_PS_H */
