/* 
 *
 * This file is auto-generated, do not edit. 
 *
 * lexpowerbasic.h - GScintilla PowerBasic Lexer
 *
 */

#ifndef GSCI_LEXER_POWERBASIC_H
#define GSCI_LEXER_POWERBASIC_H

G_BEGIN_DECLS

/* Lexer states */
#define GTK_SCINTILLA_LEXER_POWERBASIC_STYLE_DEFAULT 0
#define GTK_SCINTILLA_LEXER_POWERBASIC_STYLE_COMMENT 1
#define GTK_SCINTILLA_LEXER_POWERBASIC_STYLE_NUMBER 2
#define GTK_SCINTILLA_LEXER_POWERBASIC_STYLE_KEYWORD 3
#define GTK_SCINTILLA_LEXER_POWERBASIC_STYLE_STRING 4
#define GTK_SCINTILLA_LEXER_POWERBASIC_STYLE_PREPROCESSOR 5
#define GTK_SCINTILLA_LEXER_POWERBASIC_STYLE_OPERATOR 6
#define GTK_SCINTILLA_LEXER_POWERBASIC_STYLE_IDENTIFIER 7
#define GTK_SCINTILLA_LEXER_POWERBASIC_STYLE_DATE 8
#define GTK_SCINTILLA_LEXER_POWERBASIC_STYLE_STRINGEOL 9
#define GTK_SCINTILLA_LEXER_POWERBASIC_STYLE_KEYWORD2 10
#define GTK_SCINTILLA_LEXER_POWERBASIC_STYLE_KEYWORD3 11
#define GTK_SCINTILLA_LEXER_POWERBASIC_STYLE_KEYWORD4 12
#define GTK_SCINTILLA_LEXER_POWERBASIC_STYLE_CONSTANT 13
#define GTK_SCINTILLA_LEXER_POWERBASIC_STYLE_ASM 14
#define GTK_SCINTILLA_LEXER_POWERBASIC_STYLE_LABEL 15
#define GTK_SCINTILLA_LEXER_POWERBASIC_STYLE_ERROR 16
#define GTK_SCINTILLA_LEXER_POWERBASIC_STYLE_HEXNUMBER 17
#define GTK_SCINTILLA_LEXER_POWERBASIC_STYLE_BINNUMBER 18

		
G_END_DECLS

#endif /* ifndef GSCI_POWERBASIC_H */
