/* 
 *
 * This file is auto-generated, do not edit. 
 *
 * lexproperties.h - GScintilla Properties Lexer
 *
 */

#ifndef GSCI_LEXER_PROPERTIES_H
#define GSCI_LEXER_PROPERTIES_H

G_BEGIN_DECLS

/* Lexer states */
#define GTK_SCINTILLA_LEXER_PROPERTIES_STYLE_DEFAULT 0
#define GTK_SCINTILLA_LEXER_PROPERTIES_STYLE_COMMENT 1
#define GTK_SCINTILLA_LEXER_PROPERTIES_STYLE_SECTION 2
#define GTK_SCINTILLA_LEXER_PROPERTIES_STYLE_ASSIGNMENT 3
#define GTK_SCINTILLA_LEXER_PROPERTIES_STYLE_DEFVAL 4
#define GTK_SCINTILLA_LEXER_PROPERTIES_STYLE_KEY 5

		
G_END_DECLS

#endif /* ifndef GSCI_PROPERTIES_H */
