/* 
 *
 * This file is auto-generated, do not edit. 
 *
 * lexpowershell.h - GScintilla PowerShell Lexer
 *
 */

#ifndef GSCI_LEXER_POWERSHELL_H
#define GSCI_LEXER_POWERSHELL_H

G_BEGIN_DECLS

/* Lexer states */
#define GTK_SCINTILLA_LEXER_POWERSHELL_STYLE_DEFAULT 0
#define GTK_SCINTILLA_LEXER_POWERSHELL_STYLE_COMMENT 1
#define GTK_SCINTILLA_LEXER_POWERSHELL_STYLE_STRING 2
#define GTK_SCINTILLA_LEXER_POWERSHELL_STYLE_CHARACTER 3
#define GTK_SCINTILLA_LEXER_POWERSHELL_STYLE_NUMBER 4
#define GTK_SCINTILLA_LEXER_POWERSHELL_STYLE_VARIABLE 5
#define GTK_SCINTILLA_LEXER_POWERSHELL_STYLE_OPERATOR 6
#define GTK_SCINTILLA_LEXER_POWERSHELL_STYLE_IDENTIFIER 7
#define GTK_SCINTILLA_LEXER_POWERSHELL_STYLE_KEYWORD 8
#define GTK_SCINTILLA_LEXER_POWERSHELL_STYLE_CMDLET 9
#define GTK_SCINTILLA_LEXER_POWERSHELL_STYLE_ALIAS 10
#define GTK_SCINTILLA_LEXER_POWERSHELL_STYLE_FUNCTION 11
#define GTK_SCINTILLA_LEXER_POWERSHELL_STYLE_USER1 12
#define GTK_SCINTILLA_LEXER_POWERSHELL_STYLE_COMMENTSTREAM 13

		
G_END_DECLS

#endif /* ifndef GSCI_POWERSHELL_H */
