/* 
 *
 * This file is auto-generated, do not edit. 
 *
 * lexprogress.h - GScintilla Progress Lexer
 *
 */

#ifndef GSCI_LEXER_PROGRESS_H
#define GSCI_LEXER_PROGRESS_H

G_BEGIN_DECLS

/* Lexer states */
#define GTK_SCINTILLA_LEXER_PROGRESS_STYLE_DEFAULT 0
#define GTK_SCINTILLA_LEXER_PROGRESS_STYLE_NUMBER 1
#define GTK_SCINTILLA_LEXER_PROGRESS_STYLE_WORD 2
#define GTK_SCINTILLA_LEXER_PROGRESS_STYLE_STRING 3
#define GTK_SCINTILLA_LEXER_PROGRESS_STYLE_CHARACTER 4
#define GTK_SCINTILLA_LEXER_PROGRESS_STYLE_PREPROCESSOR 5
#define GTK_SCINTILLA_LEXER_PROGRESS_STYLE_OPERATOR 6
#define GTK_SCINTILLA_LEXER_PROGRESS_STYLE_IDENTIFIER 7
#define GTK_SCINTILLA_LEXER_PROGRESS_STYLE_BLOCK 8
#define GTK_SCINTILLA_LEXER_PROGRESS_STYLE_END 9
#define GTK_SCINTILLA_LEXER_PROGRESS_STYLE_COMMENT1 10
#define GTK_SCINTILLA_LEXER_PROGRESS_STYLE_COMMENT2 11
#define GTK_SCINTILLA_LEXER_PROGRESS_STYLE_COMMENT3 12
#define GTK_SCINTILLA_LEXER_PROGRESS_STYLE_COMMENT4 13
#define GTK_SCINTILLA_LEXER_PROGRESS_STYLE_COMMENT5 14
#define GTK_SCINTILLA_LEXER_PROGRESS_STYLE_COMMENT6 15

		
G_END_DECLS

#endif /* ifndef GSCI_PROGRESS_H */
