/* 
 *
 * This file is auto-generated, do not edit. 
 *
 * lexpascal.h - GScintilla Pascal Lexer
 *
 */

#ifndef GSCI_LEXER_PASCAL_H
#define GSCI_LEXER_PASCAL_H

G_BEGIN_DECLS

/* Lexer states */
#define GTK_SCINTILLA_LEXER_PASCAL_STYLE_DEFAULT 0
#define GTK_SCINTILLA_LEXER_PASCAL_STYLE_IDENTIFIER 1
#define GTK_SCINTILLA_LEXER_PASCAL_STYLE_COMMENT 2
#define GTK_SCINTILLA_LEXER_PASCAL_STYLE_COMMENT2 3
#define GTK_SCINTILLA_LEXER_PASCAL_STYLE_COMMENTLINE 4
#define GTK_SCINTILLA_LEXER_PASCAL_STYLE_PREPROCESSOR 5
#define GTK_SCINTILLA_LEXER_PASCAL_STYLE_PREPROCESSOR2 6
#define GTK_SCINTILLA_LEXER_PASCAL_STYLE_NUMBER 7
#define GTK_SCINTILLA_LEXER_PASCAL_STYLE_HEXNUMBER 8
#define GTK_SCINTILLA_LEXER_PASCAL_STYLE_WORD 9
#define GTK_SCINTILLA_LEXER_PASCAL_STYLE_STRING 10
#define GTK_SCINTILLA_LEXER_PASCAL_STYLE_STRINGEOL 11
#define GTK_SCINTILLA_LEXER_PASCAL_STYLE_CHARACTER 12
#define GTK_SCINTILLA_LEXER_PASCAL_STYLE_OPERATOR 13
#define GTK_SCINTILLA_LEXER_PASCAL_STYLE_ASM 14

		
G_END_DECLS

#endif /* ifndef GSCI_PASCAL_H */
