/* 
 *
 * This file is auto-generated, do not edit. 
 *
 * lexperl.h - GScintilla Perl Lexer
 *
 */

#ifndef GSCI_LEXER_PERL_H
#define GSCI_LEXER_PERL_H

G_BEGIN_DECLS

/* Lexer states */
#define GTK_SCINTILLA_LEXER_PERL_STYLE_DEFAULT 0
#define GTK_SCINTILLA_LEXER_PERL_STYLE_ERROR 1
#define GTK_SCINTILLA_LEXER_PERL_STYLE_COMMENTLINE 2
#define GTK_SCINTILLA_LEXER_PERL_STYLE_POD 3
#define GTK_SCINTILLA_LEXER_PERL_STYLE_NUMBER 4
#define GTK_SCINTILLA_LEXER_PERL_STYLE_WORD 5
#define GTK_SCINTILLA_LEXER_PERL_STYLE_STRING 6
#define GTK_SCINTILLA_LEXER_PERL_STYLE_CHARACTER 7
#define GTK_SCINTILLA_LEXER_PERL_STYLE_PUNCTUATION 8
#define GTK_SCINTILLA_LEXER_PERL_STYLE_PREPROCESSOR 9
#define GTK_SCINTILLA_LEXER_PERL_STYLE_OPERATOR 10
#define GTK_SCINTILLA_LEXER_PERL_STYLE_IDENTIFIER 11
#define GTK_SCINTILLA_LEXER_PERL_STYLE_SCALAR 12
#define GTK_SCINTILLA_LEXER_PERL_STYLE_ARRAY 13
#define GTK_SCINTILLA_LEXER_PERL_STYLE_HASH 14
#define GTK_SCINTILLA_LEXER_PERL_STYLE_SYMBOLTABLE 15
#define GTK_SCINTILLA_LEXER_PERL_STYLE_VARIABLE_INDEXER 16
#define GTK_SCINTILLA_LEXER_PERL_STYLE_REGEX 17
#define GTK_SCINTILLA_LEXER_PERL_STYLE_REGSUBST 18
#define GTK_SCINTILLA_LEXER_PERL_STYLE_LONGQUOTE 19
#define GTK_SCINTILLA_LEXER_PERL_STYLE_BACKTICKS 20
#define GTK_SCINTILLA_LEXER_PERL_STYLE_DATASECTION 21
#define GTK_SCINTILLA_LEXER_PERL_STYLE_HERE_DELIM 22
#define GTK_SCINTILLA_LEXER_PERL_STYLE_HERE_Q 23
#define GTK_SCINTILLA_LEXER_PERL_STYLE_HERE_QQ 24
#define GTK_SCINTILLA_LEXER_PERL_STYLE_HERE_QX 25
#define GTK_SCINTILLA_LEXER_PERL_STYLE_STRING_Q 26
#define GTK_SCINTILLA_LEXER_PERL_STYLE_STRING_QQ 27
#define GTK_SCINTILLA_LEXER_PERL_STYLE_STRING_QX 28
#define GTK_SCINTILLA_LEXER_PERL_STYLE_STRING_QR 29
#define GTK_SCINTILLA_LEXER_PERL_STYLE_STRING_QW 30
#define GTK_SCINTILLA_LEXER_PERL_STYLE_POD_VERB 31
#define GTK_SCINTILLA_LEXER_PERL_STYLE_SUB_PROTOTYPE 40
#define GTK_SCINTILLA_LEXER_PERL_STYLE_FORMAT_IDENT 41
#define GTK_SCINTILLA_LEXER_PERL_STYLE_FORMAT 42

		
G_END_DECLS

#endif /* ifndef GSCI_PERL_H */
