/* 
 *
 * This file is auto-generated, do not edit. 
 *
 * lexpo.h - GScintilla Po Lexer
 *
 */

#ifndef GSCI_LEXER_PO_H
#define GSCI_LEXER_PO_H

G_BEGIN_DECLS

/* Lexer states */
#define GTK_SCINTILLA_LEXER_PO_STYLE_DEFAULT 0
#define GTK_SCINTILLA_LEXER_PO_STYLE_COMMENT 1
#define GTK_SCINTILLA_LEXER_PO_STYLE_MSGID 2
#define GTK_SCINTILLA_LEXER_PO_STYLE_MSGID_TEXT 3
#define GTK_SCINTILLA_LEXER_PO_STYLE_MSGSTR 4
#define GTK_SCINTILLA_LEXER_PO_STYLE_MSGSTR_TEXT 5
#define GTK_SCINTILLA_LEXER_PO_STYLE_MSGCTXT 6
#define GTK_SCINTILLA_LEXER_PO_STYLE_MSGCTXT_TEXT 7
#define GTK_SCINTILLA_LEXER_PO_STYLE_FUZZY 8

		
G_END_DECLS

#endif /* ifndef GSCI_PO_H */
