/* 
 *
 * This file is auto-generated, do not edit. 
 *
 * lexr.h - GScintilla R Lexer
 *
 */

#ifndef GSCI_LEXER_R_H
#define GSCI_LEXER_R_H

G_BEGIN_DECLS

/* Lexer states */
#define GTK_SCINTILLA_LEXER_R_STYLE_DEFAULT 0
#define GTK_SCINTILLA_LEXER_R_STYLE_COMMENT 1
#define GTK_SCINTILLA_LEXER_R_STYLE_KWORD 2
#define GTK_SCINTILLA_LEXER_R_STYLE_BASEKWORD 3
#define GTK_SCINTILLA_LEXER_R_STYLE_OTHERKWORD 4
#define GTK_SCINTILLA_LEXER_R_STYLE_NUMBER 5
#define GTK_SCINTILLA_LEXER_R_STYLE_STRING 6
#define GTK_SCINTILLA_LEXER_R_STYLE_STRING2 7
#define GTK_SCINTILLA_LEXER_R_STYLE_OPERATOR 8
#define GTK_SCINTILLA_LEXER_R_STYLE_IDENTIFIER 9
#define GTK_SCINTILLA_LEXER_R_STYLE_INFIX 10
#define GTK_SCINTILLA_LEXER_R_STYLE_INFIXEOL 11

		
G_END_DECLS

#endif /* ifndef GSCI_R_H */
