/* 
 *
 * This file is auto-generated, do not edit. 
 *
 * lexruby.h - GScintilla Ruby Lexer
 *
 */

#ifndef GSCI_LEXER_RUBY_H
#define GSCI_LEXER_RUBY_H

G_BEGIN_DECLS

/* Lexer states */
#define GTK_SCINTILLA_LEXER_RUBY_STYLE_DEFAULT 0
#define GTK_SCINTILLA_LEXER_RUBY_STYLE_ERROR 1
#define GTK_SCINTILLA_LEXER_RUBY_STYLE_COMMENTLINE 2
#define GTK_SCINTILLA_LEXER_RUBY_STYLE_POD 3
#define GTK_SCINTILLA_LEXER_RUBY_STYLE_NUMBER 4
#define GTK_SCINTILLA_LEXER_RUBY_STYLE_WORD 5
#define GTK_SCINTILLA_LEXER_RUBY_STYLE_STRING 6
#define GTK_SCINTILLA_LEXER_RUBY_STYLE_CHARACTER 7
#define GTK_SCINTILLA_LEXER_RUBY_STYLE_CLASSNAME 8
#define GTK_SCINTILLA_LEXER_RUBY_STYLE_DEFNAME 9
#define GTK_SCINTILLA_LEXER_RUBY_STYLE_OPERATOR 10
#define GTK_SCINTILLA_LEXER_RUBY_STYLE_IDENTIFIER 11
#define GTK_SCINTILLA_LEXER_RUBY_STYLE_REGEX 12
#define GTK_SCINTILLA_LEXER_RUBY_STYLE_GLOBAL 13
#define GTK_SCINTILLA_LEXER_RUBY_STYLE_SYMBOL 14
#define GTK_SCINTILLA_LEXER_RUBY_STYLE_MODULE_NAME 15
#define GTK_SCINTILLA_LEXER_RUBY_STYLE_INSTANCE_VAR 16
#define GTK_SCINTILLA_LEXER_RUBY_STYLE_CLASS_VAR 17
#define GTK_SCINTILLA_LEXER_RUBY_STYLE_BACKTICKS 18
#define GTK_SCINTILLA_LEXER_RUBY_STYLE_DATASECTION 19
#define GTK_SCINTILLA_LEXER_RUBY_STYLE_HERE_DELIM 20
#define GTK_SCINTILLA_LEXER_RUBY_STYLE_HERE_Q 21
#define GTK_SCINTILLA_LEXER_RUBY_STYLE_HERE_QQ 22
#define GTK_SCINTILLA_LEXER_RUBY_STYLE_HERE_QX 23
#define GTK_SCINTILLA_LEXER_RUBY_STYLE_STRING_Q 24
#define GTK_SCINTILLA_LEXER_RUBY_STYLE_STRING_QQ 25
#define GTK_SCINTILLA_LEXER_RUBY_STYLE_STRING_QX 26
#define GTK_SCINTILLA_LEXER_RUBY_STYLE_STRING_QR 27
#define GTK_SCINTILLA_LEXER_RUBY_STYLE_STRING_QW 28
#define GTK_SCINTILLA_LEXER_RUBY_STYLE_WORD_DEMOTED 29
#define GTK_SCINTILLA_LEXER_RUBY_STYLE_STDIN 30
#define GTK_SCINTILLA_LEXER_RUBY_STYLE_STDOUT 31
#define GTK_SCINTILLA_LEXER_RUBY_STYLE_STDERR 40
#define GTK_SCINTILLA_LEXER_RUBY_STYLE_UPPER_BOUND 41

		
G_END_DECLS

#endif /* ifndef GSCI_RUBY_H */
