/* 
 *
 * This file is auto-generated, do not edit. 
 *
 * lexrebol.h - GScintilla Rebol Lexer
 *
 */

#ifndef GSCI_LEXER_REBOL_H
#define GSCI_LEXER_REBOL_H

G_BEGIN_DECLS

/* Lexer states */
#define GTK_SCINTILLA_LEXER_REBOL_STYLE_DEFAULT 0
#define GTK_SCINTILLA_LEXER_REBOL_STYLE_COMMENTLINE 1
#define GTK_SCINTILLA_LEXER_REBOL_STYLE_COMMENTBLOCK 2
#define GTK_SCINTILLA_LEXER_REBOL_STYLE_PREFACE 3
#define GTK_SCINTILLA_LEXER_REBOL_STYLE_OPERATOR 4
#define GTK_SCINTILLA_LEXER_REBOL_STYLE_CHARACTER 5
#define GTK_SCINTILLA_LEXER_REBOL_STYLE_QUOTEDSTRING 6
#define GTK_SCINTILLA_LEXER_REBOL_STYLE_BRACEDSTRING 7
#define GTK_SCINTILLA_LEXER_REBOL_STYLE_NUMBER 8
#define GTK_SCINTILLA_LEXER_REBOL_STYLE_PAIR 9
#define GTK_SCINTILLA_LEXER_REBOL_STYLE_TUPLE 10
#define GTK_SCINTILLA_LEXER_REBOL_STYLE_BINARY 11
#define GTK_SCINTILLA_LEXER_REBOL_STYLE_MONEY 12
#define GTK_SCINTILLA_LEXER_REBOL_STYLE_ISSUE 13
#define GTK_SCINTILLA_LEXER_REBOL_STYLE_TAG 14
#define GTK_SCINTILLA_LEXER_REBOL_STYLE_FILE 15
#define GTK_SCINTILLA_LEXER_REBOL_STYLE_EMAIL 16
#define GTK_SCINTILLA_LEXER_REBOL_STYLE_URL 17
#define GTK_SCINTILLA_LEXER_REBOL_STYLE_DATE 18
#define GTK_SCINTILLA_LEXER_REBOL_STYLE_TIME 19
#define GTK_SCINTILLA_LEXER_REBOL_STYLE_IDENTIFIER 20
#define GTK_SCINTILLA_LEXER_REBOL_STYLE_WORD 21
#define GTK_SCINTILLA_LEXER_REBOL_STYLE_WORD2 22
#define GTK_SCINTILLA_LEXER_REBOL_STYLE_WORD3 23
#define GTK_SCINTILLA_LEXER_REBOL_STYLE_WORD4 24
#define GTK_SCINTILLA_LEXER_REBOL_STYLE_WORD5 25
#define GTK_SCINTILLA_LEXER_REBOL_STYLE_WORD6 26
#define GTK_SCINTILLA_LEXER_REBOL_STYLE_WORD7 27
#define GTK_SCINTILLA_LEXER_REBOL_STYLE_WORD8 28

		
G_END_DECLS

#endif /* ifndef GSCI_REBOL_H */
