/* 
 *
 * This file is auto-generated, do not edit. 
 *
 * lexsmalltalk.h - GScintilla Smalltalk Lexer
 *
 */

#ifndef GSCI_LEXER_SMALLTALK_H
#define GSCI_LEXER_SMALLTALK_H

G_BEGIN_DECLS

/* Lexer states */
#define GTK_SCINTILLA_LEXER_SMALLTALK_STYLE_DEFAULT 0
#define GTK_SCINTILLA_LEXER_SMALLTALK_STYLE_STRING 1
#define GTK_SCINTILLA_LEXER_SMALLTALK_STYLE_NUMBER 2
#define GTK_SCINTILLA_LEXER_SMALLTALK_STYLE_COMMENT 3
#define GTK_SCINTILLA_LEXER_SMALLTALK_STYLE_SYMBOL 4
#define GTK_SCINTILLA_LEXER_SMALLTALK_STYLE_BINARY 5
#define GTK_SCINTILLA_LEXER_SMALLTALK_STYLE_BOOL 6
#define GTK_SCINTILLA_LEXER_SMALLTALK_STYLE_SELF 7
#define GTK_SCINTILLA_LEXER_SMALLTALK_STYLE_SUPER 8
#define GTK_SCINTILLA_LEXER_SMALLTALK_STYLE_NIL 9
#define GTK_SCINTILLA_LEXER_SMALLTALK_STYLE_GLOBAL 10
#define GTK_SCINTILLA_LEXER_SMALLTALK_STYLE_RETURN 11
#define GTK_SCINTILLA_LEXER_SMALLTALK_STYLE_SPECIAL 12
#define GTK_SCINTILLA_LEXER_SMALLTALK_STYLE_KWSEND 13
#define GTK_SCINTILLA_LEXER_SMALLTALK_STYLE_ASSIGN 14
#define GTK_SCINTILLA_LEXER_SMALLTALK_STYLE_CHARACTER 15
#define GTK_SCINTILLA_LEXER_SMALLTALK_STYLE_SPEC_SEL 16

		
G_END_DECLS

#endif /* ifndef GSCI_SMALLTALK_H */
