/* 
 *
 * This file is auto-generated, do not edit. 
 *
 * lexspice.h - GScintilla Spice Lexer
 *
 */

#ifndef GSCI_LEXER_SPICE_H
#define GSCI_LEXER_SPICE_H

G_BEGIN_DECLS

/* Lexer states */
#define GTK_SCINTILLA_LEXER_SPICE_STYLE_DEFAULT 0
#define GTK_SCINTILLA_LEXER_SPICE_STYLE_IDENTIFIER 1
#define GTK_SCINTILLA_LEXER_SPICE_STYLE_KEYWORD 2
#define GTK_SCINTILLA_LEXER_SPICE_STYLE_KEYWORD2 3
#define GTK_SCINTILLA_LEXER_SPICE_STYLE_KEYWORD3 4
#define GTK_SCINTILLA_LEXER_SPICE_STYLE_NUMBER 5
#define GTK_SCINTILLA_LEXER_SPICE_STYLE_DELIMITER 6
#define GTK_SCINTILLA_LEXER_SPICE_STYLE_VALUE 7
#define GTK_SCINTILLA_LEXER_SPICE_STYLE_COMMENTLINE 8

		
G_END_DECLS

#endif /* ifndef GSCI_SPICE_H */
