/* 
 *
 * This file is auto-generated, do not edit. 
 *
 * lexsorcus.h - GScintilla SORCUS Lexer
 *
 */

#ifndef GSCI_LEXER_SORCUS_H
#define GSCI_LEXER_SORCUS_H

G_BEGIN_DECLS

/* Lexer states */
#define GTK_SCINTILLA_LEXER_SORCUS_STYLE_DEFAULT 0
#define GTK_SCINTILLA_LEXER_SORCUS_STYLE_COMMAND 1
#define GTK_SCINTILLA_LEXER_SORCUS_STYLE_PARAMETER 2
#define GTK_SCINTILLA_LEXER_SORCUS_STYLE_COMMENTLINE 3
#define GTK_SCINTILLA_LEXER_SORCUS_STYLE_STRING 4
#define GTK_SCINTILLA_LEXER_SORCUS_STYLE_STRINGEOL 5
#define GTK_SCINTILLA_LEXER_SORCUS_STYLE_IDENTIFIER 6
#define GTK_SCINTILLA_LEXER_SORCUS_STYLE_OPERATOR 7
#define GTK_SCINTILLA_LEXER_SORCUS_STYLE_NUMBER 8
#define GTK_SCINTILLA_LEXER_SORCUS_STYLE_CONSTANT 9

		
G_END_DECLS

#endif /* ifndef GSCI_SORCUS_H */
