/* 
 *
 * This file is auto-generated, do not edit. 
 *
 * lexsml.h - GScintilla SML Lexer
 *
 */

#ifndef GSCI_LEXER_SML_H
#define GSCI_LEXER_SML_H

G_BEGIN_DECLS

/* Lexer states */
#define GTK_SCINTILLA_LEXER_SML_STYLE_DEFAULT 0
#define GTK_SCINTILLA_LEXER_SML_STYLE_IDENTIFIER 1
#define GTK_SCINTILLA_LEXER_SML_STYLE_TAGNAME 2
#define GTK_SCINTILLA_LEXER_SML_STYLE_KEYWORD 3
#define GTK_SCINTILLA_LEXER_SML_STYLE_KEYWORD2 4
#define GTK_SCINTILLA_LEXER_SML_STYLE_KEYWORD3 5
#define GTK_SCINTILLA_LEXER_SML_STYLE_LINENUM 6
#define GTK_SCINTILLA_LEXER_SML_STYLE_OPERATOR 7
#define GTK_SCINTILLA_LEXER_SML_STYLE_NUMBER 8
#define GTK_SCINTILLA_LEXER_SML_STYLE_CHAR 9
#define GTK_SCINTILLA_LEXER_SML_STYLE_STRING 11
#define GTK_SCINTILLA_LEXER_SML_STYLE_COMMENT 12
#define GTK_SCINTILLA_LEXER_SML_STYLE_COMMENT1 13
#define GTK_SCINTILLA_LEXER_SML_STYLE_COMMENT2 14
#define GTK_SCINTILLA_LEXER_SML_STYLE_COMMENT3 15

		
G_END_DECLS

#endif /* ifndef GSCI_SML_H */
