/* 
 *
 * This file is auto-generated, do not edit. 
 *
 * lexscriptol.h - GScintilla Sol Lexer
 *
 */

#ifndef GSCI_LEXER_SCRIPTOL_H
#define GSCI_LEXER_SCRIPTOL_H

G_BEGIN_DECLS

/* Lexer states */
#define GTK_SCINTILLA_LEXER_SCRIPTOL_STYLE_DEFAULT 0
#define GTK_SCINTILLA_LEXER_SCRIPTOL_STYLE_WHITE 1
#define GTK_SCINTILLA_LEXER_SCRIPTOL_STYLE_COMMENTLINE 2
#define GTK_SCINTILLA_LEXER_SCRIPTOL_STYLE_PERSISTENT 3
#define GTK_SCINTILLA_LEXER_SCRIPTOL_STYLE_CSTYLE 4
#define GTK_SCINTILLA_LEXER_SCRIPTOL_STYLE_COMMENTBLOCK 5
#define GTK_SCINTILLA_LEXER_SCRIPTOL_STYLE_NUMBER 6
#define GTK_SCINTILLA_LEXER_SCRIPTOL_STYLE_STRING 7
#define GTK_SCINTILLA_LEXER_SCRIPTOL_STYLE_CHARACTER 8
#define GTK_SCINTILLA_LEXER_SCRIPTOL_STYLE_STRINGEOL 9
#define GTK_SCINTILLA_LEXER_SCRIPTOL_STYLE_KEYWORD 10
#define GTK_SCINTILLA_LEXER_SCRIPTOL_STYLE_OPERATOR 11
#define GTK_SCINTILLA_LEXER_SCRIPTOL_STYLE_IDENTIFIER 12
#define GTK_SCINTILLA_LEXER_SCRIPTOL_STYLE_TRIPLE 13
#define GTK_SCINTILLA_LEXER_SCRIPTOL_STYLE_CLASSNAME 14
#define GTK_SCINTILLA_LEXER_SCRIPTOL_STYLE_PREPROCESSOR 15

		
G_END_DECLS

#endif /* ifndef GSCI_SCRIPTOL_H */
