/* 
 *
 * This file is auto-generated, do not edit. 
 *
 * lexsql.h - GScintilla SQL Lexer
 *
 */

#ifndef GSCI_LEXER_SQL_H
#define GSCI_LEXER_SQL_H

G_BEGIN_DECLS

/* Lexer states */
#define GTK_SCINTILLA_LEXER_SQL_STYLE_DEFAULT 0
#define GTK_SCINTILLA_LEXER_SQL_STYLE_COMMENT 1
#define GTK_SCINTILLA_LEXER_SQL_STYLE_COMMENTLINE 2
#define GTK_SCINTILLA_LEXER_SQL_STYLE_COMMENTDOC 3
#define GTK_SCINTILLA_LEXER_SQL_STYLE_NUMBER 4
#define GTK_SCINTILLA_LEXER_SQL_STYLE_WORD 5
#define GTK_SCINTILLA_LEXER_SQL_STYLE_STRING 6
#define GTK_SCINTILLA_LEXER_SQL_STYLE_CHARACTER 7
#define GTK_SCINTILLA_LEXER_SQL_STYLE_SQLPLUS 8
#define GTK_SCINTILLA_LEXER_SQL_STYLE_SQLPLUS_PROMPT 9
#define GTK_SCINTILLA_LEXER_SQL_STYLE_OPERATOR 10
#define GTK_SCINTILLA_LEXER_SQL_STYLE_IDENTIFIER 11
#define GTK_SCINTILLA_LEXER_SQL_STYLE_SQLPLUS_COMMENT 13
#define GTK_SCINTILLA_LEXER_SQL_STYLE_COMMENTLINEDOC 15
#define GTK_SCINTILLA_LEXER_SQL_STYLE_WORD2 16
#define GTK_SCINTILLA_LEXER_SQL_STYLE_COMMENTDOCKEYWORD 17
#define GTK_SCINTILLA_LEXER_SQL_STYLE_COMMENTDOCKEYWORDERROR 18
#define GTK_SCINTILLA_LEXER_SQL_STYLE_USER1 19
#define GTK_SCINTILLA_LEXER_SQL_STYLE_USER2 20
#define GTK_SCINTILLA_LEXER_SQL_STYLE_USER3 21
#define GTK_SCINTILLA_LEXER_SQL_STYLE_USER4 22
#define GTK_SCINTILLA_LEXER_SQL_STYLE_QUOTEDIDENTIFIER 23

		
G_END_DECLS

#endif /* ifndef GSCI_SQL_H */
