/* 
 *
 * This file is auto-generated, do not edit. 
 *
 * lextcl.h - GScintilla TCL Lexer
 *
 */

#ifndef GSCI_LEXER_TCL_H
#define GSCI_LEXER_TCL_H

G_BEGIN_DECLS

/* Lexer states */
#define GTK_SCINTILLA_LEXER_TCL_STYLE_DEFAULT 0
#define GTK_SCINTILLA_LEXER_TCL_STYLE_COMMENT 1
#define GTK_SCINTILLA_LEXER_TCL_STYLE_COMMENTLINE 2
#define GTK_SCINTILLA_LEXER_TCL_STYLE_NUMBER 3
#define GTK_SCINTILLA_LEXER_TCL_STYLE_WORD_IN_QUOTE 4
#define GTK_SCINTILLA_LEXER_TCL_STYLE_IN_QUOTE 5
#define GTK_SCINTILLA_LEXER_TCL_STYLE_OPERATOR 6
#define GTK_SCINTILLA_LEXER_TCL_STYLE_IDENTIFIER 7
#define GTK_SCINTILLA_LEXER_TCL_STYLE_SUBSTITUTION 8
#define GTK_SCINTILLA_LEXER_TCL_STYLE_SUB_BRACE 9
#define GTK_SCINTILLA_LEXER_TCL_STYLE_MODIFIER 10
#define GTK_SCINTILLA_LEXER_TCL_STYLE_EXPAND 11
#define GTK_SCINTILLA_LEXER_TCL_STYLE_WORD 12
#define GTK_SCINTILLA_LEXER_TCL_STYLE_WORD2 13
#define GTK_SCINTILLA_LEXER_TCL_STYLE_WORD3 14
#define GTK_SCINTILLA_LEXER_TCL_STYLE_WORD4 15
#define GTK_SCINTILLA_LEXER_TCL_STYLE_WORD5 16
#define GTK_SCINTILLA_LEXER_TCL_STYLE_WORD6 17
#define GTK_SCINTILLA_LEXER_TCL_STYLE_WORD7 18
#define GTK_SCINTILLA_LEXER_TCL_STYLE_WORD8 19
#define GTK_SCINTILLA_LEXER_TCL_STYLE_COMMENT_BOX 20
#define GTK_SCINTILLA_LEXER_TCL_STYLE_BLOCK_COMMENT 21

		
G_END_DECLS

#endif /* ifndef GSCI_TCL_H */
