/* 
 *
 * This file is auto-generated, do not edit. 
 *
 * lextads3.h - GScintilla TADS3 Lexer
 *
 */

#ifndef GSCI_LEXER_TADS3_H
#define GSCI_LEXER_TADS3_H

G_BEGIN_DECLS

/* Lexer states */
#define GTK_SCINTILLA_LEXER_TADS3_STYLE_DEFAULT 0
#define GTK_SCINTILLA_LEXER_TADS3_STYLE_X_DEFAULT 1
#define GTK_SCINTILLA_LEXER_TADS3_STYLE_PREPROCESSOR 2
#define GTK_SCINTILLA_LEXER_TADS3_STYLE_BLOCK_COMMENT 3
#define GTK_SCINTILLA_LEXER_TADS3_STYLE_LINE_COMMENT 4
#define GTK_SCINTILLA_LEXER_TADS3_STYLE_OPERATOR 5
#define GTK_SCINTILLA_LEXER_TADS3_STYLE_KEYWORD 6
#define GTK_SCINTILLA_LEXER_TADS3_STYLE_NUMBER 7
#define GTK_SCINTILLA_LEXER_TADS3_STYLE_IDENTIFIER 8
#define GTK_SCINTILLA_LEXER_TADS3_STYLE_S_STRING 9
#define GTK_SCINTILLA_LEXER_TADS3_STYLE_D_STRING 10
#define GTK_SCINTILLA_LEXER_TADS3_STYLE_X_STRING 11
#define GTK_SCINTILLA_LEXER_TADS3_STYLE_LIB_DIRECTIVE 12
#define GTK_SCINTILLA_LEXER_TADS3_STYLE_MSG_PARAM 13
#define GTK_SCINTILLA_LEXER_TADS3_STYLE_HTML_TAG 14
#define GTK_SCINTILLA_LEXER_TADS3_STYLE_HTML_DEFAULT 15
#define GTK_SCINTILLA_LEXER_TADS3_STYLE_HTML_STRING 16
#define GTK_SCINTILLA_LEXER_TADS3_STYLE_USER1 17
#define GTK_SCINTILLA_LEXER_TADS3_STYLE_USER2 18
#define GTK_SCINTILLA_LEXER_TADS3_STYLE_USER3 19
#define GTK_SCINTILLA_LEXER_TADS3_STYLE_BRACE 20

		
G_END_DECLS

#endif /* ifndef GSCI_TADS3_H */
