/* 
 *
 * This file is auto-generated, do not edit. 
 *
 * lexverilog.h - GScintilla Verilog Lexer
 *
 */

#ifndef GSCI_LEXER_VERILOG_H
#define GSCI_LEXER_VERILOG_H

G_BEGIN_DECLS

/* Lexer states */
#define GTK_SCINTILLA_LEXER_VERILOG_STYLE_DEFAULT 0
#define GTK_SCINTILLA_LEXER_VERILOG_STYLE_COMMENT 1
#define GTK_SCINTILLA_LEXER_VERILOG_STYLE_COMMENTLINE 2
#define GTK_SCINTILLA_LEXER_VERILOG_STYLE_COMMENTLINEBANG 3
#define GTK_SCINTILLA_LEXER_VERILOG_STYLE_NUMBER 4
#define GTK_SCINTILLA_LEXER_VERILOG_STYLE_WORD 5
#define GTK_SCINTILLA_LEXER_VERILOG_STYLE_STRING 6
#define GTK_SCINTILLA_LEXER_VERILOG_STYLE_WORD2 7
#define GTK_SCINTILLA_LEXER_VERILOG_STYLE_WORD3 8
#define GTK_SCINTILLA_LEXER_VERILOG_STYLE_PREPROCESSOR 9
#define GTK_SCINTILLA_LEXER_VERILOG_STYLE_OPERATOR 10
#define GTK_SCINTILLA_LEXER_VERILOG_STYLE_IDENTIFIER 11
#define GTK_SCINTILLA_LEXER_VERILOG_STYLE_STRINGEOL 12
#define GTK_SCINTILLA_LEXER_VERILOG_STYLE_USER 19

		
G_END_DECLS

#endif /* ifndef GSCI_VERILOG_H */
