/* 
 *
 * This file is auto-generated, do not edit. 
 *
 * lexvb.h - GScintilla VB Lexer
 *
 */

#ifndef GSCI_LEXER_VB_H
#define GSCI_LEXER_VB_H

G_BEGIN_DECLS

/* Lexer states */
#define GTK_SCINTILLA_LEXER_VB_STYLE_DEFAULT 0
#define GTK_SCINTILLA_LEXER_VB_STYLE_COMMENT 1
#define GTK_SCINTILLA_LEXER_VB_STYLE_NUMBER 2
#define GTK_SCINTILLA_LEXER_VB_STYLE_KEYWORD 3
#define GTK_SCINTILLA_LEXER_VB_STYLE_STRING 4
#define GTK_SCINTILLA_LEXER_VB_STYLE_PREPROCESSOR 5
#define GTK_SCINTILLA_LEXER_VB_STYLE_OPERATOR 6
#define GTK_SCINTILLA_LEXER_VB_STYLE_IDENTIFIER 7
#define GTK_SCINTILLA_LEXER_VB_STYLE_DATE 8
#define GTK_SCINTILLA_LEXER_VB_STYLE_STRINGEOL 9
#define GTK_SCINTILLA_LEXER_VB_STYLE_KEYWORD2 10
#define GTK_SCINTILLA_LEXER_VB_STYLE_KEYWORD3 11
#define GTK_SCINTILLA_LEXER_VB_STYLE_KEYWORD4 12
#define GTK_SCINTILLA_LEXER_VB_STYLE_CONSTANT 13
#define GTK_SCINTILLA_LEXER_VB_STYLE_ASM 14
#define GTK_SCINTILLA_LEXER_VB_STYLE_LABEL 15
#define GTK_SCINTILLA_LEXER_VB_STYLE_ERROR 16
#define GTK_SCINTILLA_LEXER_VB_STYLE_HEXNUMBER 17
#define GTK_SCINTILLA_LEXER_VB_STYLE_BINNUMBER 18

		
G_END_DECLS

#endif /* ifndef GSCI_VB_H */
