/* 
 *
 * This file is auto-generated, do not edit. 
 *
 * lexvhdl.h - GScintilla VHDL Lexer
 *
 */

#ifndef GSCI_LEXER_VHDL_H
#define GSCI_LEXER_VHDL_H

G_BEGIN_DECLS

/* Lexer states */
#define GTK_SCINTILLA_LEXER_VHDL_STYLE_DEFAULT 0
#define GTK_SCINTILLA_LEXER_VHDL_STYLE_COMMENT 1
#define GTK_SCINTILLA_LEXER_VHDL_STYLE_COMMENTLINEBANG 2
#define GTK_SCINTILLA_LEXER_VHDL_STYLE_NUMBER 3
#define GTK_SCINTILLA_LEXER_VHDL_STYLE_STRING 4
#define GTK_SCINTILLA_LEXER_VHDL_STYLE_OPERATOR 5
#define GTK_SCINTILLA_LEXER_VHDL_STYLE_IDENTIFIER 6
#define GTK_SCINTILLA_LEXER_VHDL_STYLE_STRINGEOL 7
#define GTK_SCINTILLA_LEXER_VHDL_STYLE_KEYWORD 8
#define GTK_SCINTILLA_LEXER_VHDL_STYLE_STDOPERATOR 9
#define GTK_SCINTILLA_LEXER_VHDL_STYLE_ATTRIBUTE 10
#define GTK_SCINTILLA_LEXER_VHDL_STYLE_STDFUNCTION 11
#define GTK_SCINTILLA_LEXER_VHDL_STYLE_STDPACKAGE 12
#define GTK_SCINTILLA_LEXER_VHDL_STYLE_STDTYPE 13
#define GTK_SCINTILLA_LEXER_VHDL_STYLE_USERWORD 14

		
G_END_DECLS

#endif /* ifndef GSCI_VHDL_H */
