/* 
 *
 * This file is auto-generated, do not edit. 
 *
 * lexyaml.h - GScintilla YAML Lexer
 *
 */

#ifndef GSCI_LEXER_YAML_H
#define GSCI_LEXER_YAML_H

G_BEGIN_DECLS

/* Lexer states */
#define GTK_SCINTILLA_LEXER_YAML_STYLE_DEFAULT 0
#define GTK_SCINTILLA_LEXER_YAML_STYLE_COMMENT 1
#define GTK_SCINTILLA_LEXER_YAML_STYLE_IDENTIFIER 2
#define GTK_SCINTILLA_LEXER_YAML_STYLE_KEYWORD 3
#define GTK_SCINTILLA_LEXER_YAML_STYLE_NUMBER 4
#define GTK_SCINTILLA_LEXER_YAML_STYLE_REFERENCE 5
#define GTK_SCINTILLA_LEXER_YAML_STYLE_DOCUMENT 6
#define GTK_SCINTILLA_LEXER_YAML_STYLE_TEXT 7
#define GTK_SCINTILLA_LEXER_YAML_STYLE_ERROR 8
#define GTK_SCINTILLA_LEXER_YAML_STYLE_OPERATOR 9

		
G_END_DECLS

#endif /* ifndef GSCI_YAML_H */
