#!/usr/bin/env python

from sciface.function import Function

if __name__ == "__main__":

	from optparse import OptionParser
	
	p = OptionParser(
			usage='Usage: %prog [options] FILE',
			description='Output function prototypes and/or function ' +
					'definitions for all functions in the ' +
					'Scintilla.iface file specified in FILE argument.')
	
	p.add_option('-p', dest='proto', action='store_true',
		default=False, help='print function prototypes')
	p.add_option('-d', dest='defs', action='store_true',
		default=False, help='print function definitions')
	p.add_option('-n', dest='ns', metavar='PREFIX', 
		default='gtk_scintilla',
		help='namespace to prefix to all function names')
	
	opts, args = p.parse_args()

	if not opts.proto and not opts.defs:
		opts.defs = True
	
	if len(args) < 1:
		p.error('missing interface FILE')
	
	if len(args) > 1:
		p.error('too many arguments for FILE')
	
	if opts.proto:
		for func in Function.iter_functions(args[0], opts.ns):
			print func.prototype
			
	if opts.defs:
		for func in Function.iter_functions(args[0], opts.ns):
			if func.definition:
				print func.definition
