/* gtkieditorlexer.c generated by valac 0.10.0, the Vala compiler
 * generated from gtkieditorlexer.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include "gtkeditor.h"
#include <stdlib.h>
#include <string.h>







gboolean gtk_ieditor_lexer_read_config (GtkIEditorLexer* self, const char* filename) {
	return GTK_IEDITOR_LEXER_GET_INTERFACE (self)->read_config (self, filename);
}


gboolean gtk_ieditor_lexer_write_config (GtkIEditorLexer* self, const char* filename) {
	return GTK_IEDITOR_LEXER_GET_INTERFACE (self)->write_config (self, filename);
}


char** gtk_ieditor_lexer_list_props (GtkIEditorLexer* self, int* result_length1) {
	return GTK_IEDITOR_LEXER_GET_INTERFACE (self)->list_props (self, result_length1);
}


gboolean gtk_ieditor_lexer_has_prop (GtkIEditorLexer* self, const char* propname) {
	return GTK_IEDITOR_LEXER_GET_INTERFACE (self)->has_prop (self, propname);
}


gboolean gtk_ieditor_lexer_get_prop_as_int (GtkIEditorLexer* self, const char* propname, gint* propvalue) {
	return GTK_IEDITOR_LEXER_GET_INTERFACE (self)->get_prop_as_int (self, propname, propvalue);
}


gboolean gtk_ieditor_lexer_get_prop_as_bool (GtkIEditorLexer* self, const char* propname, gboolean* propvalue) {
	return GTK_IEDITOR_LEXER_GET_INTERFACE (self)->get_prop_as_bool (self, propname, propvalue);
}


gboolean gtk_ieditor_lexer_get_prop_as_string (GtkIEditorLexer* self, const char* propname, char** propvalue) {
	return GTK_IEDITOR_LEXER_GET_INTERFACE (self)->get_prop_as_string (self, propname, propvalue);
}


char* gtk_ieditor_lexer_get_prop (GtkIEditorLexer* self, const char* propname) {
	return GTK_IEDITOR_LEXER_GET_INTERFACE (self)->get_prop (self, propname);
}


gboolean gtk_ieditor_lexer_set_prop (GtkIEditorLexer* self, const char* propname, const char* propvalue) {
	return GTK_IEDITOR_LEXER_GET_INTERFACE (self)->set_prop (self, propname, propvalue);
}


static void gtk_ieditor_lexer_base_init (GtkIEditorLexerIface * iface) {
	static gboolean initialized = FALSE;
	if (!initialized) {
		initialized = TRUE;
	}
}


GType gtk_ieditor_lexer_get_type (void) {
	static volatile gsize gtk_ieditor_lexer_type_id__volatile = 0;
	if (g_once_init_enter (&gtk_ieditor_lexer_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (GtkIEditorLexerIface), (GBaseInitFunc) gtk_ieditor_lexer_base_init, (GBaseFinalizeFunc) NULL, (GClassInitFunc) NULL, (GClassFinalizeFunc) NULL, NULL, 0, 0, (GInstanceInitFunc) NULL, NULL };
		GType gtk_ieditor_lexer_type_id;
		gtk_ieditor_lexer_type_id = g_type_register_static (G_TYPE_INTERFACE, "GtkIEditorLexer", &g_define_type_info, 0);
		g_type_interface_add_prerequisite (gtk_ieditor_lexer_type_id, G_TYPE_OBJECT);
		g_once_init_leave (&gtk_ieditor_lexer_type_id__volatile, gtk_ieditor_lexer_type_id);
	}
	return gtk_ieditor_lexer_type_id__volatile;
}




