/* This file is auto-generated, do not edit. */

#ifndef GTK_SCINTILLA_CONSTANTS_H
#define GTK_SCINTILLA_CONSTANTS_H

G_BEGIN_DECLS

#define GTK_SCINTILLA_INVALID_POSITION -1
#define GTK_SCINTILLA_START 2000
#define GTK_SCINTILLA_OPTIONAL_START 3000
#define GTK_SCINTILLA_LEXER_START 4000
#define GTK_SCINTILLA_CP_UTF8 65001
#define GTK_SCINTILLA_CP_DBCS 1
#define GTK_SCINTILLA_MARKER_MAX 31
#define GTK_SCINTILLA_MASK_FOLDERS 0xFE000000
#define GTK_SCINTILLA_TIME_FOREVER 10000000
#define GTK_SCINTILLA_VISIBLE_SLOP 0x01
#define GTK_SCINTILLA_VISIBLE_STRICT 0x04
#define GTK_SCINTILLA_ALPHA_TRANSPARENT 0
#define GTK_SCINTILLA_ALPHA_OPAQUE 255
#define GTK_SCINTILLA_ALPHA_NOALPHA 256
#define GTK_SCINTILLA_UNDO_MAY_COALESCE 1
#define GTK_SCINTILLA_KEYWORDSET_MAX 8
#define GTK_SCINTILLA_MODEVENTMASKALL 0x7FFFF

/**
 * GtkScintillaUpdateFlag:
 * @GTK_SCINTILLA_UPDATE_CONTENT:	Contents, styling or markers have been
 * 									changed.
 * @GTK_SCINTILLA_UPDATE_SELECTION:	Selection has been changed.
 * @GTK_SCINTILLA_UPDATE_V_SCROLL:	Scrolled vertically.
 * @GTK_SCINTILLA_UPDATE_H_SCROLL:	Scrolled horizontally.
 * 
 * When the #GtkScintilla::update-ui signal is emitted, a bit field of these
 * flags is passed as a parameter to indicate which part of the UI has changed.
 */
typedef enum {
	GTK_SCINTILLA_UPDATE_CONTENT=0x01,
	GTK_SCINTILLA_UPDATE_SELECTION=0x02,
	GTK_SCINTILLA_UPDATE_V_SCROLL=0x04,
	GTK_SCINTILLA_UPDATE_H_SCROLL=0x08
} GtkScintillaUpdateFlag;

/**
 * GtkScintillaSearchFlag:
 * @GTK_SCINTILLA_SEARCH_FLAG_WHOLE_WORD:	A match only occurs if the
 * 											characters before and after are not
 * 											whole words.
 * @GTK_SCINTILLA_SEARCH_FLAG_MATCH_CASE:	A match only occurs with text that
 * 											matches the case of the search
 * 											string.
 * @GTK_SCINTILLA_SEARCH_FLAG_WORD_START:	A match only occurs if the 
 * 											character before is not a word
 * 											character.
 * @GTK_SCINTILLA_SEARCH_FLAG_REGEXP:		The search string should be 
 * 											interpreted as a regular
 * 											expression.
 * @GTK_SCINTILLA_SEARCH_FLAG_POSIX:		Treat regular expression in a more
 * 											POSIX compatible manner by 
 * 											interpreting bare ( and ) for
 * 											tagged sections rather than 
 * 											\( and \).
 * 
 * Several of the search routines use flag options, which include a simple 
 * regular expression search.  Combine flag options by adding them.
 */
typedef enum {
	GTK_SCINTILLA_SEARCH_FLAG_WHOLE_WORD=2,
	GTK_SCINTILLA_SEARCH_FLAG_MATCH_CASE=4,
	GTK_SCINTILLA_SEARCH_FLAG_WORD_START=0x00100000,
	GTK_SCINTILLA_SEARCH_FLAG_REGEXP=0x00200000,
	GTK_SCINTILLA_SEARCH_FLAG_POSIX=0x00400000
} GtkScintillaSearchFlag;

typedef enum {
	GTK_SCINTILLA_WHITE_SPACE_INVISIBLE=0,
	GTK_SCINTILLA_WHITE_SPACE_VISIBLEALWAYS=1,
	GTK_SCINTILLA_WHITE_SPACE_VISIBLEAFTERINDENT=2
} GtkScintillaWhiteSpace;

typedef enum {
	GTK_SCINTILLA_END_OF_LINE_CRLF=0,
	GTK_SCINTILLA_END_OF_LINE_CR=1,
	GTK_SCINTILLA_END_OF_LINE_LF=2
} GtkScintillaEndOfLine;

typedef enum {
	GTK_SCINTILLA_MARKER_SYMBOL_CIRCLE=0,
	GTK_SCINTILLA_MARKER_SYMBOL_ROUNDRECT=1,
	GTK_SCINTILLA_MARKER_SYMBOL_ARROW=2,
	GTK_SCINTILLA_MARKER_SYMBOL_SMALLRECT=3,
	GTK_SCINTILLA_MARKER_SYMBOL_SHORTARROW=4,
	GTK_SCINTILLA_MARKER_SYMBOL_EMPTY=5,
	GTK_SCINTILLA_MARKER_SYMBOL_ARROWDOWN=6,
	GTK_SCINTILLA_MARKER_SYMBOL_MINUS=7,
	GTK_SCINTILLA_MARKER_SYMBOL_PLUS=8,
	GTK_SCINTILLA_MARKER_SYMBOL_VLINE=9,
	GTK_SCINTILLA_MARKER_SYMBOL_LCORNER=10,
	GTK_SCINTILLA_MARKER_SYMBOL_TCORNER=11,
	GTK_SCINTILLA_MARKER_SYMBOL_BOXPLUS=12,
	GTK_SCINTILLA_MARKER_SYMBOL_BOXPLUSCONNECTED=13,
	GTK_SCINTILLA_MARKER_SYMBOL_BOXMINUS=14,
	GTK_SCINTILLA_MARKER_SYMBOL_BOXMINUSCONNECTED=15,
	GTK_SCINTILLA_MARKER_SYMBOL_LCORNERCURVE=16,
	GTK_SCINTILLA_MARKER_SYMBOL_TCORNERCURVE=17,
	GTK_SCINTILLA_MARKER_SYMBOL_CIRCLEPLUS=18,
	GTK_SCINTILLA_MARKER_SYMBOL_CIRCLEPLUSCONNECTED=19,
	GTK_SCINTILLA_MARKER_SYMBOL_CIRCLEMINUS=20,
	GTK_SCINTILLA_MARKER_SYMBOL_CIRCLEMINUSCONNECTED=21,
	GTK_SCINTILLA_MARKER_SYMBOL_BACKGROUND=22,
	GTK_SCINTILLA_MARKER_SYMBOL_DOTDOTDOT=23,
	GTK_SCINTILLA_MARKER_SYMBOL_ARROWS=24,
	GTK_SCINTILLA_MARKER_SYMBOL_PIXMAP=25,
	GTK_SCINTILLA_MARKER_SYMBOL_FULLRECT=26,
	GTK_SCINTILLA_MARKER_SYMBOL_LEFTRECT=27,
	GTK_SCINTILLA_MARKER_SYMBOL_AVAILABLE=28,
	GTK_SCINTILLA_MARKER_SYMBOL_UNDERLINE=29,
	GTK_SCINTILLA_MARKER_SYMBOL_CHARACTER=10000
} GtkScintillaMarkerSymbol;

typedef enum {
	GTK_SCINTILLA_MARKER_OUTLINE_FOLDEREND=25,
	GTK_SCINTILLA_MARKER_OUTLINE_FOLDEROPENMID=26,
	GTK_SCINTILLA_MARKER_OUTLINE_FOLDERMIDTAIL=27,
	GTK_SCINTILLA_MARKER_OUTLINE_FOLDERTAIL=28,
	GTK_SCINTILLA_MARKER_OUTLINE_FOLDERSUB=29,
	GTK_SCINTILLA_MARKER_OUTLINE_FOLDER=30,
	GTK_SCINTILLA_MARKER_OUTLINE_FOLDEROPEN=31
} GtkScintillaMarkerOutline;

typedef enum {
	GTK_SCINTILLA_MARGIN_TYPE_SYMBOL=0,
	GTK_SCINTILLA_MARGIN_TYPE_NUMBER=1,
	GTK_SCINTILLA_MARGIN_TYPE_BACK=2,
	GTK_SCINTILLA_MARGIN_TYPE_FORE=3,
	GTK_SCINTILLA_MARGIN_TYPE_TEXT=4,
	GTK_SCINTILLA_MARGIN_TYPE_RTEXT=5
} GtkScintillaMarginType;

typedef enum {
	GTK_SCINTILLA_STYLES_COMMON_DEFAULT=32,
	GTK_SCINTILLA_STYLES_COMMON_LINENUMBER=33,
	GTK_SCINTILLA_STYLES_COMMON_BRACELIGHT=34,
	GTK_SCINTILLA_STYLES_COMMON_BRACEBAD=35,
	GTK_SCINTILLA_STYLES_COMMON_CONTROLCHAR=36,
	GTK_SCINTILLA_STYLES_COMMON_INDENTGUIDE=37,
	GTK_SCINTILLA_STYLES_COMMON_CALLTIP=38,
	GTK_SCINTILLA_STYLES_COMMON_LASTPREDEFINED=39,
	GTK_SCINTILLA_STYLES_COMMON_MAX=255
} GtkScintillaStylesCommon;

typedef enum {
	GTK_SCINTILLA_CHARACTER_SET_ANSI=0,
	GTK_SCINTILLA_CHARACTER_SET_DEFAULT=1,
	GTK_SCINTILLA_CHARACTER_SET_BALTIC=186,
	GTK_SCINTILLA_CHARACTER_SET_CHINESEBIG5=136,
	GTK_SCINTILLA_CHARACTER_SET_EASTEUROPE=238,
	GTK_SCINTILLA_CHARACTER_SET_GB2312=134,
	GTK_SCINTILLA_CHARACTER_SET_GREEK=161,
	GTK_SCINTILLA_CHARACTER_SET_HANGUL=129,
	GTK_SCINTILLA_CHARACTER_SET_MAC=77,
	GTK_SCINTILLA_CHARACTER_SET_OEM=255,
	GTK_SCINTILLA_CHARACTER_SET_RUSSIAN=204,
	GTK_SCINTILLA_CHARACTER_SET_CYRILLIC=1251,
	GTK_SCINTILLA_CHARACTER_SET_SHIFTJIS=128,
	GTK_SCINTILLA_CHARACTER_SET_SYMBOL=2,
	GTK_SCINTILLA_CHARACTER_SET_TURKISH=162,
	GTK_SCINTILLA_CHARACTER_SET_JOHAB=130,
	GTK_SCINTILLA_CHARACTER_SET_HEBREW=177,
	GTK_SCINTILLA_CHARACTER_SET_ARABIC=178,
	GTK_SCINTILLA_CHARACTER_SET_VIETNAMESE=163,
	GTK_SCINTILLA_CHARACTER_SET_THAI=222,
	GTK_SCINTILLA_CHARACTER_SET_8859_15=1000
} GtkScintillaCharacterSet;

typedef enum {
	GTK_SCINTILLA_CASE_MIXED=0,
	GTK_SCINTILLA_CASE_UPPER=1,
	GTK_SCINTILLA_CASE_LOWER=2
} GtkScintillaCase;

typedef enum {
	GTK_SCINTILLA_INDICATOR_STYLE_PLAIN=0,
	GTK_SCINTILLA_INDICATOR_STYLE_SQUIGGLE=1,
	GTK_SCINTILLA_INDICATOR_STYLE_TT=2,
	GTK_SCINTILLA_INDICATOR_STYLE_DIAGONAL=3,
	GTK_SCINTILLA_INDICATOR_STYLE_STRIKE=4,
	GTK_SCINTILLA_INDICATOR_STYLE_HIDDEN=5,
	GTK_SCINTILLA_INDICATOR_STYLE_BOX=6,
	GTK_SCINTILLA_INDICATOR_STYLE_ROUNDBOX=7,
	GTK_SCINTILLA_INDICATOR_STYLE_MAX=31,
	GTK_SCINTILLA_INDICATOR_STYLE_CONTAINER=8,
	GTK_SCINTILLA_INDICATOR_STYLE_0_MASK=0x20,
	GTK_SCINTILLA_INDICATOR_STYLE_1_MASK=0x40,
	GTK_SCINTILLA_INDICATOR_STYLE_2_MASK=0x80,
	GTK_SCINTILLA_INDICATOR_STYLE_S_MASK=0xE0
} GtkScintillaIndicatorStyle;

typedef enum {
	GTK_SCINTILLA_INDENT_VIEW_NONE=0,
	GTK_SCINTILLA_INDENT_VIEW_REAL=1,
	GTK_SCINTILLA_INDENT_VIEW_LOOKFORWARD=2,
	GTK_SCINTILLA_INDENT_VIEW_LOOKBOTH=3
} GtkScintillaIndentView;

typedef enum {
	GTK_SCINTILLA_PRINT_OPTION_NORMAL=0,
	GTK_SCINTILLA_PRINT_OPTION_INVERTLIGHT=1,
	GTK_SCINTILLA_PRINT_OPTION_BLACKONWHITE=2,
	GTK_SCINTILLA_PRINT_OPTION_COLOURONWHITE=3,
	GTK_SCINTILLA_PRINT_OPTION_COLOURONWHITEDEFAULTBG=4
} GtkScintillaPrintOption;

typedef enum {
	GTK_SCINTILLA_FIND_OPTION_WHOLEWORD=2,
	GTK_SCINTILLA_FIND_OPTION_MATCHCASE=4,
	GTK_SCINTILLA_FIND_OPTION_WORDSTART=0x00100000,
	GTK_SCINTILLA_FIND_OPTION_REGEXP=0x00200000,
	GTK_SCINTILLA_FIND_OPTION_POSIX=0x00400000
} GtkScintillaFindOption;

typedef enum {
	GTK_SCINTILLA_FOLD_LEVEL_BASE=0x400,
	GTK_SCINTILLA_FOLD_LEVEL_WHITEFLAG=0x1000,
	GTK_SCINTILLA_FOLD_LEVEL_HEADERFLAG=0x2000,
	GTK_SCINTILLA_FOLD_LEVEL_NUMBERMASK=0x0FFF
} GtkScintillaFoldLevel;

typedef enum {
	GTK_SCINTILLA_FOLD_FLAG_LINEBEFORE_EXPANDED=0x0002,
	GTK_SCINTILLA_FOLD_FLAG_LINEBEFORE_CONTRACTED=0x0004,
	GTK_SCINTILLA_FOLD_FLAG_LINEAFTER_EXPANDED=0x0008,
	GTK_SCINTILLA_FOLD_FLAG_LINEAFTER_CONTRACTED=0x0010,
	GTK_SCINTILLA_FOLD_FLAG_LEVELNUMBERS=0x0040
} GtkScintillaFoldFlag;

typedef enum {
	GTK_SCINTILLA_WRAP_NONE=0,
	GTK_SCINTILLA_WRAP_WORD=1,
	GTK_SCINTILLA_WRAP_CHAR=2
} GtkScintillaWrap;

typedef enum {
	GTK_SCINTILLA_WRAP_VISUAL_FLAG_NONE=0x0000,
	GTK_SCINTILLA_WRAP_VISUAL_FLAG_END=0x0001,
	GTK_SCINTILLA_WRAP_VISUAL_FLAG_START=0x0002
} GtkScintillaWrapVisualFlag;

typedef enum {
	GTK_SCINTILLA_WRAP_VISUAL_LOCATION_DEFAULT=0x0000,
	GTK_SCINTILLA_WRAP_VISUAL_LOCATION_END_BY_TEXT=0x0001,
	GTK_SCINTILLA_WRAP_VISUAL_LOCATION_START_BY_TEXT=0x0002
} GtkScintillaWrapVisualLocation;

typedef enum {
	GTK_SCINTILLA_WRAP_INDENT_MODE_FIXED=0,
	GTK_SCINTILLA_WRAP_INDENT_MODE_SAME=1,
	GTK_SCINTILLA_WRAP_INDENT_MODE_INDENT=2
} GtkScintillaWrapIndentMode;

typedef enum {
	GTK_SCINTILLA_LINE_CACHE_NONE=0,
	GTK_SCINTILLA_LINE_CACHE_CARET=1,
	GTK_SCINTILLA_LINE_CACHE_PAGE=2,
	GTK_SCINTILLA_LINE_CACHE_DOCUMENT=3
} GtkScintillaLineCache;

typedef enum {
	GTK_SCINTILLA_FONT_QUALITY_QUALITY_MASK=0xF,
	GTK_SCINTILLA_FONT_QUALITY_QUALITY_DEFAULT=0,
	GTK_SCINTILLA_FONT_QUALITY_QUALITY_NON_ANTIALIASED=1,
	GTK_SCINTILLA_FONT_QUALITY_QUALITY_ANTIALIASED=2,
	GTK_SCINTILLA_FONT_QUALITY_QUALITY_LCD_OPTIMIZED=3
} GtkScintillaFontQuality;

typedef enum {
	GTK_SCINTILLA_MULTI_PASTE_ONCE=0,
	GTK_SCINTILLA_MULTI_PASTE_EACH=1
} GtkScintillaMultiPaste;

typedef enum {
	GTK_SCINTILLA_EDGE_VISUAL_STYLE_NONE=0,
	GTK_SCINTILLA_EDGE_VISUAL_STYLE_LINE=1,
	GTK_SCINTILLA_EDGE_VISUAL_STYLE_BACKGROUND=2
} GtkScintillaEdgeVisualStyle;

typedef enum {
	GTK_SCINTILLA_STATUS_OK=0,
	GTK_SCINTILLA_STATUS_FAILURE=1,
	GTK_SCINTILLA_STATUS_BADALLOC=2
} GtkScintillaStatus;

typedef enum {
	GTK_SCINTILLA_CURSOR_SHAPE_NORMAL=-1,
	GTK_SCINTILLA_CURSOR_SHAPE_WAIT=4
} GtkScintillaCursorShape;

typedef enum {
	GTK_SCINTILLA_CARET_POLICY_SLOP=0x01,
	GTK_SCINTILLA_CARET_POLICY_STRICT=0x04,
	GTK_SCINTILLA_CARET_POLICY_JUMPS=0x10,
	GTK_SCINTILLA_CARET_POLICY_EVEN=0x08
} GtkScintillaCaretPolicy;

typedef enum {
	GTK_SCINTILLA_SELECTION_MODE_STREAM=0,
	GTK_SCINTILLA_SELECTION_MODE_RECTANGLE=1,
	GTK_SCINTILLA_SELECTION_MODE_LINES=2,
	GTK_SCINTILLA_SELECTION_MODE_THIN=3
} GtkScintillaSelectionMode;

typedef enum {
	GTK_SCINTILLA_CARET_STICKY_OFF=0,
	GTK_SCINTILLA_CARET_STICKY_ON=1,
	GTK_SCINTILLA_CARET_STICKY_WHITESPACE=2
} GtkScintillaCaretSticky;

typedef enum {
	GTK_SCINTILLA_CARET_STYLE_INVISIBLE=0,
	GTK_SCINTILLA_CARET_STYLE_LINE=1,
	GTK_SCINTILLA_CARET_STYLE_BLOCK=2
} GtkScintillaCaretStyle;

typedef enum {
	GTK_SCINTILLA_ANNOTATION_VISIBLE_HIDDEN=0,
	GTK_SCINTILLA_ANNOTATION_VISIBLE_STANDARD=1,
	GTK_SCINTILLA_ANNOTATION_VISIBLE_BOXED=2
} GtkScintillaAnnotationVisible;

typedef enum {
	GTK_SCINTILLA_VIRTUAL_SPACE_NONE=0,
	GTK_SCINTILLA_VIRTUAL_SPACE_RECTANGULARSELECTION=1,
	GTK_SCINTILLA_VIRTUAL_SPACE_USERACCESSIBLE=2
} GtkScintillaVirtualSpace;

typedef enum {
	GTK_SCINTILLA_MODIFICATION_FLAGS_INSERT_TEXT=0x1,
	GTK_SCINTILLA_MODIFICATION_FLAGS_DELETE_TEXT=0x2,
	GTK_SCINTILLA_MODIFICATION_FLAGS_CHANGE_STYLE=0x4,
	GTK_SCINTILLA_MODIFICATION_FLAGS_CHANGE_FOLD=0x8,
	GTK_SCINTILLA_MODIFICATION_FLAGS_USER=0x10,
	GTK_SCINTILLA_MODIFICATION_FLAGS_UNDO=0x20,
	GTK_SCINTILLA_MODIFICATION_FLAGS_REDO=0x40,
	GTK_SCINTILLA_MODIFICATION_FLAGS_MULTI_STEP_UNDO_REDO=0x80,
	GTK_SCINTILLA_MODIFICATION_FLAGS_MULTI_STEP_IN_UNDO_REDO=0x100,
	GTK_SCINTILLA_MODIFICATION_FLAGS_CHANGE_MARKER=0x200,
	GTK_SCINTILLA_MODIFICATION_FLAGS_BEFORE_INSERT=0x400,
	GTK_SCINTILLA_MODIFICATION_FLAGS_BEFORE_DELETE=0x800,
	GTK_SCINTILLA_MODIFICATION_FLAGS_MULTI_LINE_UNDO_REDO=0x1000,
	GTK_SCINTILLA_MODIFICATION_FLAGS_START_ACTION=0x2000,
	GTK_SCINTILLA_MODIFICATION_FLAGS_CHANGE_INDICATOR=0x4000,
	GTK_SCINTILLA_MODIFICATION_FLAGS_CHANGE_LINE_STATE=0x8000,
	GTK_SCINTILLA_MODIFICATION_FLAGS_CHANGE_MARGIN=0x10000,
	GTK_SCINTILLA_MODIFICATION_FLAGS_CHANGE_ANNOTATION=0x20000,
	GTK_SCINTILLA_MODIFICATION_FLAGS_CONTAINER=0x40000
	/* todo: these are separate */
	/*GTK_SCINTILLA_MODIFICATION_FLAGS_CHANGE=768,*/
	/*GTK_SCINTILLA_MODIFICATION_FLAGS_SETFOCUS=512,*/
	/*GTK_SCINTILLA_MODIFICATION_FLAGS_KILLFOCUS=256*/
} GtkScintillaModificationFlags;

typedef enum {
	GTK_SCINTILLA_KEYS_DOWN=300,
	GTK_SCINTILLA_KEYS_UP=301,
	GTK_SCINTILLA_KEYS_LEFT=302,
	GTK_SCINTILLA_KEYS_RIGHT=303,
	GTK_SCINTILLA_KEYS_HOME=304,
	GTK_SCINTILLA_KEYS_END=305,
	GTK_SCINTILLA_KEYS_PRIOR=306,
	GTK_SCINTILLA_KEYS_NEXT=307,
	GTK_SCINTILLA_KEYS_DELETE=308,
	GTK_SCINTILLA_KEYS_INSERT=309,
	GTK_SCINTILLA_KEYS_ESCAPE=7,
	GTK_SCINTILLA_KEYS_BACK=8,
	GTK_SCINTILLA_KEYS_TAB=9,
	GTK_SCINTILLA_KEYS_RETURN=13,
	GTK_SCINTILLA_KEYS_ADD=310,
	GTK_SCINTILLA_KEYS_SUBTRACT=311,
	GTK_SCINTILLA_KEYS_DIVIDE=312,
	GTK_SCINTILLA_KEYS_WIN=313,
	GTK_SCINTILLA_KEYS_RWIN=314,
	GTK_SCINTILLA_KEYS_MENU=315
} GtkScintillaKeys;

typedef enum {
	GTK_SCINTILLA_KEY_MOD_NORM=0,
	GTK_SCINTILLA_KEY_MOD_SHIFT=1,
	GTK_SCINTILLA_KEY_MOD_CTRL=2,
	GTK_SCINTILLA_KEY_MOD_ALT=4,
	GTK_SCINTILLA_KEY_MOD_SUPER=8
} GtkScintillaKeyMod;

/**
 * GtkScintillaLexers:
 * @GTK_SCINTILLA_LEXER_CONTAINER:	Specifies that you would like to perform
 * 									styling yourself.  This lexer will cause
 * 									the #GtkScintilla::style-needed signal to
 * 									be emitted when you need to style a range
 * 									of text.
 * @GTK_SCINTILLA_LEXER_NULL:		Specifies that no lexer should be used.
 * 
 * Enum values used to specify a lexer to gtk_scintilla_set_lexer().  Generally
 * the lexer's name here will indicate the corresponding programming language,
 * but some of the lexers support numerous programming languages.  For example,
 * the @GTK_SCINTILLA_LEXER_CPP will style C/C++, Java, Vala and similar 
 * languages, while the @GTK_SCINTILLA_LEXER_HTML will style HTML, XML, PHP,
 * and several other similar or embedable languages.
 */
typedef enum {
	GTK_SCINTILLA_LEXER_CONTAINER=0, 
	GTK_SCINTILLA_LEXER_NULL=1,
	GTK_SCINTILLA_LEXER_PYTHON=2,
	GTK_SCINTILLA_LEXER_CPP=3,
	GTK_SCINTILLA_LEXER_HTML=4,
	GTK_SCINTILLA_LEXER_XML=5,
	GTK_SCINTILLA_LEXER_PERL=6,
	GTK_SCINTILLA_LEXER_SQL=7,
	GTK_SCINTILLA_LEXER_VB=8,
	GTK_SCINTILLA_LEXER_PROPERTIES=9,
	GTK_SCINTILLA_LEXER_ERRORLIST=10,
	GTK_SCINTILLA_LEXER_MAKEFILE=11,
	GTK_SCINTILLA_LEXER_BATCH=12,
	GTK_SCINTILLA_LEXER_XCODE=13,
	GTK_SCINTILLA_LEXER_LATEX=14,
	GTK_SCINTILLA_LEXER_LUA=15,
	GTK_SCINTILLA_LEXER_DIFF=16,
	GTK_SCINTILLA_LEXER_CONF=17,
	GTK_SCINTILLA_LEXER_PASCAL=18,
	GTK_SCINTILLA_LEXER_AVE=19,
	GTK_SCINTILLA_LEXER_ADA=20,
	GTK_SCINTILLA_LEXER_LISP=21,
	GTK_SCINTILLA_LEXER_RUBY=22,
	GTK_SCINTILLA_LEXER_EIFFEL=23,
	GTK_SCINTILLA_LEXER_EIFFELKW=24,
	GTK_SCINTILLA_LEXER_TCL=25,
	GTK_SCINTILLA_LEXER_NNCRONTAB=26,
	GTK_SCINTILLA_LEXER_BULLANT=27,
	GTK_SCINTILLA_LEXER_VBSCRIPT=28,
	GTK_SCINTILLA_LEXER_BAAN=31,
	GTK_SCINTILLA_LEXER_MATLAB=32,
	GTK_SCINTILLA_LEXER_SCRIPTOL=33,
	GTK_SCINTILLA_LEXER_ASM=34,
	GTK_SCINTILLA_LEXER_CPPNOCASE=35,
	GTK_SCINTILLA_LEXER_FORTRAN=36,
	GTK_SCINTILLA_LEXER_F77=37,
	GTK_SCINTILLA_LEXER_CSS=38,
	GTK_SCINTILLA_LEXER_POV=39,
	GTK_SCINTILLA_LEXER_LOUT=40,
	GTK_SCINTILLA_LEXER_ESCRIPT=41,
	GTK_SCINTILLA_LEXER_PS=42,
	GTK_SCINTILLA_LEXER_NSIS=43,
	GTK_SCINTILLA_LEXER_MMIXAL=44,
	GTK_SCINTILLA_LEXER_CLW=45,
	GTK_SCINTILLA_LEXER_CLWNOCASE=46,
	GTK_SCINTILLA_LEXER_LOT=47,
	GTK_SCINTILLA_LEXER_YAML=48,
	GTK_SCINTILLA_LEXER_TEX=49,
	GTK_SCINTILLA_LEXER_METAPOST=50,
	GTK_SCINTILLA_LEXER_POWERBASIC=51,
	GTK_SCINTILLA_LEXER_FORTH=52,
	GTK_SCINTILLA_LEXER_ERLANG=53,
	GTK_SCINTILLA_LEXER_OCTAVE=54,
	GTK_SCINTILLA_LEXER_MSSQL=55,
	GTK_SCINTILLA_LEXER_VERILOG=56,
	GTK_SCINTILLA_LEXER_KIX=57,
	GTK_SCINTILLA_LEXER_GUI4CLI=58,
	GTK_SCINTILLA_LEXER_SPECMAN=59,
	GTK_SCINTILLA_LEXER_AU3=60,
	GTK_SCINTILLA_LEXER_APDL=61,
	GTK_SCINTILLA_LEXER_BASH=62,
	GTK_SCINTILLA_LEXER_ASN1=63,
	GTK_SCINTILLA_LEXER_VHDL=64,
	GTK_SCINTILLA_LEXER_CAML=65,
	GTK_SCINTILLA_LEXER_BLITZBASIC=66,
	GTK_SCINTILLA_LEXER_PUREBASIC=67,
	GTK_SCINTILLA_LEXER_HASKELL=68,
	GTK_SCINTILLA_LEXER_PHPSCRIPT=69,
	GTK_SCINTILLA_LEXER_TADS3=70,
	GTK_SCINTILLA_LEXER_REBOL=71,
	GTK_SCINTILLA_LEXER_SMALLTALK=72,
	GTK_SCINTILLA_LEXER_FLAGSHIP=73,
	GTK_SCINTILLA_LEXER_CSOUND=74,
	GTK_SCINTILLA_LEXER_FREEBASIC=75,
	GTK_SCINTILLA_LEXER_INNOSETUP=76,
	GTK_SCINTILLA_LEXER_OPAL=77,
	GTK_SCINTILLA_LEXER_SPICE=78,
	GTK_SCINTILLA_LEXER_D=79,
	GTK_SCINTILLA_LEXER_CMAKE=80,
	GTK_SCINTILLA_LEXER_GAP=81,
	GTK_SCINTILLA_LEXER_PLM=82,
	GTK_SCINTILLA_LEXER_PROGRESS=83,
	GTK_SCINTILLA_LEXER_ABAQUS=84,
	GTK_SCINTILLA_LEXER_ASYMPTOTE=85,
	GTK_SCINTILLA_LEXER_R=86,
	GTK_SCINTILLA_LEXER_MAGIK=87,
	GTK_SCINTILLA_LEXER_POWERSHELL=88,
	GTK_SCINTILLA_LEXER_MYSQL=89,
	GTK_SCINTILLA_LEXER_PO=90,
	GTK_SCINTILLA_LEXER_TAL=91,
	GTK_SCINTILLA_LEXER_COBOL=92,
	GTK_SCINTILLA_LEXER_TACL=93,
	GTK_SCINTILLA_LEXER_SORCUS=94,
	GTK_SCINTILLA_LEXER_POWERPRO=95,
	GTK_SCINTILLA_LEXER_NIMROD=96,
	GTK_SCINTILLA_LEXER_SML=97,
	GTK_SCINTILLA_LEXER_MARKDOWN=98,
	GTK_SCINTILLA_LEXER_AUTOMATIC=1000
} GtkScintillaLexers;

typedef enum 
{
	GTK_SCINTILLA_MSG_START=2000,
	GTK_SCINTILLA_MSG_OPTIONAL_START=3000,
	GTK_SCINTILLA_MSG_LEXER_START=4000,
	GTK_SCINTILLA_MSG_ADDTEXT=2001,
	GTK_SCINTILLA_MSG_ADDSTYLEDTEXT=2002,
	GTK_SCINTILLA_MSG_INSERTTEXT=2003,
	GTK_SCINTILLA_MSG_CLEARALL=2004,
	GTK_SCINTILLA_MSG_CLEARDOCUMENTSTYLE=2005,
	GTK_SCINTILLA_MSG_GETLENGTH=2006,
	GTK_SCINTILLA_MSG_GETCHARAT=2007,
	GTK_SCINTILLA_MSG_GETCURRENTPOS=2008,
	GTK_SCINTILLA_MSG_GETANCHOR=2009,
	GTK_SCINTILLA_MSG_GETSTYLEAT=2010,
	GTK_SCINTILLA_MSG_REDO=2011,
	GTK_SCINTILLA_MSG_SETUNDOCOLLECTION=2012,
	GTK_SCINTILLA_MSG_SELECTALL=2013,
	GTK_SCINTILLA_MSG_SETSAVEPOINT=2014,
	GTK_SCINTILLA_MSG_GETSTYLEDTEXT=2015,
	GTK_SCINTILLA_MSG_CANREDO=2016,
	GTK_SCINTILLA_MSG_MARKERLINEFROMHANDLE=2017,
	GTK_SCINTILLA_MSG_MARKERDELETEHANDLE=2018,
	GTK_SCINTILLA_MSG_GETUNDOCOLLECTION=2019,
	GTK_SCINTILLA_MSG_GETVIEWWS=2020,
	GTK_SCINTILLA_MSG_SETVIEWWS=2021,
	GTK_SCINTILLA_MSG_POSITIONFROMPOINT=2022,
	GTK_SCINTILLA_MSG_POSITIONFROMPOINTCLOSE=2023,
	GTK_SCINTILLA_MSG_GOTOLINE=2024,
	GTK_SCINTILLA_MSG_GOTOPOS=2025,
	GTK_SCINTILLA_MSG_SETANCHOR=2026,
	GTK_SCINTILLA_MSG_GETCURLINE=2027,
	GTK_SCINTILLA_MSG_GETENDSTYLED=2028,
	GTK_SCINTILLA_MSG_CONVERTEOLS=2029,
	GTK_SCINTILLA_MSG_GETEOLMODE=2030,
	GTK_SCINTILLA_MSG_SETEOLMODE=2031,
	GTK_SCINTILLA_MSG_STARTSTYLING=2032,
	GTK_SCINTILLA_MSG_SETSTYLING=2033,
	GTK_SCINTILLA_MSG_GETBUFFEREDDRAW=2034,
	GTK_SCINTILLA_MSG_SETBUFFEREDDRAW=2035,
	GTK_SCINTILLA_MSG_SETTABWIDTH=2036,
	GTK_SCINTILLA_MSG_GETTABWIDTH=2121,
	GTK_SCINTILLA_MSG_SETCODEPAGE=2037,
	GTK_SCINTILLA_MSG_SETUSEPALETTE=2039,
	GTK_SCINTILLA_MSG_MARKERDEFINE=2040,
	GTK_SCINTILLA_MSG_MARKERSETFORE=2041,
	GTK_SCINTILLA_MSG_MARKERSETBACK=2042,
	GTK_SCINTILLA_MSG_MARKERADD=2043,
	GTK_SCINTILLA_MSG_MARKERDELETE=2044,
	GTK_SCINTILLA_MSG_MARKERDELETEALL=2045,
	GTK_SCINTILLA_MSG_MARKERGET=2046,
	GTK_SCINTILLA_MSG_MARKERNEXT=2047,
	GTK_SCINTILLA_MSG_MARKERPREVIOUS=2048,
	GTK_SCINTILLA_MSG_MARKERDEFINEPIXMAP=2049,
	GTK_SCINTILLA_MSG_MARKERADDSET=2466,
	GTK_SCINTILLA_MSG_MARKERSETALPHA=2476,
	GTK_SCINTILLA_MSG_SETMARGINTYPEN=2240,
	GTK_SCINTILLA_MSG_GETMARGINTYPEN=2241,
	GTK_SCINTILLA_MSG_SETMARGINWIDTHN=2242,
	GTK_SCINTILLA_MSG_GETMARGINWIDTHN=2243,
	GTK_SCINTILLA_MSG_SETMARGINMASKN=2244,
	GTK_SCINTILLA_MSG_GETMARGINMASKN=2245,
	GTK_SCINTILLA_MSG_SETMARGINSENSITIVEN=2246,
	GTK_SCINTILLA_MSG_GETMARGINSENSITIVEN=2247,
	GTK_SCINTILLA_MSG_STYLECLEARALL=2050,
	GTK_SCINTILLA_MSG_STYLESETFORE=2051,
	GTK_SCINTILLA_MSG_STYLESETBACK=2052,
	GTK_SCINTILLA_MSG_STYLESETBOLD=2053,
	GTK_SCINTILLA_MSG_STYLESETITALIC=2054,
	GTK_SCINTILLA_MSG_STYLESETSIZE=2055,
	GTK_SCINTILLA_MSG_STYLESETFONT=2056,
	GTK_SCINTILLA_MSG_STYLESETEOLFILLED=2057,
	GTK_SCINTILLA_MSG_STYLERESETDEFAULT=2058,
	GTK_SCINTILLA_MSG_STYLESETUNDERLINE=2059,
	GTK_SCINTILLA_MSG_STYLEGETFORE=2481,
	GTK_SCINTILLA_MSG_STYLEGETBACK=2482,
	GTK_SCINTILLA_MSG_STYLEGETBOLD=2483,
	GTK_SCINTILLA_MSG_STYLEGETITALIC=2484,
	GTK_SCINTILLA_MSG_STYLEGETSIZE=2485,
	GTK_SCINTILLA_MSG_STYLEGETFONT=2486,
	GTK_SCINTILLA_MSG_STYLEGETEOLFILLED=2487,
	GTK_SCINTILLA_MSG_STYLEGETUNDERLINE=2488,
	GTK_SCINTILLA_MSG_STYLEGETCASE=2489,
	GTK_SCINTILLA_MSG_STYLEGETCHARACTERSET=2490,
	GTK_SCINTILLA_MSG_STYLEGETVISIBLE=2491,
	GTK_SCINTILLA_MSG_STYLEGETCHANGEABLE=2492,
	GTK_SCINTILLA_MSG_STYLEGETHOTSPOT=2493,
	GTK_SCINTILLA_MSG_STYLESETCASE=2060,
	GTK_SCINTILLA_MSG_STYLESETCHARACTERSET=2066,
	GTK_SCINTILLA_MSG_STYLESETHOTSPOT=2409,
	GTK_SCINTILLA_MSG_SETSELFORE=2067,
	GTK_SCINTILLA_MSG_SETSELBACK=2068,
	GTK_SCINTILLA_MSG_GETSELALPHA=2477,
	GTK_SCINTILLA_MSG_SETSELALPHA=2478,
	GTK_SCINTILLA_MSG_GETSELEOLFILLED=2479,
	GTK_SCINTILLA_MSG_SETSELEOLFILLED=2480,
	GTK_SCINTILLA_MSG_SETCARETFORE=2069,
	GTK_SCINTILLA_MSG_ASSIGNCMDKEY=2070,
	GTK_SCINTILLA_MSG_CLEARCMDKEY=2071,
	GTK_SCINTILLA_MSG_CLEARALLCMDKEYS=2072,
	GTK_SCINTILLA_MSG_SETSTYLINGEX=2073,
	GTK_SCINTILLA_MSG_STYLESETVISIBLE=2074,
	GTK_SCINTILLA_MSG_GETCARETPERIOD=2075,
	GTK_SCINTILLA_MSG_SETCARETPERIOD=2076,
	GTK_SCINTILLA_MSG_SETWORDCHARS=2077,
	GTK_SCINTILLA_MSG_BEGINUNDOACTION=2078,
	GTK_SCINTILLA_MSG_ENDUNDOACTION=2079,
	GTK_SCINTILLA_MSG_INDICSETSTYLE=2080,
	GTK_SCINTILLA_MSG_INDICGETSTYLE=2081,
	GTK_SCINTILLA_MSG_INDICSETFORE=2082,
	GTK_SCINTILLA_MSG_INDICGETFORE=2083,
	GTK_SCINTILLA_MSG_INDICSETUNDER=2510,
	GTK_SCINTILLA_MSG_INDICGETUNDER=2511,
	GTK_SCINTILLA_MSG_SETWHITESPACEFORE=2084,
	GTK_SCINTILLA_MSG_SETWHITESPACEBACK=2085,
	GTK_SCINTILLA_MSG_SETWHITESPACESIZE=2086,
	GTK_SCINTILLA_MSG_GETWHITESPACESIZE=2087,
	GTK_SCINTILLA_MSG_SETSTYLEBITS=2090,
	GTK_SCINTILLA_MSG_GETSTYLEBITS=2091,
	GTK_SCINTILLA_MSG_SETLINESTATE=2092,
	GTK_SCINTILLA_MSG_GETLINESTATE=2093,
	GTK_SCINTILLA_MSG_GETMAXLINESTATE=2094,
	GTK_SCINTILLA_MSG_GETCARETLINEVISIBLE=2095,
	GTK_SCINTILLA_MSG_SETCARETLINEVISIBLE=2096,
	GTK_SCINTILLA_MSG_GETCARETLINEBACK=2097,
	GTK_SCINTILLA_MSG_SETCARETLINEBACK=2098,
	GTK_SCINTILLA_MSG_STYLESETCHANGEABLE=2099,
	GTK_SCINTILLA_MSG_AUTOCSHOW=2100,
	GTK_SCINTILLA_MSG_AUTOCCANCEL=2101,
	GTK_SCINTILLA_MSG_AUTOCACTIVE=2102,
	GTK_SCINTILLA_MSG_AUTOCPOSSTART=2103,
	GTK_SCINTILLA_MSG_AUTOCCOMPLETE=2104,
	GTK_SCINTILLA_MSG_AUTOCSTOPS=2105,
	GTK_SCINTILLA_MSG_AUTOCSETSEPARATOR=2106,
	GTK_SCINTILLA_MSG_AUTOCGETSEPARATOR=2107,
	GTK_SCINTILLA_MSG_AUTOCSELECT=2108,
	GTK_SCINTILLA_MSG_AUTOCSETCANCELATSTART=2110,
	GTK_SCINTILLA_MSG_AUTOCGETCANCELATSTART=2111,
	GTK_SCINTILLA_MSG_AUTOCSETFILLUPS=2112,
	GTK_SCINTILLA_MSG_AUTOCSETCHOOSESINGLE=2113,
	GTK_SCINTILLA_MSG_AUTOCGETCHOOSESINGLE=2114,
	GTK_SCINTILLA_MSG_AUTOCSETIGNORECASE=2115,
	GTK_SCINTILLA_MSG_AUTOCGETIGNORECASE=2116,
	GTK_SCINTILLA_MSG_USERLISTSHOW=2117,
	GTK_SCINTILLA_MSG_AUTOCSETAUTOHIDE=2118,
	GTK_SCINTILLA_MSG_AUTOCGETAUTOHIDE=2119,
	GTK_SCINTILLA_MSG_AUTOCSETDROPRESTOFWORD=2270,
	GTK_SCINTILLA_MSG_AUTOCGETDROPRESTOFWORD=2271,
	GTK_SCINTILLA_MSG_REGISTERIMAGE=2405,
	GTK_SCINTILLA_MSG_CLEARREGISTEREDIMAGES=2408,
	GTK_SCINTILLA_MSG_AUTOCGETTYPESEPARATOR=2285,
	GTK_SCINTILLA_MSG_AUTOCSETTYPESEPARATOR=2286,
	GTK_SCINTILLA_MSG_AUTOCSETMAXWIDTH=2208,
	GTK_SCINTILLA_MSG_AUTOCGETMAXWIDTH=2209,
	GTK_SCINTILLA_MSG_AUTOCSETMAXHEIGHT=2210,
	GTK_SCINTILLA_MSG_AUTOCGETMAXHEIGHT=2211,
	GTK_SCINTILLA_MSG_SETINDENT=2122,
	GTK_SCINTILLA_MSG_GETINDENT=2123,
	GTK_SCINTILLA_MSG_SETUSETABS=2124,
	GTK_SCINTILLA_MSG_GETUSETABS=2125,
	GTK_SCINTILLA_MSG_SETLINEINDENTATION=2126,
	GTK_SCINTILLA_MSG_GETLINEINDENTATION=2127,
	GTK_SCINTILLA_MSG_GETLINEINDENTPOSITION=2128,
	GTK_SCINTILLA_MSG_GETCOLUMN=2129,
	GTK_SCINTILLA_MSG_SETHSCROLLBAR=2130,
	GTK_SCINTILLA_MSG_GETHSCROLLBAR=2131,
	GTK_SCINTILLA_MSG_SETINDENTATIONGUIDES=2132,
	GTK_SCINTILLA_MSG_GETINDENTATIONGUIDES=2133,
	GTK_SCINTILLA_MSG_SETHIGHLIGHTGUIDE=2134,
	GTK_SCINTILLA_MSG_GETHIGHLIGHTGUIDE=2135,
	GTK_SCINTILLA_MSG_GETLINEENDPOSITION=2136,
	GTK_SCINTILLA_MSG_GETCODEPAGE=2137,
	GTK_SCINTILLA_MSG_GETCARETFORE=2138,
	GTK_SCINTILLA_MSG_GETUSEPALETTE=2139,
	GTK_SCINTILLA_MSG_GETREADONLY=2140,
	GTK_SCINTILLA_MSG_SETCURRENTPOS=2141,
	GTK_SCINTILLA_MSG_SETSELECTIONSTART=2142,
	GTK_SCINTILLA_MSG_GETSELECTIONSTART=2143,
	GTK_SCINTILLA_MSG_SETSELECTIONEND=2144,
	GTK_SCINTILLA_MSG_GETSELECTIONEND=2145,
	GTK_SCINTILLA_MSG_SETPRINTMAGNIFICATION=2146,
	GTK_SCINTILLA_MSG_GETPRINTMAGNIFICATION=2147,
	GTK_SCINTILLA_MSG_SETPRINTCOLOURMODE=2148,
	GTK_SCINTILLA_MSG_GETPRINTCOLOURMODE=2149,
	GTK_SCINTILLA_MSG_FINDTEXT=2150,
	GTK_SCINTILLA_MSG_FORMATRANGE=2151,
	GTK_SCINTILLA_MSG_GETFIRSTVISIBLELINE=2152,
	GTK_SCINTILLA_MSG_GETLINE=2153,
	GTK_SCINTILLA_MSG_GETLINECOUNT=2154,
	GTK_SCINTILLA_MSG_SETMARGINLEFT=2155,
	GTK_SCINTILLA_MSG_GETMARGINLEFT=2156,
	GTK_SCINTILLA_MSG_SETMARGINRIGHT=2157,
	GTK_SCINTILLA_MSG_GETMARGINRIGHT=2158,
	GTK_SCINTILLA_MSG_GETMODIFY=2159,
	GTK_SCINTILLA_MSG_SETSEL=2160,
	GTK_SCINTILLA_MSG_GETSELTEXT=2161,
	GTK_SCINTILLA_MSG_GETTEXTRANGE=2162,
	GTK_SCINTILLA_MSG_HIDESELECTION=2163,
	GTK_SCINTILLA_MSG_POINTXFROMPOSITION=2164,
	GTK_SCINTILLA_MSG_POINTYFROMPOSITION=2165,
	GTK_SCINTILLA_MSG_LINEFROMPOSITION=2166,
	GTK_SCINTILLA_MSG_POSITIONFROMLINE=2167,
	GTK_SCINTILLA_MSG_LINESCROLL=2168,
	GTK_SCINTILLA_MSG_SCROLLCARET=2169,
	GTK_SCINTILLA_MSG_REPLACESEL=2170,
	GTK_SCINTILLA_MSG_SETREADONLY=2171,
	GTK_SCINTILLA_MSG_NULL=2172,
	GTK_SCINTILLA_MSG_CANPASTE=2173,
	GTK_SCINTILLA_MSG_CANUNDO=2174,
	GTK_SCINTILLA_MSG_EMPTYUNDOBUFFER=2175,
	GTK_SCINTILLA_MSG_UNDO=2176,
	GTK_SCINTILLA_MSG_CUT=2177,
	GTK_SCINTILLA_MSG_COPY=2178,
	GTK_SCINTILLA_MSG_PASTE=2179,
	GTK_SCINTILLA_MSG_CLEAR=2180,
	GTK_SCINTILLA_MSG_SETTEXT=2181,
	GTK_SCINTILLA_MSG_GETTEXT=2182,
	GTK_SCINTILLA_MSG_GETTEXTLENGTH=2183,
	GTK_SCINTILLA_MSG_GETDIRECTFUNCTION=2184,
	GTK_SCINTILLA_MSG_GETDIRECTPOINTER=2185,
	GTK_SCINTILLA_MSG_SETOVERTYPE=2186,
	GTK_SCINTILLA_MSG_GETOVERTYPE=2187,
	GTK_SCINTILLA_MSG_SETCARETWIDTH=2188,
	GTK_SCINTILLA_MSG_GETCARETWIDTH=2189,
	GTK_SCINTILLA_MSG_SETTARGETSTART=2190,
	GTK_SCINTILLA_MSG_GETTARGETSTART=2191,
	GTK_SCINTILLA_MSG_SETTARGETEND=2192,
	GTK_SCINTILLA_MSG_GETTARGETEND=2193,
	GTK_SCINTILLA_MSG_REPLACETARGET=2194,
	GTK_SCINTILLA_MSG_REPLACETARGETRE=2195,
	GTK_SCINTILLA_MSG_SEARCHINTARGET=2197,
	GTK_SCINTILLA_MSG_SETSEARCHFLAGS=2198,
	GTK_SCINTILLA_MSG_GETSEARCHFLAGS=2199,
	GTK_SCINTILLA_MSG_CALLTIPSHOW=2200,
	GTK_SCINTILLA_MSG_CALLTIPCANCEL=2201,
	GTK_SCINTILLA_MSG_CALLTIPACTIVE=2202,
	GTK_SCINTILLA_MSG_CALLTIPPOSSTART=2203,
	GTK_SCINTILLA_MSG_CALLTIPSETHLT=2204,
	GTK_SCINTILLA_MSG_CALLTIPSETBACK=2205,
	GTK_SCINTILLA_MSG_CALLTIPSETFORE=2206,
	GTK_SCINTILLA_MSG_CALLTIPSETFOREHLT=2207,
	GTK_SCINTILLA_MSG_CALLTIPUSESTYLE=2212,
	GTK_SCINTILLA_MSG_VISIBLEFROMDOCLINE=2220,
	GTK_SCINTILLA_MSG_DOCLINEFROMVISIBLE=2221,
	GTK_SCINTILLA_MSG_WRAPCOUNT=2235,
	GTK_SCINTILLA_MSG_SETFOLDLEVEL=2222,
	GTK_SCINTILLA_MSG_GETFOLDLEVEL=2223,
	GTK_SCINTILLA_MSG_GETLASTCHILD=2224,
	GTK_SCINTILLA_MSG_GETFOLDPARENT=2225,
	GTK_SCINTILLA_MSG_SHOWLINES=2226,
	GTK_SCINTILLA_MSG_HIDELINES=2227,
	GTK_SCINTILLA_MSG_GETLINEVISIBLE=2228,
	GTK_SCINTILLA_MSG_SETFOLDEXPANDED=2229,
	GTK_SCINTILLA_MSG_GETFOLDEXPANDED=2230,
	GTK_SCINTILLA_MSG_TOGGLEFOLD=2231,
	GTK_SCINTILLA_MSG_ENSUREVISIBLE=2232,
	GTK_SCINTILLA_MSG_SETFOLDFLAGS=2233,
	GTK_SCINTILLA_MSG_ENSUREVISIBLEENFORCEPOLICY=2234,
	GTK_SCINTILLA_MSG_SETTABINDENTS=2260,
	GTK_SCINTILLA_MSG_GETTABINDENTS=2261,
	GTK_SCINTILLA_MSG_SETBACKSPACEUNINDENTS=2262,
	GTK_SCINTILLA_MSG_GETBACKSPACEUNINDENTS=2263,
	GTK_SCINTILLA_MSG_SETMOUSEDWELLTIME=2264,
	GTK_SCINTILLA_MSG_GETMOUSEDWELLTIME=2265,
	GTK_SCINTILLA_MSG_WORDSTARTPOSITION=2266,
	GTK_SCINTILLA_MSG_WORDENDPOSITION=2267,
	GTK_SCINTILLA_MSG_SETWRAPMODE=2268,
	GTK_SCINTILLA_MSG_GETWRAPMODE=2269,
	GTK_SCINTILLA_MSG_SETWRAPVISUALFLAGS=2460,
	GTK_SCINTILLA_MSG_GETWRAPVISUALFLAGS=2461,
	GTK_SCINTILLA_MSG_SETWRAPVISUALFLAGSLOCATION=2462,
	GTK_SCINTILLA_MSG_GETWRAPVISUALFLAGSLOCATION=2463,
	GTK_SCINTILLA_MSG_SETWRAPSTARTINDENT=2464,
	GTK_SCINTILLA_MSG_GETWRAPSTARTINDENT=2465,
	GTK_SCINTILLA_MSG_SETWRAPINDENTMODE=2472,
	GTK_SCINTILLA_MSG_GETWRAPINDENTMODE=2473,
	GTK_SCINTILLA_MSG_SETLAYOUTCACHE=2272,
	GTK_SCINTILLA_MSG_GETLAYOUTCACHE=2273,
	GTK_SCINTILLA_MSG_SETSCROLLWIDTH=2274,
	GTK_SCINTILLA_MSG_GETSCROLLWIDTH=2275,
	GTK_SCINTILLA_MSG_SETSCROLLWIDTHTRACKING=2516,
	GTK_SCINTILLA_MSG_GETSCROLLWIDTHTRACKING=2517,
	GTK_SCINTILLA_MSG_TEXTWIDTH=2276,
	GTK_SCINTILLA_MSG_SETENDATLASTLINE=2277,
	GTK_SCINTILLA_MSG_GETENDATLASTLINE=2278,
	GTK_SCINTILLA_MSG_TEXTHEIGHT=2279,
	GTK_SCINTILLA_MSG_SETVSCROLLBAR=2280,
	GTK_SCINTILLA_MSG_GETVSCROLLBAR=2281,
	GTK_SCINTILLA_MSG_APPENDTEXT=2282,
	GTK_SCINTILLA_MSG_GETTWOPHASEDRAW=2283,
	GTK_SCINTILLA_MSG_SETTWOPHASEDRAW=2284,
	GTK_SCINTILLA_MSG_SETFONTQUALITY=2611,
	GTK_SCINTILLA_MSG_GETFONTQUALITY=2612,
	GTK_SCINTILLA_MSG_SETFIRSTVISIBLELINE=2613,
	GTK_SCINTILLA_MSG_SETMULTIPASTE=2614,
	GTK_SCINTILLA_MSG_GETMULTIPASTE=2615,
	GTK_SCINTILLA_MSG_GETTAG=2616,
	GTK_SCINTILLA_MSG_TARGETFROMSELECTION=2287,
	GTK_SCINTILLA_MSG_LINESJOIN=2288,
	GTK_SCINTILLA_MSG_LINESSPLIT=2289,
	GTK_SCINTILLA_MSG_SETFOLDMARGINCOLOUR=2290,
	GTK_SCINTILLA_MSG_SETFOLDMARGINHICOLOUR=2291,
	GTK_SCINTILLA_MSG_LINEDOWN=2300,
	GTK_SCINTILLA_MSG_LINEDOWNEXTEND=2301,
	GTK_SCINTILLA_MSG_LINEUP=2302,
	GTK_SCINTILLA_MSG_LINEUPEXTEND=2303,
	GTK_SCINTILLA_MSG_CHARLEFT=2304,
	GTK_SCINTILLA_MSG_CHARLEFTEXTEND=2305,
	GTK_SCINTILLA_MSG_CHARRIGHT=2306,
	GTK_SCINTILLA_MSG_CHARRIGHTEXTEND=2307,
	GTK_SCINTILLA_MSG_WORDLEFT=2308,
	GTK_SCINTILLA_MSG_WORDLEFTEXTEND=2309,
	GTK_SCINTILLA_MSG_WORDRIGHT=2310,
	GTK_SCINTILLA_MSG_WORDRIGHTEXTEND=2311,
	GTK_SCINTILLA_MSG_HOME=2312,
	GTK_SCINTILLA_MSG_HOMEEXTEND=2313,
	GTK_SCINTILLA_MSG_LINEEND=2314,
	GTK_SCINTILLA_MSG_LINEENDEXTEND=2315,
	GTK_SCINTILLA_MSG_DOCUMENTSTART=2316,
	GTK_SCINTILLA_MSG_DOCUMENTSTARTEXTEND=2317,
	GTK_SCINTILLA_MSG_DOCUMENTEND=2318,
	GTK_SCINTILLA_MSG_DOCUMENTENDEXTEND=2319,
	GTK_SCINTILLA_MSG_PAGEUP=2320,
	GTK_SCINTILLA_MSG_PAGEUPEXTEND=2321,
	GTK_SCINTILLA_MSG_PAGEDOWN=2322,
	GTK_SCINTILLA_MSG_PAGEDOWNEXTEND=2323,
	GTK_SCINTILLA_MSG_EDITTOGGLEOVERTYPE=2324,
	GTK_SCINTILLA_MSG_CANCEL=2325,
	GTK_SCINTILLA_MSG_DELETEBACK=2326,
	GTK_SCINTILLA_MSG_TAB=2327,
	GTK_SCINTILLA_MSG_BACKTAB=2328,
	GTK_SCINTILLA_MSG_NEWLINE=2329,
	GTK_SCINTILLA_MSG_FORMFEED=2330,
	GTK_SCINTILLA_MSG_VCHOME=2331,
	GTK_SCINTILLA_MSG_VCHOMEEXTEND=2332,
	GTK_SCINTILLA_MSG_ZOOMIN=2333,
	GTK_SCINTILLA_MSG_ZOOMOUT=2334,
	GTK_SCINTILLA_MSG_DELWORDLEFT=2335,
	GTK_SCINTILLA_MSG_DELWORDRIGHT=2336,
	GTK_SCINTILLA_MSG_DELWORDRIGHTEND=2518,
	GTK_SCINTILLA_MSG_LINECUT=2337,
	GTK_SCINTILLA_MSG_LINEDELETE=2338,
	GTK_SCINTILLA_MSG_LINETRANSPOSE=2339,
	GTK_SCINTILLA_MSG_LINEDUPLICATE=2404,
	GTK_SCINTILLA_MSG_LOWERCASE=2340,
	GTK_SCINTILLA_MSG_UPPERCASE=2341,
	GTK_SCINTILLA_MSG_LINESCROLLDOWN=2342,
	GTK_SCINTILLA_MSG_LINESCROLLUP=2343,
	GTK_SCINTILLA_MSG_DELETEBACKNOTLINE=2344,
	GTK_SCINTILLA_MSG_HOMEDISPLAY=2345,
	GTK_SCINTILLA_MSG_HOMEDISPLAYEXTEND=2346,
	GTK_SCINTILLA_MSG_LINEENDDISPLAY=2347,
	GTK_SCINTILLA_MSG_LINEENDDISPLAYEXTEND=2348,
	GTK_SCINTILLA_MSG_HOMEWRAP=2349,
	GTK_SCINTILLA_MSG_HOMEWRAPEXTEND=2450,
	GTK_SCINTILLA_MSG_LINEENDWRAP=2451,
	GTK_SCINTILLA_MSG_LINEENDWRAPEXTEND=2452,
	GTK_SCINTILLA_MSG_VCHOMEWRAP=2453,
	GTK_SCINTILLA_MSG_VCHOMEWRAPEXTEND=2454,
	GTK_SCINTILLA_MSG_LINECOPY=2455,
	GTK_SCINTILLA_MSG_MOVECARETINSIDEVIEW=2401,
	GTK_SCINTILLA_MSG_LINELENGTH=2350,
	GTK_SCINTILLA_MSG_BRACEHIGHLIGHT=2351,
	GTK_SCINTILLA_MSG_BRACEBADLIGHT=2352,
	GTK_SCINTILLA_MSG_BRACEMATCH=2353,
	GTK_SCINTILLA_MSG_GETVIEWEOL=2355,
	GTK_SCINTILLA_MSG_SETVIEWEOL=2356,
	GTK_SCINTILLA_MSG_GETDOCPOINTER=2357,
	GTK_SCINTILLA_MSG_SETDOCPOINTER=2358,
	GTK_SCINTILLA_MSG_SETMODEVENTMASK=2359,
	GTK_SCINTILLA_MSG_GETEDGECOLUMN=2360,
	GTK_SCINTILLA_MSG_SETEDGECOLUMN=2361,
	GTK_SCINTILLA_MSG_GETEDGEMODE=2362,
	GTK_SCINTILLA_MSG_SETEDGEMODE=2363,
	GTK_SCINTILLA_MSG_GETEDGECOLOUR=2364,
	GTK_SCINTILLA_MSG_SETEDGECOLOUR=2365,
	GTK_SCINTILLA_MSG_SEARCHANCHOR=2366,
	GTK_SCINTILLA_MSG_SEARCHNEXT=2367,
	GTK_SCINTILLA_MSG_SEARCHPREV=2368,
	GTK_SCINTILLA_MSG_LINESONSCREEN=2370,
	GTK_SCINTILLA_MSG_USEPOPUP=2371,
	GTK_SCINTILLA_MSG_SELECTIONISRECTANGLE=2372,
	GTK_SCINTILLA_MSG_SETZOOM=2373,
	GTK_SCINTILLA_MSG_GETZOOM=2374,
	GTK_SCINTILLA_MSG_CREATEDOCUMENT=2375,
	GTK_SCINTILLA_MSG_ADDREFDOCUMENT=2376,
	GTK_SCINTILLA_MSG_RELEASEDOCUMENT=2377,
	GTK_SCINTILLA_MSG_GETMODEVENTMASK=2378,
	GTK_SCINTILLA_MSG_SETFOCUS=2380,
	GTK_SCINTILLA_MSG_GETFOCUS=2381,
	GTK_SCINTILLA_MSG_SETSTATUS=2382,
	GTK_SCINTILLA_MSG_GETSTATUS=2383,
	GTK_SCINTILLA_MSG_SETMOUSEDOWNCAPTURES=2384,
	GTK_SCINTILLA_MSG_GETMOUSEDOWNCAPTURES=2385,
	GTK_SCINTILLA_MSG_SETCURSOR=2386,
	GTK_SCINTILLA_MSG_GETCURSOR=2387,
	GTK_SCINTILLA_MSG_SETCONTROLCHARSYMBOL=2388,
	GTK_SCINTILLA_MSG_GETCONTROLCHARSYMBOL=2389,
	GTK_SCINTILLA_MSG_WORDPARTLEFT=2390,
	GTK_SCINTILLA_MSG_WORDPARTLEFTEXTEND=2391,
	GTK_SCINTILLA_MSG_WORDPARTRIGHT=2392,
	GTK_SCINTILLA_MSG_WORDPARTRIGHTEXTEND=2393,
	GTK_SCINTILLA_MSG_SETVISIBLEPOLICY=2394,
	GTK_SCINTILLA_MSG_DELLINELEFT=2395,
	GTK_SCINTILLA_MSG_DELLINERIGHT=2396,
	GTK_SCINTILLA_MSG_SETXOFFSET=2397,
	GTK_SCINTILLA_MSG_GETXOFFSET=2398,
	GTK_SCINTILLA_MSG_CHOOSECARETX=2399,
	GTK_SCINTILLA_MSG_GRABFOCUS=2400,
	GTK_SCINTILLA_MSG_SETXCARETPOLICY=2402,
	GTK_SCINTILLA_MSG_SETYCARETPOLICY=2403,
	GTK_SCINTILLA_MSG_SETPRINTWRAPMODE=2406,
	GTK_SCINTILLA_MSG_GETPRINTWRAPMODE=2407,
	GTK_SCINTILLA_MSG_SETHOTSPOTACTIVEFORE=2410,
	GTK_SCINTILLA_MSG_GETHOTSPOTACTIVEFORE=2494,
	GTK_SCINTILLA_MSG_SETHOTSPOTACTIVEBACK=2411,
	GTK_SCINTILLA_MSG_GETHOTSPOTACTIVEBACK=2495,
	GTK_SCINTILLA_MSG_SETHOTSPOTACTIVEUNDERLINE=2412,
	GTK_SCINTILLA_MSG_GETHOTSPOTACTIVEUNDERLINE=2496,
	GTK_SCINTILLA_MSG_SETHOTSPOTSINGLELINE=2421,
	GTK_SCINTILLA_MSG_GETHOTSPOTSINGLELINE=2497,
	GTK_SCINTILLA_MSG_PARADOWN=2413,
	GTK_SCINTILLA_MSG_PARADOWNEXTEND=2414,
	GTK_SCINTILLA_MSG_PARAUP=2415,
	GTK_SCINTILLA_MSG_PARAUPEXTEND=2416,
	GTK_SCINTILLA_MSG_POSITIONBEFORE=2417,
	GTK_SCINTILLA_MSG_POSITIONAFTER=2418,
	GTK_SCINTILLA_MSG_COPYRANGE=2419,
	GTK_SCINTILLA_MSG_COPYTEXT=2420,
	GTK_SCINTILLA_MSG_SETSELECTIONMODE=2422,
	GTK_SCINTILLA_MSG_GETSELECTIONMODE=2423,
	GTK_SCINTILLA_MSG_GETLINESELSTARTPOSITION=2424,
	GTK_SCINTILLA_MSG_GETLINESELENDPOSITION=2425,
	GTK_SCINTILLA_MSG_LINEDOWNRECTEXTEND=2426,
	GTK_SCINTILLA_MSG_LINEUPRECTEXTEND=2427,
	GTK_SCINTILLA_MSG_CHARLEFTRECTEXTEND=2428,
	GTK_SCINTILLA_MSG_CHARRIGHTRECTEXTEND=2429,
	GTK_SCINTILLA_MSG_HOMERECTEXTEND=2430,
	GTK_SCINTILLA_MSG_VCHOMERECTEXTEND=2431,
	GTK_SCINTILLA_MSG_LINEENDRECTEXTEND=2432,
	GTK_SCINTILLA_MSG_PAGEUPRECTEXTEND=2433,
	GTK_SCINTILLA_MSG_PAGEDOWNRECTEXTEND=2434,
	GTK_SCINTILLA_MSG_STUTTEREDPAGEUP=2435,
	GTK_SCINTILLA_MSG_STUTTEREDPAGEUPEXTEND=2436,
	GTK_SCINTILLA_MSG_STUTTEREDPAGEDOWN=2437,
	GTK_SCINTILLA_MSG_STUTTEREDPAGEDOWNEXTEND=2438,
	GTK_SCINTILLA_MSG_WORDLEFTEND=2439,
	GTK_SCINTILLA_MSG_WORDLEFTENDEXTEND=2440,
	GTK_SCINTILLA_MSG_WORDRIGHTEND=2441,
	GTK_SCINTILLA_MSG_WORDRIGHTENDEXTEND=2442,
	GTK_SCINTILLA_MSG_SETWHITESPACECHARS=2443,
	GTK_SCINTILLA_MSG_SETCHARSDEFAULT=2444,
	GTK_SCINTILLA_MSG_AUTOCGETCURRENT=2445,
	GTK_SCINTILLA_MSG_AUTOCGETCURRENTTEXT=2610,
	GTK_SCINTILLA_MSG_ALLOCATE=2446,
	GTK_SCINTILLA_MSG_TARGETASUTF8=2447,
	GTK_SCINTILLA_MSG_SETLENGTHFORENCODE=2448,
	GTK_SCINTILLA_MSG_ENCODEDFROMUTF8=2449,
	GTK_SCINTILLA_MSG_FINDCOLUMN=2456,
	GTK_SCINTILLA_MSG_GETCARETSTICKY=2457,
	GTK_SCINTILLA_MSG_SETCARETSTICKY=2458,
	GTK_SCINTILLA_MSG_TOGGLECARETSTICKY=2459,
	GTK_SCINTILLA_MSG_SETPASTECONVERTENDINGS=2467,
	GTK_SCINTILLA_MSG_GETPASTECONVERTENDINGS=2468,
	GTK_SCINTILLA_MSG_SELECTIONDUPLICATE=2469,
	GTK_SCINTILLA_MSG_SETCARETLINEBACKALPHA=2470,
	GTK_SCINTILLA_MSG_GETCARETLINEBACKALPHA=2471,
	GTK_SCINTILLA_MSG_SETCARETSTYLE=2512,
	GTK_SCINTILLA_MSG_GETCARETSTYLE=2513,
	GTK_SCINTILLA_MSG_SETINDICATORCURRENT=2500,
	GTK_SCINTILLA_MSG_GETINDICATORCURRENT=2501,
	GTK_SCINTILLA_MSG_SETINDICATORVALUE=2502,
	GTK_SCINTILLA_MSG_GETINDICATORVALUE=2503,
	GTK_SCINTILLA_MSG_INDICATORFILLRANGE=2504,
	GTK_SCINTILLA_MSG_INDICATORCLEARRANGE=2505,
	GTK_SCINTILLA_MSG_INDICATORALLONFOR=2506,
	GTK_SCINTILLA_MSG_INDICATORVALUEAT=2507,
	GTK_SCINTILLA_MSG_INDICATORSTART=2508,
	GTK_SCINTILLA_MSG_INDICATOREND=2509,
	GTK_SCINTILLA_MSG_SETPOSITIONCACHE=2514,
	GTK_SCINTILLA_MSG_GETPOSITIONCACHE=2515,
	GTK_SCINTILLA_MSG_COPYALLOWLINE=2519,
	GTK_SCINTILLA_MSG_GETCHARACTERPOINTER=2520,
	GTK_SCINTILLA_MSG_SETKEYSUNICODE=2521,
	GTK_SCINTILLA_MSG_GETKEYSUNICODE=2522,
	GTK_SCINTILLA_MSG_INDICSETALPHA=2523,
	GTK_SCINTILLA_MSG_INDICGETALPHA=2524,
	GTK_SCINTILLA_MSG_SETEXTRAASCENT=2525,
	GTK_SCINTILLA_MSG_GETEXTRAASCENT=2526,
	GTK_SCINTILLA_MSG_SETEXTRADESCENT=2527,
	GTK_SCINTILLA_MSG_GETEXTRADESCENT=2528,
	GTK_SCINTILLA_MSG_MARKERSYMBOLDEFINED=2529,
	GTK_SCINTILLA_MSG_MARGINSETTEXT=2530,
	GTK_SCINTILLA_MSG_MARGINGETTEXT=2531,
	GTK_SCINTILLA_MSG_MARGINSETSTYLE=2532,
	GTK_SCINTILLA_MSG_MARGINGETSTYLE=2533,
	GTK_SCINTILLA_MSG_MARGINSETSTYLES=2534,
	GTK_SCINTILLA_MSG_MARGINGETSTYLES=2535,
	GTK_SCINTILLA_MSG_MARGINTEXTCLEARALL=2536,
	GTK_SCINTILLA_MSG_MARGINSETSTYLEOFFSET=2537,
	GTK_SCINTILLA_MSG_MARGINGETSTYLEOFFSET=2538,
	GTK_SCINTILLA_MSG_ANNOTATIONSETTEXT=2540,
	GTK_SCINTILLA_MSG_ANNOTATIONGETTEXT=2541,
	GTK_SCINTILLA_MSG_ANNOTATIONSETSTYLE=2542,
	GTK_SCINTILLA_MSG_ANNOTATIONGETSTYLE=2543,
	GTK_SCINTILLA_MSG_ANNOTATIONSETSTYLES=2544,
	GTK_SCINTILLA_MSG_ANNOTATIONGETSTYLES=2545,
	GTK_SCINTILLA_MSG_ANNOTATIONGETLINES=2546,
	GTK_SCINTILLA_MSG_ANNOTATIONCLEARALL=2547,
	GTK_SCINTILLA_MSG_ANNOTATIONSETVISIBLE=2548,
	GTK_SCINTILLA_MSG_ANNOTATIONGETVISIBLE=2549,
	GTK_SCINTILLA_MSG_ANNOTATIONSETSTYLEOFFSET=2550,
	GTK_SCINTILLA_MSG_ANNOTATIONGETSTYLEOFFSET=2551,
	GTK_SCINTILLA_MSG_ADDUNDOACTION=2560,
	GTK_SCINTILLA_MSG_CHARPOSITIONFROMPOINT=2561,
	GTK_SCINTILLA_MSG_CHARPOSITIONFROMPOINTCLOSE=2562,
	GTK_SCINTILLA_MSG_SETMULTIPLESELECTION=2563,
	GTK_SCINTILLA_MSG_GETMULTIPLESELECTION=2564,
	GTK_SCINTILLA_MSG_SETADDITIONALSELECTIONTYPING=2565,
	GTK_SCINTILLA_MSG_GETADDITIONALSELECTIONTYPING=2566,
	GTK_SCINTILLA_MSG_SETADDITIONALCARETSBLINK=2567,
	GTK_SCINTILLA_MSG_GETADDITIONALCARETSBLINK=2568,
	GTK_SCINTILLA_MSG_SETADDITIONALCARETSVISIBLE=2608,
	GTK_SCINTILLA_MSG_GETADDITIONALCARETSVISIBLE=2609,
	GTK_SCINTILLA_MSG_GETSELECTIONS=2570,
	GTK_SCINTILLA_MSG_CLEARSELECTIONS=2571,
	GTK_SCINTILLA_MSG_SETSELECTION=2572,
	GTK_SCINTILLA_MSG_ADDSELECTION=2573,
	GTK_SCINTILLA_MSG_SETMAINSELECTION=2574,
	GTK_SCINTILLA_MSG_GETMAINSELECTION=2575,
	GTK_SCINTILLA_MSG_SETSELECTIONNCARET=2576,
	GTK_SCINTILLA_MSG_GETSELECTIONNCARET=2577,
	GTK_SCINTILLA_MSG_SETSELECTIONNANCHOR=2578,
	GTK_SCINTILLA_MSG_GETSELECTIONNANCHOR=2579,
	GTK_SCINTILLA_MSG_SETSELECTIONNCARETVIRTUALSPACE=2580,
	GTK_SCINTILLA_MSG_GETSELECTIONNCARETVIRTUALSPACE=2581,
	GTK_SCINTILLA_MSG_SETSELECTIONNANCHORVIRTUALSPACE=2582,
	GTK_SCINTILLA_MSG_GETSELECTIONNANCHORVIRTUALSPACE=2583,
	GTK_SCINTILLA_MSG_SETSELECTIONNSTART=2584,
	GTK_SCINTILLA_MSG_GETSELECTIONNSTART=2585,
	GTK_SCINTILLA_MSG_SETSELECTIONNEND=2586,
	GTK_SCINTILLA_MSG_GETSELECTIONNEND=2587,
	GTK_SCINTILLA_MSG_SETRECTANGULARSELECTIONCARET=2588,
	GTK_SCINTILLA_MSG_GETRECTANGULARSELECTIONCARET=2589,
	GTK_SCINTILLA_MSG_SETRECTANGULARSELECTIONANCHOR=2590,
	GTK_SCINTILLA_MSG_GETRECTANGULARSELECTIONANCHOR=2591,
	GTK_SCINTILLA_MSG_SETRECTANGULARSELECTIONCARETVIRTUALSPACE=2592,
	GTK_SCINTILLA_MSG_GETRECTANGULARSELECTIONCARETVIRTUALSPACE=2593,
	GTK_SCINTILLA_MSG_SETRECTANGULARSELECTIONANCHORVIRTUALSPACE=2594,
	GTK_SCINTILLA_MSG_GETRECTANGULARSELECTIONANCHORVIRTUALSPACE=2595,
	GTK_SCINTILLA_MSG_SETVIRTUALSPACEOPTIONS=2596,
	GTK_SCINTILLA_MSG_GETVIRTUALSPACEOPTIONS=2597,
	GTK_SCINTILLA_MSG_SETRECTANGULARSELECTIONMODIFIER=2598,
	GTK_SCINTILLA_MSG_GETRECTANGULARSELECTIONMODIFIER=2599,
	GTK_SCINTILLA_MSG_SETADDITIONALSELFORE=2600,
	GTK_SCINTILLA_MSG_SETADDITIONALSELBACK=2601,
	GTK_SCINTILLA_MSG_SETADDITIONALSELALPHA=2602,
	GTK_SCINTILLA_MSG_GETADDITIONALSELALPHA=2603,
	GTK_SCINTILLA_MSG_SETADDITIONALCARETFORE=2604,
	GTK_SCINTILLA_MSG_GETADDITIONALCARETFORE=2605,
	GTK_SCINTILLA_MSG_ROTATESELECTION=2606,
	GTK_SCINTILLA_MSG_SWAPMAINANCHORCARET=2607,
	GTK_SCINTILLA_MSG_STARTRECORD=3001,
	GTK_SCINTILLA_MSG_STOPRECORD=3002,
	GTK_SCINTILLA_MSG_SETLEXER=4001,
	GTK_SCINTILLA_MSG_GETLEXER=4002,
	GTK_SCINTILLA_MSG_COLOURISE=4003,
	GTK_SCINTILLA_MSG_SETPROPERTY=4004,
	GTK_SCINTILLA_MSG_SETKEYWORDS=4005,
	GTK_SCINTILLA_MSG_SETLEXERLANGUAGE=4006,
	GTK_SCINTILLA_MSG_LOADLEXERLIBRARY=4007,
	GTK_SCINTILLA_MSG_GETPROPERTY=4008,
	GTK_SCINTILLA_MSG_GETPROPERTYEXPANDED=4009,
	GTK_SCINTILLA_MSG_GETPROPERTYINT=4010,
	GTK_SCINTILLA_MSG_GETSTYLEBITSNEEDED=4011,
	GTK_SCINTILLA_MSG_GETLEXERLANGUAGE=4012
} GtkScintillaMessages;

G_END_DECLS

#endif /* ifndef GTK_SCINTILLA_CONSTANTS_H */
