/*
 * style-properties.h
 *
 * Copyright 2011 Matthew Brush <mbrush@codebrainz.ca>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation; either version 2 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA 02110-1301, USA.
 */

#ifndef GTK_SCINTILLA_STYLE_PROPERTIES_H
#define GTK_SCINTILLA_STYLE_PROPERTIES_H

#include "gtkscintilla.h"

enum
{
	STYLE_PROP_SELECTION_BG_COLOR,
	STYLE_PROP_SELECTION_FG_COLOR,
	STYLE_PROP_SELECTION_BG_ALPHA,

	STYLE_PROP_CURRENT_LINE_HIGHLIGHT_ENABLED,
	STYLE_PROP_CURRENT_LINE_BG_COLOR,
	STYLE_PROP_CURRENT_LINE_BG_ALPHA,

	STYLE_PROP_BRACE_GOOD_BG_COLOR,
	STYLE_PROP_BRACE_GOOD_FG_COLOR,
	STYLE_PROP_BRACE_GOOD_FONT_DESC,

	STYLE_PROP_BRACE_BAD_BG_COLOR,
	STYLE_PROP_BRACE_BAD_FG_COLOR,
	STYLE_PROP_BRACE_BAD_FONT_DESC,

	STYLE_PROP_MARGIN_LINE_NUMBER_BG_COLOR,
	STYLE_PROP_MARGIN_LINE_NUMBER_FG_COLOR,
	STYLE_PROP_MARGIN_LINE_NUMBER_FONT_DESC,

	STYLE_PROP_MARGIN_FOLD_BG_COLOR,
	STYLE_PROP_MARGIN_FOLD_FG_COLOR,
	STYLE_PROP_MARGIN_FOLD_FONT_DESC,

	STYLE_PROP_MARGIN_SYMBOL_BG_COLOR,
	STYLE_PROP_MARGIN_SYMBOL_FG_COLOR,
	STYLE_PROP_MARGIN_SYMBOL_HIGHLIGHT_COLOR,

	STYLE_PROP_WHITESPACE_SYMBOLS_BG_COLOR,
	STYLE_PROP_WHITESPACE_SYMBOLS_FG_COLOR,

	STYLE_PROP_INDENTATION_GUIDES_BG_COLOR,
	STYLE_PROP_INDENTATION_GUIDES_FG_COLOR,

	STYLE_PROP_CURSOR_COLOR,
	STYLE_PROP_CURSOR_LINE_WIDTH,
	STYLE_PROP_CURSOR_BLOCK,
	STYLE_PROP_CURSOR_BLINK_PERIOD,

	STYLE_PROP_CALLTIP_BG_COLOR,
	STYLE_PROP_CALLTIP_FG_COLOR,
	STYLE_PROP_CALLTIP_FONT_DESC,

	STYLE_PROP_AUTO_COMPLETE_MAX_HEIGHT,
	STYLE_PROP_AUTO_COMPLETE_MAX_WIDTH,

	STYLE_PROP_LONG_LINE_EDGE_COLOR,

	STYLE_PROP_ACTIVE_HOTSPOT_BG_COLOR,
	STYLE_PROP_ACTIVE_HOTSPOT_FG_COLOR,
	STYLE_PROP_ACTIVE_HOTSPOT_UNDERLINE,
	STYLE_PROP_ACTIVE_HOTSPOT_SINGLE_LINE
};

void _gtk_scintilla_class_install_style_properties(GtkScintillaClass *klass);

#endif /* #ifndef GTK_SCINTILLA_STYLE_PROPERTIES_H */
