/*
 * utils.c
 *
 * Copyright 2011 Matthew Brush <mbrush@codebrainz.ca>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation; either version 2 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA 02110-1301, USA.
 */

/* utils.c generated by valac 0.10.0, the Vala compiler
 * generated from utils.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include "gtkscintillastyle.h"
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <gdk/gdk.h>

#define _g_free0(var) (var = (g_free (var), NULL))






char* gtk_scintilla_utils_int_to_color_spec (gint int_color) {
	char* result = NULL;
	gint red;
	gint green;
	gint blue;
	red = int_color & 255;
	green = (int_color >> 8) & 255;
	blue = (int_color >> 16) & 255;
	result = g_strdup_printf ("#%02X%02X%02X", (guint) red, (guint) green, (guint) blue);
	return result;
}


static glong string_get_length (const char* self) {
	glong result;
	g_return_val_if_fail (self != NULL, 0L);
	result = g_utf8_strlen (self, (gssize) (-1));
	return result;
}


static char* string_substring (const char* self, glong offset, glong len) {
	char* result = NULL;
	glong string_length;
	const char* start;
	g_return_val_if_fail (self != NULL, NULL);
	string_length = string_get_length (self);
	if (offset < 0) {
		offset = string_length + offset;
		g_return_val_if_fail (offset >= 0, NULL);
	} else {
		g_return_val_if_fail (offset <= string_length, NULL);
	}
	if (len < 0) {
		len = string_length - offset;
	}
	g_return_val_if_fail ((offset + len) <= string_length, NULL);
	start = g_utf8_offset_to_pointer (self, offset);
	result = g_strndup (start, ((gchar*) g_utf8_offset_to_pointer (start, len)) - ((gchar*) start));
	return result;
}


gint gtk_scintilla_utils_color_spec_to_int (const char* color_spec) {
	gint result = 0;
	gint red;
	gint green;
	gint blue;
	char* tmp;
	g_return_val_if_fail (color_spec != NULL, 0);
	red = 0;
	green = 0;
	blue = 0;
	tmp = NULL;
	if (g_str_has_prefix (color_spec, "0x")) {
		char* _tmp0_;
		char* _tmp1_;
		tmp = (_tmp1_ = (char*) g_utf8_strup (_tmp0_ = string_substring (color_spec, (glong) 2, -1), -1), _g_free0 (tmp), _tmp1_);
		_g_free0 (_tmp0_);
	}
	if (g_str_has_prefix (color_spec, "#")) {
		char* _tmp2_;
		char* _tmp3_;
		tmp = (_tmp3_ = (char*) g_utf8_strup (_tmp2_ = string_substring (color_spec, (glong) 1, -1), -1), _g_free0 (tmp), _tmp3_);
		_g_free0 (_tmp2_);
	} else {
		char* _tmp4_;
		tmp = (_tmp4_ = (char*) g_utf8_strup (color_spec, -1), _g_free0 (tmp), _tmp4_);
	}
	if (sscanf ("%02X%02X%02X", tmp, &red, &green, &blue) != 3) {
		result = -1;
		_g_free0 (tmp);
		return result;
	}
	result = (red | (green << 8)) | (blue << 16);
	_g_free0 (tmp);
	return result;
}


void gtk_scintilla_utils_int_to_gdk_color (gint int_color, GdkColor* result) {
	GdkColor color = {0};
	char* _tmp0_;
	gdk_color_parse (_tmp0_ = gtk_scintilla_utils_int_to_color_spec (int_color), &color);
	_g_free0 (_tmp0_);
	*result = color;
	return;
}


gint gtk_scintilla_utils_gdk_color_to_int (GdkColor* color) {
	gint result = 0;
	gint red;
	gint green;
	gint blue;
	red = (*color).red / 256;
	green = (*color).green / 256;
	blue = (*color).blue / 256;
	result = (red | (green << 8)) | (blue << 16);
	return result;
}


void gtk_scintilla_utils_color_spec_to_gdk_color (const char* color_spec, GdkColor* result) {
	GdkColor color = {0};
	g_return_if_fail (color_spec != NULL);
	gdk_color_parse (color_spec, &color);
	*result = color;
	return;
}


char* gtk_scintilla_utils_gdk_color_to_color_spec (GdkColor* color) {
	char* result = NULL;
	gint int_color;
	int_color = gtk_scintilla_utils_gdk_color_to_int (color);
	result = gtk_scintilla_utils_int_to_color_spec (int_color);
	return result;
}




